<div id="page-start"></div>
<!-- section start -->
<!-- ================ -->
<section class="section light-gray-bg clearfix">
	<div class="container">        
            
			<div class="col-md-12">
                
				<div class="tab-content clear-style">
					<div class="tab-pane active">
						<div class="row masonry-grid-fitrows grid-space-10" style="position: relative;">
                        <?php  
                            $locales = \Application\Module::getConfig('general.locales');
                            $request = $this->requestHelper();    
                            $products = !empty($result['data']) ? $result['data'] : array();
                            $limit = !empty($result['limit']) ? $result['limit'] : 20;
                            $count = !empty($result['count']) ? $result['count'] : 0;                       
                            if (!empty($products)) {
                                foreach ($products as $product) {
                                    echo $this->productItemHelper($product, 4);                                                                                                                    
                                }
                            } else {
                                echo "<center class=\"not-found\">{$this->translate('Product not found')}</center>";
                            }
                        ?>  
						</div>
					</div>
                    <!-- pagination start -->
                    <nav class="text-center">
                        <?php   
                            if ($count > $limit) {
                                echo $this->paginatorHelper(
                                    $params, 
                                    $count, 
                                    $limit
                                );
                            }
                        ?>
                    </nav>
                </div>
                
			</div>
		</div>
	</div>
</section>
<!-- section end -->
<div id="dialog-modal" class="modal fade" role="dialog" aria-labelledby="largeModal" aria-hidden="true">
    <div class="modal-dialog modal-lg"><div class="modal-content"></div></div>
</div>