<!-- main-container start -->
<!-- ================ -->
<div class="main-container dark-translucent-bg" style="background-image:url(&#39;/web/images/background-img-6.jpg&#39;);">
    <div class="container">
        <div class="row">
            <!-- main start -->
            <!-- ================ -->
            <div class="main object-non-visible animated object-visible fadeInUpSmall" data-animation-effect="fadeInUpSmall" data-effect-delay="100">
                <div class="form-block center-block p-30 light-gray-bg border-clear">
                    <h2 class="title"><?php echo $this->translate('Forgot your password')?></h2>
                    <?php
                        echo $this->flashMessenger()->renderCurrent('error', array('alert', 'alert-dismissible', 'alert-danger'));
                        echo $this->flashMessenger()->renderCurrent('success', array('alert', 'alert-dismissible', 'alert-success'));
                        $this->flashMessenger()->getPluginFlashMessenger()->clearCurrentMessagesFromNamespace('success');
                        $this->flashMessenger()->getPluginFlashMessenger()->clearCurrentMessagesFromNamespace('error');
                    ?>
                    <?php 
                        $form->prepare();
                        echo $this->form()->openTag($form);
                    ?>
                    <div class="form-group has-feedback">
                        <label for="inputUserName" class="col-sm-3 control-label">
                            <?php echo $this->formLabel($form->get('email')); ?>
                        </label>
                        <div class="col-sm-8">
                            <?php echo $this->formText($form->get('email')); ?> 
                            <?php echo $this->formErrorMessage($form->get('email')); ?>
                            <i class="fa fa-envelope form-control-feedback"></i>
                        </div>
                    </div>  
                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-8">
                            <button type="submit" class="btn btn-group btn-default btn-animated"><?php echo $this->translate('Send')?><i class="fa fa-check"></i></button>
                        </div>                        
                    </div> 
                    <?php                
						echo $this->formHidden($form->get('csrf'));					
                        echo $this->form()->closeTag();
                        unset($form);
                    ?>                    
                </div>
            </div>
            <!-- main end -->
        </div>
    </div>
</div>
<!-- main-container end -->
<?php
echo $this->headScript()->prependFile(Web\Module::getConfig('st_host') . ('/js/fblogin.js'));
echo $this->headScript()->prependFile('https://connect.facebook.net/en_US/all.js');
$facebook_app_id = \Web\Module::getConfig('facebook_app_id');
$this->headScript()->offsetSetScript(100, " 
    $(function() {    
        var facebook_app_id = '{$facebook_app_id}';
        $(function () {
            FB.init({
                appId: facebook_app_id,
                cookie: true,
                status: true,
                oauth: true,
                xfbml: true
            });
        });           
    });
");
?>	