<!-- main-container start -->
<!-- ================ -->
<div class="main-container dark-translucent-bg" style="background-image:url(&#39;/web/images/background-img-6.jpg&#39;);">
    <div class="container">
        <div class="row">
            <!-- main start -->
            <!-- ================ -->
            <div class="main object-non-visible animated object-visible fadeInUpSmall" data-animation-effect="fadeInUpSmall" data-effect-delay="100">
                
                <div class="form-block center-block p-30 light-gray-bg border-clear">
                    <h2 class="title"><?php echo $this->translate('Login')?></h2>
                    <?php
                        echo $this->flashMessenger()->renderCurrent('error', array('alert', 'alert-dismissible', 'alert-danger'));
                        echo $this->flashMessenger()->renderCurrent('success', array('alert', 'alert-dismissible', 'alert-success'));
                        $this->flashMessenger()->getPluginFlashMessenger()->clearCurrentMessagesFromNamespace('success');
                        $this->flashMessenger()->getPluginFlashMessenger()->clearCurrentMessagesFromNamespace('error');
                    ?>
                    <?php 
                        $form->prepare();
                        echo $this->form()->openTag($form);
                    ?>
                    <div class="form-group has-feedback">
                        <label for="inputUserName" class="col-sm-3 control-label">
                            <?php echo $this->formLabel($form->get('email')); ?>
                        </label>
                        <div class="col-sm-8">
                            <?php echo $this->formText($form->get('email')); ?>  
                            <?php echo $this->formErrorMessage($form->get('email')); ?>                                
                            <i class="fa fa-envelope form-control-feedback"></i>
                        </div>
                    </div>
                    <div class="form-group has-feedback">
                        <label for="inputPassword" class="col-sm-3 control-label">
                            <?php echo $this->formLabel($form->get('password')); ?>
                        </label>
                        <div class="col-sm-8">
                            <?php echo $this->formPassword($form->get('password')); ?>
                            <?php echo $this->formErrorMessage($form->get('password')); ?>
                            <i class="fa fa-lock form-control-feedback"></i>
                        </div>
                    </div>
                    <div class="form-group">                        
                        <div class="col-sm-offset-3 col-sm-8">
                            <div class="remember-me">
                                <div class="checkbox fl">
                                    <label>
                                        <?php echo $this->formInput($form->get('remember')); ?>                         
                                        <?php echo $this->translate('Remember me')?>
                                    </label>
                                </div>	
                                <div class="fr forgot-password">
                                    <a href="<?php echo $this->url('web/forgetpassword')?>"><?php echo $this->translate('Forgot your password')?>?</a>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-group btn-default btn-animated">
                                <?php echo $this->translate('Login')?>
                                <i class="fa fa-user"></i>
                            </button>
                        </div>
                        <div class="col-sm-offset-3 col-sm-8 mt8m">
                            <span class="text-center text-muted"><?php echo $this->translate('Or login with')?></span>
                            <ul class="social-links colored circle clearfix mt5 ml0">
                                <li class="facebook"><a id="fbLogin" target="_blank" href="http://www.facebook.com"><i class="fa fa-facebook"></i></a></li>                              
                                <li class="googleplus"><a href="<?php echo $this->url('web/glogin')?>"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>   
                    </div>  
                    <?php                       
                        echo $this->form()->closeTag();
                        unset($form);
                    ?>                    
                </div>
                <p class="text-center space-top"><?php echo $this->translate('Don\'t have an account yet?')?> <a href="<?php echo $this->url('web/signup')?>"><?php echo $this->translate('Sign Up')?></a> <?php echo $this->translate('now')?>.</p>
            </div>
            <!-- main end -->
        </div>
    </div>
</div>
<!-- main-container end -->
<?php
echo $this->headScript()->prependFile(Web\Module::getConfig('st_host') . ('/js/fblogin2.js'));
echo $this->headScript()->prependFile('https://connect.facebook.net/en_US/all.js');
$facebook_app_id = \Web\Module::getConfig('facebook_app_id');
$this->headScript()->offsetSetScript(100, " 
    $(function() {    
        var facebook_app_id = '{$facebook_app_id}';
        $(function () {
            FB.init({
                appId: facebook_app_id,
                cookie: true,
                status: true,
                oauth: true,
                xfbml: true
            });
        });           
    });
");
?>		