<!-- main-container start -->
<!-- ================ -->
<div class="main-container dark-translucent-bg" style="background-image:url(&#39;/web/images/background-img-6.jpg&#39;);">
    <div class="container">
        <div class="row">
            <!-- main start -->
            <!-- ================ -->
            <div class="main object-non-visible animated object-visible fadeInUpSmall" data-animation-effect="fadeInUpSmall" data-effect-delay="100">
                <div class="form-block center-block p-30 light-gray-bg border-clear">
                    <h2 class="title"><?php echo $this->translate('New password')?></h2>
                    <?php
                        echo $this->flashMessenger()->renderCurrent('error', array('alert', 'alert-dismissible', 'alert-danger'));
                        echo $this->flashMessenger()->renderCurrent('success', array('alert', 'alert-dismissible', 'alert-success'));
                        $this->flashMessenger()->getPluginFlashMessenger()->clearCurrentMessagesFromNamespace('success');
                        $this->flashMessenger()->getPluginFlashMessenger()->clearCurrentMessagesFromNamespace('error');
                    ?>
                    <?php 
                        $form->prepare();
                        echo $this->form()->openTag($form);
                    ?>
                    <div class="form-group">
						<div class="col-md-4 control-label"><?php echo $this->formLabel($form->get('password'));?></div>
						<div class="col-md-8">
							<?php echo $this->formPassword($form->get('password'));?>
							<?php echo $this->formErrorMessage($form->get('password')); ?>                                
						</div>
					</div>                            
					<div class="form-group">
						<div for="password_confirmation" class="col-md-4 control-label"><?php echo $this->formLabel($form->get('password_confirmation'));?></div>
						<div class="col-md-8">
							<?php echo $this->formPassword($form->get('password_confirmation'));?>
							<?php echo $this->formErrorMessage($form->get('password_confirmation')); ?>                                
						</div>
					</div> 
                    <div class="form-group">
                        <div class="col-sm-offset-4 col-sm-8">
                            <button type="submit" class="btn btn-group btn-default btn-animated"><?php echo $this->translate('Update')?><i class="fa fa-check"></i></button>
                        </div>                        
                    </div> 
                    <?php                
						echo $this->formHidden($form->get('csrf'));					
                        echo $this->form()->closeTag();
                        unset($form);
                    ?>                    
                </div>
            </div>
            <!-- main end -->
        </div>
    </div>
</div>