<!-- main-container start -->
<!-- ================ -->
<section class="main-container">

    <div class="container">
        <div class="row">

            <!-- main start -->
            <!-- ================ -->
            <div class="main col-md-12">

                <!-- page-title start -->
                <!-- ================ -->
              
                <!-- page-title end -->

                <div class="row">
                    <div class="col-md-4">
                        <!-- pills start -->
                        <!-- ================ -->
                        <!-- Nav tabs -->
                        <!--
                        <ul class="nav nav-pills" role="tablist">
                            <li class="active"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html#pill-1" role="tab" data-toggle="tab" title="images"><i class="fa fa-camera pr-5"></i> Photo</a></li>
                            <li><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html#pill-2" role="tab" data-toggle="tab" title="video"><i class="fa fa-video-camera pr-5"></i> Video</a></li>
                        </ul>
                        -->
                        <!-- Tab panes -->
                        <div class="tab-content clear-style">
                            <div class="tab-pane active" id="pill-1">
								<?php if (!empty($data['url_image'])) : ?>
                                <div class="owl-carousel content-slider-with-large-controls">
									<?php foreach ($data['images'] as $image): ?>
                                    <div class="overlay-container overlay-visible">
                                        <img src="<?php echo $image['url_image']; ?>" alt="">
                                        <a href="<?php echo $image['url_image']; ?>" class="popup-img overlay-link" title="image title"><i class="icon-plus-1"></i></a>
                                    </div>
									<?php endforeach ?>                                    
                                </div>
								<?php endif ?>
                            </div>
                            <div class="tab-pane" id="pill-2">
                                <div class="embed-responsive embed-responsive-16by9">
                                    <iframe class="embed-responsive-item" src="//player.vimeo.com/video/29198414?byline=0&amp;portrait=0"></iframe>
                                    <p><a href="http://vimeo.com/29198414">Introducing Vimeo Music Store</a> from <a href="http://vimeo.com/staff">Vimeo Staff</a> on <a href="https://vimeo.com">Vimeo</a>.</p>
                                </div>
                            </div>
                        </div>
                        <!-- pills end -->
                    </div>
                    <div class="col-md-8 pv-30">
                        <h2><?php echo $data['name'] ?></h2>                        
                        <?php
                            if (!empty($data['brand_id'])) {                                
                                echo "<p class=\"attribute brand\">";
                                echo "<span class=\"attribute-name\">" . $this->translate('Brand') . ":</span>";                                            
                                echo "<span class=\"attribute-value\"><a href=\"/products?brand_id={$data['brand_id']}\">{$data['brand']['name']}</a></span>";                                            
                                echo "</p>";                                
                            }
                        ?> 
                        <?php if (!empty($data['code'])): ?>
                        <p class="code">
                            <span class="attribute-name"><?php echo $this->translate('SKU') ?>:</span>
                            <span class="attribute-value"><?php echo $data['code']; ?></span>
                        </p>
                        <?php endif ?>
                        <?php if (!empty($data['model'])): ?>
                        <p class="code">
                            <span class="attribute-name"><?php echo $this->translate('Model') ?>:</span>
                            <span class="attribute-value"><?php echo $data['model']; ?></span>
                        </p>
                        <?php endif ?>                        
                        <?php if (!empty($data['warranty'])): ?>
                        <p class="warranty">
                            <span class="attribute-name"><?php echo $this->translate('Warranty') ?>:</span>
                            <span class="attribute-value"><?php echo $data['warranty']; ?></span>
                        </p>
                        <?php endif ?>
                        <?php if (!empty($data['weight'])): ?>
                        <p class="warranty">
                            <span class="attribute-name"><?php echo $this->translate('Weight (kg)') ?>:</span>
                            <span class="attribute-value"><?php echo $data['weight']; ?></span>
                        </p>
                        <?php endif ?>
                        <?php if (!empty($data['size'])): ?>
                        <p class="warranty">
                            <span class="attribute-name"><?php echo $this->translate('Size (depth x width x height cm)') ?>:</span>
                            <span class="attribute-value"><?php echo $data['size']; ?></span>
                        </p>
                        <?php endif ?>
                        <?php if (!empty($data['made_in'])): ?>
                        <p class="made-in">
                            <span class="attribute-name"><?php echo $this->translate('Made in') ?>:</span>
                            <span class="attribute-value"><?php echo $data['made_in']; ?></span>
                        </p>
                        <?php endif ?>
                        <?php
                            if (!empty($data['attributes'])) {
                                foreach ($data['attributes'] as $attribute) {
                                    if (!empty($attribute['options']['value_options']) 
                                        && !empty($attribute['value'])) {
                                        if (!is_array($attribute['value'])) {
                                            $attribute['value'] = array($attribute['value']);
                                        }
                                        $selectedValue = array();
                                        foreach ($attribute['options']['value_options'] as $valueId => $value) {
                                            if (in_array($valueId, $attribute['value'])) {
                                                $selectedValue[] = $value;
                                            }
                                        }
                                        echo "<p class=\"attribute\">";
                                        echo "<span class=\"attribute-name\">{$attribute['name']}:</span>";                                            
                                        echo "<span class=\"attribute-value\">" . implode(', ', $selectedValue) . "</span>";                                            
                                        echo "</p>";
                                    }
                                }
                            }
                        ?>   
                        
                        <p><?php echo nl2br($data['short']) ?></p>
                        <hr class="mb-10">
                        <!--
                        <div class="clearfix mb-20">
                            <span>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                            </span>
                            <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html#" class="wishlist"><i class="fa fa-heart-o pl-10 pr-5"></i>Wishlist</a>
                            <ul class="pl-20 pull-right social-links circle small clearfix margin-clear animated-effect-1">
                                <li class="twitter"><a target="_blank" href="http://www.twitter.com/"><i class="fa fa-twitter"></i></a></li>
                                <li class="googleplus"><a target="_blank" href="http://plus.google.com/"><i class="fa fa-google-plus"></i></a></li>
                                <li class="facebook"><a target="_blank" href="http://www.facebook.com/"><i class="fa fa-facebook"></i></a></li>
                            </ul>
                        </div>
                        -->
						<form method="post" id="detailForm" novalidate="novalidate" class="clearfix">
							<!--
                            <div class="row grid-space-10">                           
								<div class="col-md-4">
									<div class="form-group">
										<label>Quantity</label>
										<input name="quantity" type="text" class="form-control number" value="1">
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Color</label>
										<select class="form-control">
											<option>Red</option>
											<option>White</option>
											<option>Black</option>
											<option>Blue</option>
											<option>Orange</option>
										</select>
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Size</label>
										<select class="form-control">
											<option>5.3"</option>
											<option>5.7"</option>
										</select>
									</div>
								</div>
								<div class="col-md-12 text-right">

								</div>
								
							</div>
                            -->
							<div class="light-gray-bg p-20 bordered clearfix">
                            <span class="product price">
								<i class="icon-tag pr-10"></i>
								<?php 								
                                    if (!empty($data['price'])) {
                                        echo app_money_format($data['price']); 
                                    } else {
                                        echo $this->translate('Price contact');
                                    }                                    
                                ?>
							</span>
                            <div class="product elements-list pull-right clearfix">
                                <input 
									type="button" 
									value="<?php echo $this->translate('Add to cart') ?>" 
									data-url="<?php echo $this->url(
											'web/carts', 
											array(
												'action' => 'additem',
												'id' => $data['_id']
											))
									?>"
									data-callback="										
										loadCart(1);                                    
										showMessage('<?php echo $this->translate('Added to cart') ?>')
									"
									class="margin-clear btn btn-default ajax-submit">
                            </div>
                        </div>
						</form>
					</div>
                </div>
            </div>
            <!-- main end -->

        </div>
    </div>
</section>
<!-- main-container end -->

<!-- section start -->
<!-- ================ -->
<section class="pv-30 ">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs style-4" role="tablist">
                    <li class="active"><a href="#h2tab2" role="tab" data-toggle="tab"><i class="fa fa-files-o pr-5"></i><?php echo $this->translate('Detail Description') ?></a></li>
                    <li><a href="#h2tab3" role="tab" data-toggle="tab"><i class="fa fa-star pr-5"></i><?php echo $this->translate('Reviews') ?></a></li>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content padding-top-clear padding-bottom-clear">
                    <div class="tab-pane fade in active" id="h2tab2">                                              
						<?php echo $data['content']; ?>
                        <?php if (!empty($data['brand'])): ?>
                        <h4 class="space-top"><?php echo $this->translate('Brand information') ?></h4><hr>
                        <?php echo nl2br($data['brand']['short']) ?>
                        <?php endif ?>
                    </div>
                    <div class="tab-pane fade" id="h2tab3">
                        <!-- comments start -->
                        <div class="comments margin-clear space-top" id="review-list">
                            <!-- comment start -->
                            <?php
                            if (!empty($reviewList)) {
                                foreach ($reviewList as $review) {
                                    $review['content'] = nl2br($review['content']);
                                    $time = app_datetime_format($review['created']);
                                    $rating = '';
                                    for ($star = 1; $star <= 5; $star++) {
                                        if ($review['rating'] >= $star) {
                                            $rating .= "<i class=\"fa fa-star text-default\"></i>"; 
                                        } else {
                                            $rating .= "<i class=\"fa fa-star\"></i>";
                                        }
                                    }
                                    echo "<div class=\"comment clearfix\">
                                        <!--
                                        <div class=\"comment-avatar\">
                                            <img class=\"img-circle\" src=\"/web/images/avatar.jpg\" alt=\"avatar\">
                                        </div>
                                        -->
                                        <header>
                                            <h3>{$review['name']}</h3>
                                            <div class=\"comment-meta\"> 
                                                {$rating} | {$time}
                                            </div>
                                        </header>
                                        <div class=\"comment-content\">
                                            <div class=\"comment-body clearfix\">
                                                <p>{$review['content']}</p>
                                                <!--<a href=\"http://htmlcoder.me/preview/the_project/v.1.1/template/blog-post.html\" class=\"btn-sm-link link-dark pull-right\"><i class=\"fa fa-reply\"></i> Reply</a>-->
                                            </div>
                                        </div>
                                    </div>";
                                }
                            }
                            ?>                            
                            <!-- comment end -->
                        </div>
                        <!-- comments end -->

                        <!-- comments form start -->
                        <div class="comments-form">
                            <h2 class="title"><?php echo $this->translate('Add your Review') ?></h2>
                            <?php                
                                echo $this->htmlForm($reviewForm);                   
                            ?>                            
                        </div>
                        <!-- comments form end -->
                    </div>
                </div>
            </div>

            <!-- sidebar start -->
            <!-- ================ -->
            <aside class="col-md-4 col-lg-3 col-lg-offset-1">
                <div class="sidebar">
                    <div class="block clearfix">
                        <?php if (!empty($relatedProducts)) : ?>
                        <h3 class="title">Related Products</h3>
                        <div class="separator-2"></div>
                        <?php                         
                            $locales = \Application\Module::getConfig('general.locales');
                            $request = $this->requestHelper(); 
                            if (!empty($relatedProducts)) {
                                foreach ($relatedProducts as $product) {
                                    $product['url'] = $this->url(
                                        'web/products', 
                                        array(
                                            'action' => 'detail',
                                            'id' => $product['_id']
                                        )
                                    );
                                    $product['original_price'] = !empty($product['original_price']) ? app_money_format($product['original_price']) : '';
                                    $product['price'] = app_money_format($product['price']);
                                    $product['name'] = truncate($product['name'], 60);
                                    echo "<div class=\"media margin-clear\">
                                        <div class=\"media-left\">
                                            <div class=\"overlay-container\">
                                                <img class=\"media-object\" src=\"{$product['url_image']}\" alt=\"blog-thumb\">
                                                <a href=\"{$product['url']}\" class=\"overlay-link small\"><i class=\"fa fa-link\"></i></a>
                                            </div>
                                        </div>
                                        <div class=\"media-body\">
                                            <h6 class=\"media-heading\"><a href=\"{$product['url']}\">{$product['name']}</a></h6>
                                            <p class=\"price\">{$product['price']} <span class=\"original-price\">{$product['original_price']}</span></p>
                                        </div>
                                        <hr>
                                    </div>";                                    
                                }
                            }
                        ?>
                        
                        <?php endif ?>                       
                        
                    </div>
                </div>
            </aside>
            <!-- sidebar end -->

        </div>
    </div>
</section>
<!-- section end -->

