<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary collapsed-box">
            <div class="box-header" data-toggle="" title="" data-original-title="Header tooltip">
            <h3 class="box-title"><?php echo $this->translate('Search') ?></h3>
            <div class="box-tools pull-right">
                <button class="btn btn-primary btn-xs search-collapse" data-widget="collapse"><i class="fa fa-plus"></i></button>
            </div>
            </div>
            <div class="box-body search-body" style="display:none;">
                <?php
                    echo $this->htmlForm($searchForm);
                ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <?php
                echo $this->htmlListForm($listForm);
            ?>
        </div>
    </div>
</div>