<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle()
                        ->setSeparator(' - ')
                        ->setAutoEscape(false)
        ?>
        
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath('/be/custom.css')) 
            ->prependStylesheet($this->basePath('/be/plugins/notification/css/jquery_notification.css')) 
            ->prependStylesheet($this->basePath('/be/plugins/datetimepicker/bootstrap-datetimepicker.css')) 
            ->prependStylesheet($this->basePath('/be/plugins/lightbox/jquery.lightbox-0.5.css')) 
            ->prependStylesheet($this->basePath('/be/plugins/daterangepicker/daterangepicker-bs3.css')) 
            ->prependStylesheet($this->basePath('/be/plugins/datepicker/datepicker3.css')) 
            ->prependStylesheet($this->basePath('/be/plugins/timepicker/bootstrap-timepicker.css')) 
            ->prependStylesheet($this->basePath('/be/plugins/jvectormap/jquery-jvectormap-1.2.2.css')) 
            ->prependStylesheet($this->basePath('/be/plugins/morris/morris.css')) 
            ->prependStylesheet($this->basePath('/be/plugins/iCheck/flat/blue.css')) 
            ->prependStylesheet($this->basePath('/be/plugins/toggle/bootstrap-toggle.css')) 
            ->prependStylesheet($this->basePath('/be/plugins/datatables/dataTables.bootstrap.css')) 
            ->prependStylesheet($this->basePath('/be/plugins/select2/select2.css'))              
            ->prependStylesheet($this->basePath('/be/dist/css/skins/_all-skins.min.css'))     
            ->prependStylesheet($this->basePath('/be/dist/css/AdminLTE.min.css'))
            ->prependStylesheet('//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css') 
            ->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css')
            ->prependStylesheet('//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css')
            ->prependStylesheet($this->basePath('/be/bootstrap/css/bootstrap.min.css'))
        ;?>
    </head>    
    <body class="skin-red sidebar-mini fixed" id="<?php echo $controller . '_' . $action; ?>">
        <div class="wrapper">
            <?php echo $this->partial('admin/header'); ?>
            <?php echo $this->partial('admin/sidebar'); ?> 
            <div class="content-wrapper" style="min-height: 916px;">
                <!-- Content Header (Page header) -->
                <section class="content-header">                                     
                    <?php 
                        echo $this->navigation('navigation')                            
                            ->breadcrumbs()
                            ->setMinDepth(0)
                            ->setPartial('admin/breadcrumb');                        
                    ?> 
                </section>

                <!-- Main content -->
                <section class="content">
                    <?php                
                        echo $this->flashMessenger()->renderCurrent('error', array('alert', 'alert-dismissible', 'alert-danger'));
                        echo $this->flashMessenger()->renderCurrent('success', array('alert', 'alert-dismissible', 'alert-success'));
                        $this->flashMessenger()->getPluginFlashMessenger()->clearCurrentMessagesFromNamespace('success');
                        $this->flashMessenger()->getPluginFlashMessenger()->clearCurrentMessagesFromNamespace('error');
                    ?>
                    <?php                       
                        echo $this->content; 
                    ?>                    
                    <div id="dialog-modal" class="modal fade" role="dialog" aria-labelledby="largeModal" aria-hidden="true">
                        <div class="modal-dialog modal-lg">
                            <div class="modal-content">            
                                
                            </div>
                        </div>
                    </div>
                </section><!-- /.content -->
            </div>
            <?php echo $this->partial('admin/footer'); ?>     
        </div>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('/be/main.js')) 
            ->prependFile($this->basePath('/be/plugins/notification/js/jquery_notification_v.1.js')) 
            ->prependFile($this->basePath('/be/plugins/lightbox/jquery.lightbox-0.5.js')) 
            ->prependFile($this->basePath('/be/plugins/iCheck/icheck.min.js'))
            ->prependFile($this->basePath('/be/dist/js/demo.js'))    
            //->prependFile($this->basePath('/be/dist/js/pages/dashboard.js'))
            ->prependFile($this->basePath('/be/dist/js/app.min.js'))
            ->prependFile($this->basePath('/be/plugins/fastclick/fastclick.min.js'))
            ->prependFile($this->basePath('/be/plugins/slimScroll/jquery.slimscroll.min.js'))
            ->prependFile($this->basePath('/be/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'))
            ->prependFile($this->basePath('/be/plugins/datetimepicker/bootstrap-datetimepicker.min.js'))
                ->prependFile($this->basePath('/be/plugins/datetimepicker/moment-with-locales.js'))
            ->prependFile($this->basePath('/be/plugins/datetimepicker/moment.min.js'))            
            ->prependFile($this->basePath('/be/plugins/daterangepicker/daterangepicker.js'))    
            ->prependFile($this->basePath('/be/plugins/datepicker/bootstrap-datepicker.js'))    
            ->prependFile($this->basePath('/be/plugins/timepicker/bootstrap-timepicker.js'))            
            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js')
            ->prependFile($this->basePath('/be/plugins/knob/jquery.knob.js'))
            ->prependFile($this->basePath('/be/plugins/jvectormap/jquery-jvectormap-world-mill-en.js'))   
            ->prependFile($this->basePath('/be/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'))
            ->prependFile($this->basePath('/be/plugins/sparkline/jquery.sparkline.min.js'))
            ->prependFile($this->basePath('/be/plugins/toggle/bootstrap-toggle.js'))
            ->prependFile($this->basePath('/be/plugins/select2/select2.js'))
            ->prependFile($this->basePath('/be/plugins/autoNumeric/autoNumeric.js'))
            //->prependFile($this->basePath('/be/plugins/morris/morris.min.js'))
            ->prependFile($this->basePath('/be/bootstrap/js/bootstrap.min.js'))
            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js')    
            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js')    
            ->prependFile('//code.jquery.com/ui/1.11.4/jquery-ui.min.js')    
            ->prependFile($this->basePath('/be/plugins/jQuery/jQuery-2.1.4.min.js'))            
        ; ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>