<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle()
                        ->setSeparator(' - ')
                        ->setAutoEscape(false)
        ?>
        
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath('/be/custom.css'))     
            ->prependStylesheet($this->basePath('/be/plugins/iCheck/flat/blue.css')) 
            ->prependStylesheet($this->basePath('/be/dist/css/skins/_all-skins.min.css'))     
            ->prependStylesheet($this->basePath('/be/dist/css/AdminLTE.min.css')) 
            ->prependStylesheet('//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css') 
            ->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css')
            ->prependStylesheet($this->basePath('/be/bootstrap/css/bootstrap.min.css'))
        ;?>       
    </head>    
    <body class="hold-transition login-page">
        <?php                
            echo $this->flashMessenger()->renderCurrent('error', array('alert', 'alert-dismissible', 'alert-danger'));
            echo $this->flashMessenger()->renderCurrent('success', array('alert', 'alert-dismissible', 'alert-success'));
            $this->flashMessenger()->getPluginFlashMessenger()->clearCurrentMessagesFromNamespace('success');
            $this->flashMessenger()->getPluginFlashMessenger()->clearCurrentMessagesFromNamespace('error');
        ?>
        <?php                      
            echo $this->content; 
        ?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('/be/main.js')) 
            ->prependFile($this->basePath('/be/plugins/iCheck/icheck.min.js'))            
            ->prependFile($this->basePath('/be/bootstrap/js/bootstrap.min.js'))
            ->prependFile($this->basePath('/be/plugins/jQuery/jQuery-2.1.4.min.js'))            
        ; ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>