<?php
$cartItems = Application\Lib\Cart::get();
$totalQuantity = 0;
$totalMoney = 0;
if (!empty($cartItems)) {    
    foreach ($cartItems as $item) {
        $totalQuantity += $item['quantity'];
        $totalMoney += $item['quantity'] * $item['price'];
    }
}
$checkoutInfo = Application\Lib\Session::get('checkout_step1');
?>
<!-- main-container start -->
<!-- ================ -->
<section class="main-container">

    <div class="container">
        <div class="row">

            <!-- main start -->
            <!-- ================ -->
            <div class="main col-md-12">

                <!-- page-title start -->
                <!-- ================ -->
                <h1 class="page-title"><?php echo $this->translate('Checkout')?></h1>
                <div class="separator-2"></div>
                <!-- page-title end -->
                
                
                <table class="table cart">
                    <thead>
                        <tr>
                            <th><strong><?php echo $this->translate('Product name')?></strong></th>
                            <th><strong><?php echo $this->translate('Price')?></strong></th>
                            <th><strong><?php echo $this->translate('Quantity')?></strong></th>
                            <th class="amount"><strong><?php echo $this->translate('Total')?></strong></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($cartItems as $item) : ?>
                        <tr>
                            <td class="product">
                                <a href="<?php echo $this->url('web/products', array('name' => name_2_url($item['name'])))?>">
                                    <?php echo $item['custom_name']?>
                                </a> 
                            </td>
                            <td class="price"><?php echo money_format($item['price'])?></td>
                            <td class="quantity">
                                <div class="form-group">
                                    <input type="text" class="form-control" value="<?php echo $item['quantity']?>" disabled="">
                                </div>											
                            </td>
                            <td class="amount"><?php echo money_format($item['quantity'] * $item['price'])?></td>
                        </tr>
                        <?php endforeach ?>                        
                        <tr>
                            <td class="total-quantity" colspan="3"><?php echo $this->translate('Total Items')?>: <?php echo money_format($totalQuantity)?></td>
                            <td class="total-amount"><?php echo money_format($totalMoney)?></td>
                        </tr>
                    </tbody>
                </table>
                
                <div class="space-bottom"></div> 
                
                <?php if (!empty($registerAddressForm)): ?>
                <fieldset>
                    <legend><strong><?php echo $this->translate('Devivery information')?></strong></legend>
                    <?php 
                        $registerAddressForm->prepare();
                        echo $this->form()->openTag($registerAddressForm);                 
                    ?>
                    <div class="row">
                        <!--
                        <div class="col-lg-3">
                            <h3 class="title"><?php echo $this->translate('Personal Info')?></h3>
                        </div>
                        -->
                        <div class="col-lg-10 col-lg-offset-1">
                            <div class="form-group">
                                <label for="name" class="col-md-3 control-label"><?php echo $this->formLabel($registerAddressForm->get('name'));?></label>
                                <div class="col-md-9">
                                    <?php echo $this->formText($registerAddressForm->get('name'));?>
                                    <?php echo $this->formErrorMessage($registerAddressForm->get('name')); ?>                                
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="mobile" class="col-md-3 control-label"><?php echo $this->formLabel($registerAddressForm->get('mobile'));?></label>
                                <div class="col-md-9">
                                    <?php echo $this->formText($registerAddressForm->get('mobile'));?>
                                    <?php echo $this->formErrorMessage($registerAddressForm->get('mobile')); ?>                                
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="email" class="col-md-3 control-label"><?php echo $this->formLabel($registerAddressForm->get('email'));?></label>
                                <div class="col-md-9">
                                    <?php echo $this->formText($registerAddressForm->get('email'));?>
                                    <?php echo $this->formErrorMessage($registerAddressForm->get('email')); ?>                                
                                </div>
                            </div>
                            <div class="form-group<?php echo empty($user['addresses']) ? ' hide' : ''?>">
                                <label for="address_id" class="col-md-3 control-label"><?php echo $this->formLabel($registerAddressForm->get('address_id'));?></label>
                                <div class="col-md-9">
                                    <?php echo $this->formSelect($registerAddressForm->get('address_id'));?>
                                    <?php echo $this->formErrorMessage($registerAddressForm->get('address_id')); ?>                                
                                </div>
                            </div>
                        </div>
                    </div>   
                    
                    <div class="row hide" id="new-address">
                        <!--
                        <div class="col-lg-3">
                            <h3 class="title"><?php echo $this->translate('Delivery address')?></h3>
                        </div>
                        -->
                        <div class="col-lg-10 col-lg-offset-1">                            
                            <div class="form-group hide">
                                <label for="country_code" class="col-md-3 control-label"><?php echo $this->formLabel($registerAddressForm->get('country_code'));?></label>
                                <div class="col-md-9">
                                    <?php echo $this->formSelect($registerAddressForm->get('country_code'));?>
                                    <?php echo $this->formErrorMessage($registerAddressForm->get('country_code')); ?>                                
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="state_code" class="col-md-3 control-label"><?php echo $this->formLabel($registerAddressForm->get('state_code'));?></label>
                                <div class="col-md-9">
                                    <?php echo $this->formSelect($registerAddressForm->get('state_code'));?>
                                    <?php echo $this->formErrorMessage($registerAddressForm->get('state_code')); ?>                                
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="city_code" class="col-md-3 control-label"><?php echo $this->formLabel($registerAddressForm->get('city_code'));?></label>
                                <div class="col-md-9">
                                    <?php echo $this->formSelect($registerAddressForm->get('city_code'));?>
                                    <?php echo $this->formErrorMessage($registerAddressForm->get('city_code')); ?>                                
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="street" class="col-md-3 control-label"><?php echo $this->formLabel($registerAddressForm->get('street'));?></label>
                                <div class="col-md-9">
                                    <?php echo $this->formText($registerAddressForm->get('street'));?>
                                    <?php echo $this->formErrorMessage($registerAddressForm->get('street')); ?>                                
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="address_name" class="col-md-3 control-label"><?php echo $this->formLabel($registerAddressForm->get('address_name'));?></label>
                                <div class="col-md-9">
                                    <?php echo $this->formSelect($registerAddressForm->get('address_name'));?>
                                    <?php echo $this->formErrorMessage($registerAddressForm->get('address_name')); ?>                                
                                </div>
                            </div>                            
                        </div>
                    </div> 
                    <?php                       
                        echo $this->form()->closeTag();
                        unset($registerAddressForm);
                    ?>
                </fieldset>                           
                <?php endif ?>                
                
                <?php if (!empty($registerForm)): ?>
                <?php 
                    $registerForm->prepare();
                    echo $this->form()->openTag($registerForm);                        
                ?>
                <fieldset>
                    <legend><strong><?php echo $this->translate('Signup Account')?></strong></legend>                    
                    <div class="row">                        
                        <div class="col-lg-10 col-lg-offset-1">                            
                            <div class="form-group">
                                <label for="email" class="col-md-3 control-label"><?php echo $this->formLabel($registerForm->get('email'));?></label>
                                <div class="col-md-9">
                                    <?php echo $this->formText($registerForm->get('email'));?>
                                    <?php echo $this->formErrorMessage($registerForm->get('email')); ?>                                
                                </div>
                            </div>                            
                            <div class="form-group">
                                <label for="password" class="col-md-3 control-label"><?php echo $this->formLabel($registerForm->get('password'));?></label>
                                <div class="col-md-9">
                                    <?php echo $this->formPassword($registerForm->get('password'));?>
                                    <?php echo $this->formErrorMessage($registerForm->get('password')); ?>                                
                                </div>
                            </div>                            
                            <div class="form-group">
                                <label for="password_confirmation" class="col-md-3 control-label"><?php echo $this->formLabel($registerForm->get('password_confirmation'));?></label>
                                <div class="col-md-9">
                                    <?php echo $this->formPassword($registerForm->get('password_confirmation'));?>
                                    <?php echo $this->formErrorMessage($registerForm->get('password_confirmation')); ?>                                
                                </div>
                            </div>
                            <div class="col-sm-offset-3 col-sm-8 mt8m">
                                <a itemprop="url" href="<?php echo $this->url('web/login')?>" class="btn btn-default btn-sm">
                                    <i class="fa fa-lock pr-10"></i> 
                                    <span itemprop="name"><?php echo $this->translate('Login with registed account')?></span>
                                </a>
                            </div>
                            <div class="col-sm-offset-3 col-sm-8 mt8m"> 
                                <span class="text-center text-muted"><?php echo $this->translate('Or login with')?></span>
                                <ul class="social-links colored circle clearfix mt5 ml0">
                                    <li class="facebook"><a id="fbLogin" target="_blank" href="http://www.facebook.com"><i class="fa fa-facebook"></i></a></li>                              
                                    <li class="googleplus"><a target="_blank" href="http://plus.google.com"><i class="fa fa-google-plus"></i></a></li>
                                </ul>
                            </div>
                            <?php
                            echo $this->headScript()->prependFile($this->basePath('/web/js/fblogin.js'));
                            echo $this->headScript()->prependFile('https://connect.facebook.net/en_US/all.js');
                            $facebook_app_id = \Web\Module::getConfig('facebook_app_id');
                            $this->headScript()->offsetSetScript(101, " 
                                $(function() {    
                                    var facebook_app_id = '{$facebook_app_id}';
                                    $(function () {
                                        FB.init({
                                            appId: facebook_app_id,
                                            cookie: true,
                                            status: true,
                                            oauth: true,
                                            xfbml: true
                                        });
                                    });           
                                });
                            ");
                            ?>
                        </div>                            
                    </div>                            
                </fieldset>   
                 
                <div class="space-bottom"></div> 
                
                <fieldset>
                    <legend><strong><?php echo $this->translate('Devivery information')?></strong></legend>                    
                    <div class="row">
                        <div class="col-lg-10 col-lg-offset-1"> 
                            <div class="form-group">
                                <label for="name" class="col-md-3 control-label"><?php echo $this->formLabel($registerForm->get('name'));?></label>
                                <div class="col-md-9">
                                    <?php echo $this->formText($registerForm->get('name'));?>
                                    <?php echo $this->formErrorMessage($registerForm->get('name')); ?>                                
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="mobile" class="col-md-3 control-label"><?php echo $this->formLabel($registerForm->get('mobile'));?></label>
                                <div class="col-md-9">
                                    <?php echo $this->formText($registerForm->get('mobile'));?>
                                    <?php echo $this->formErrorMessage($registerForm->get('mobile')); ?>                                
                                </div>
                            </div>
                            <div class="form-group hide">
                                <label for="country_code" class="col-md-3 control-label"><?php echo $this->formLabel($registerForm->get('country_code'));?></label>
                                <div class="col-md-9">
                                    <?php echo $this->formSelect($registerForm->get('country_code'));?>
                                    <?php echo $this->formErrorMessage($registerForm->get('country_code')); ?>                                
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="state_code" class="col-md-3 control-label"><?php echo $this->formLabel($registerForm->get('state_code'));?></label>
                                <div class="col-md-9">
                                    <?php echo $this->formSelect($registerForm->get('state_code'));?>
                                    <?php echo $this->formErrorMessage($registerForm->get('state_code')); ?>                                
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="city_code" class="col-md-3 control-label"><?php echo $this->formLabel($registerForm->get('city_code'));?></label>
                                <div class="col-md-9">
                                    <?php echo $this->formSelect($registerForm->get('city_code'));?>
                                    <?php echo $this->formErrorMessage($registerForm->get('city_code')); ?>                                
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="street" class="col-md-3 control-label"><?php echo $this->formLabel($registerForm->get('street'));?></label>
                                <div class="col-md-9">
                                    <?php echo $this->formText($registerForm->get('street'));?>
                                    <?php echo $this->formErrorMessage($registerForm->get('street')); ?>                                
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="address_name" class="col-md-3 control-label"><?php echo $this->formLabel($registerForm->get('address_name'));?></label>
                                <div class="col-md-9">
                                    <?php echo $this->formSelect($registerForm->get('address_name'));?>
                                    <?php echo $this->formErrorMessage($registerForm->get('address_name')); ?>                                
                                </div>
                            </div>
                        </div>
                    </div>                            
                </fieldset> 
                <?php                       
                    echo $this->form()->closeTag();
                    unset($registerForm);
                ?>
                <?php endif ?>
                
                <div class="space-bottom"></div> 
               
                <fieldset>
                    <legend><strong><?php echo $this->translate('Payment')?></strong></legend>                    
                    <div class="row">
                        <span><input id="payment" name="payment" type="radio" checked style="width:20px; float:left;"/></span>                                
                        <span><?php echo $this->translate('COD')?></span>
                    </div>
                </div>
            
                <div class="text-right">	
                    <a href="/" class="btn btn-group btn-default"><i class="icon-left-open-big"></i><?php echo $this->translate('Continue shopping!')?></a>
                    <a href="<?php echo $this->url('web/carts', array('action' => 'view'))?>" class="btn btn-group btn-default"><i class="icon-left-open-big"></i> <?php echo $this->translate('Back to cart')?></a>
                    <a id="checkout-next" href="<?php echo $this->url('web/checkout', array('action' => 'review'))?>" class="btn btn-group btn-default"><?php echo !empty($AppUI) ? $this->translate('Next step') : $this->translate('Signup Account and Go next step')?> <i class="icon-right-open-big"></i></a>
                </div>

            </div>
            <!-- main end -->

        </div>
    </div>
</section>
<!-- main-container end -->
<?php
$this->headScript()->offsetSetScript(100, " 
    $(function() {
        var address_id = $('#address_id').val(); 
        if (address_id == '') {
            $('#new-address').removeClass('hide');
        }
    });
");
?>	