<!-- banner start -->
<!-- ================ -->
<div class="banner clearfix">

	<!-- slideshow start -->
	<!-- ================ -->
	<div class="slideshow">
		
		<!-- slider revolution start -->
		<!-- ================ -->
		<div class="slider-banner-container">
			<div class="slider-banner-fullwidth-big-height">
				<ul class="slides">
					<!-- slide 1 start -->
					<!-- ================ -->
					<li data-transition="random" data-slotamount="7" data-masterspeed="500" data-saveperformance="on" data-title="Get 50% Sales">
					
					<!-- main image -->
					<img src="/web/images/shop-slide-1.jpg" alt="slidebg1" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover">
					
					<!-- Transparent Background -->
					<div class="tp-caption dark-translucent-bg"
						data-x="center"
						data-y="bottom"
						data-speed="600"
						data-start="0">
					</div>

					<!-- LAYER NR. 1 -->
					<div class="tp-caption sfb fadeout large_white"
						data-x="left"
						data-y="180"
						data-speed="500"
						data-start="1000"
						data-easing="easeOutQuad">Get <span class="text-default">50%</span> OFF<br> Next Generation Template
					</div>	

					<!-- LAYER NR. 2 -->
					<div class="tp-caption sfb fadeout large_white tp-resizeme hidden-xs"
						data-x="left"
						data-y="300"
						data-speed="500"
						data-start="1300"
						data-easing="easeOutQuad"><div class="separator-2 light"></div>
					</div>	

					<!-- LAYER NR. 3 -->
					<div class="tp-caption sfb fadeout medium_white hidden-xs"
						data-x="left"
						data-y="320"
						data-speed="500"
						data-start="1300"
						data-easing="easeOutQuad"
						data-endspeed="600">Lorem ipsum dolor sit amet, consectetur adipisicing elit. <br> Nesciunt, maiores, aliquid. Repellat eum numquam aliquid culpa offici, <br> tenetur fugiat dolorum sapiente eligendi...
					</div>

					<!-- LAYER NR. 4 -->
					<div class="tp-caption sfb fadeout small_white text-center"
						data-x="left"
						data-y="430"
						data-speed="500"
						data-start="1600"
						data-easing="easeOutQuad"
						data-endspeed="600"><a href="#" class="btn btn-default btn-animated">Learn More <i class="fa fa-arrow-right"></i></a>
					</div>

					</li>
					<!-- slide 1 end -->

					<!-- slide 2 start -->
					<!-- ================ -->
					<li data-transition="random" data-slotamount="7" data-masterspeed="500" data-saveperformance="on" data-title="New Arrivals">
					
					<!-- main image -->
					<img src="/web/images/shop-slide-2.jpg" alt="slidebg1" data-bgposition="center top"  data-bgrepeat="no-repeat" data-bgfit="cover">
					
					<!-- Transparent Background -->
					<div class="tp-caption dark-translucent-bg"
						data-x="center"
						data-y="bottom"
						data-speed="600"
						data-start="0">
					</div>

					<!-- LAYER NR. 1 -->
					<div class="tp-caption sfb fadeout text-right large_white"
						data-x="right"
						data-y="180"
						data-speed="500"
						data-start="1000"
						data-easing="easeOutQuad"><span class="text-default">New</span> Arrivals<br> Unlimited Variations and Layouts
					</div>	

					<!-- LAYER NR. 2 -->
					<div class="tp-caption sfb fadeout large_white tp-resizeme hidden-xs"
						data-x="right"
						data-y="300"
						data-speed="500"
						data-start="1300"
						data-easing="easeOutQuad"><div class="separator-3 light"></div>
					</div>	

					<!-- LAYER NR. 3 -->
					<div class="tp-caption sfb fadeout medium_white text-right hidden-xs"
						data-x="right"
						data-y="320"
						data-speed="500"
						data-start="1300"
						data-easing="easeOutQuad"
						data-endspeed="600">Lorem ipsum dolor sit amet, consectetur adipisicing elit. <br> Nesciunt, maiores, aliquid. Repellat eum numquam aliquid culpa offici, <br> tenetur fugiat dolorum sapiente eligendi...
					</div>

					<!-- LAYER NR. 4 -->
					<div class="tp-caption sfb fadeout small_white text-right text-center"
						data-x="right"
						data-y="430"
						data-speed="500"
						data-start="1600"
						data-easing="easeOutQuad"
						data-endspeed="600"><a href="#" class="btn btn-default btn-animated">Check Now <i class="fa fa-arrow-right"></i></a>
					</div>
					</li>
					<!-- slide 2 end -->
				</ul>
				<div class="tp-bannertimer"></div>
			</div>
		</div>
		<!-- slider revolution end -->

	</div>
	<!-- slideshow end -->

</div>
<!-- banner end -->

<div id="page-start"></div>

<!-- section start -->
<!-- ================ -->
<section class="section light-gray-bg clearfix">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<!-- pills start -->
				<!-- ================ -->
				<!-- Nav tabs -->
				<ul class="nav nav-pills" role="tablist">
					<li class="active"><a href="/index-shop.html#pill-1" role="tab" data-toggle="tab" title="Latest Arrivals"><i class="icon-star"></i> Latest Arrivals</a></li>
					<li><a href="/index-shop.html#pill-2" role="tab" data-toggle="tab" title="Featured"><i class="icon-heart"></i> Featured</a></li>
					<li><a href="/index-shop.html#pill-3" role="tab" data-toggle="tab" title="Top Sellers"><i class=" icon-up-1"></i> Top Sellers</a></li>
				</ul>
				<!-- Tab panes -->
				<div class="tab-content clear-style">
					<div class="tab-pane active" id="pill-1">
						<div class="row masonry-grid-fitrows grid-space-10" style="position: relative; height: 1082.02px;">
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 0px; top: 0px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-1.jpg" alt="">
										<a class="overlay-link popup-img-single" href="/web/images/product-1.jpg"><i class="fa fa-search-plus"></i></a>
										<span class="badge">30% OFF</span>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Suscipit consequatur velit</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price"><del>$100.00</del> $70.00</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 288px; top: 0px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-2.jpg" alt="">
										<span class="badge">25% OFF</span>
										<a class="overlay-link popup-img-single" href="/web/images/product-2.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Consectetur adipisicing elit</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price"><del>$199.00</del> $150.00</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 576px; top: 0px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-3.jpg" alt="">
										<span class="badge">33% OFF</span>
										<a class="overlay-link popup-img-single" href="/web/images/product-3.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Quas inventore modi</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price"><del>$9.99</del> $6.66</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 864px; top: 0px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-4.jpg" alt="">
										<span class="badge">20% OFF</span>
										<a class="overlay-link popup-img-single" href="/web/images/product-4.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Lorem ipsum dolor sit</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price"><del>$86.25</del> $69.00</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 0px; top: 537px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-5.jpg" alt="">
										<span class="badge">30% OFF</span>
										<a class="overlay-link popup-img-single" href="/web/images/product-5.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Velit Suscipit consequatur</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price"><del>$12.00</del> $8.40</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 288px; top: 537px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-6.jpg" alt="">
										<span class="badge">50% OFF</span>
										<a class="overlay-link popup-img-single" href="/web/images/product-6.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Reprehenderit a reiciendis</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price"><del>$158.00</del> $129.00</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 576px; top: 537px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-7.jpg" alt="">
										<span class="badge">40% OFF</span>
										<a class="overlay-link popup-img-single" href="/web/images/product-7.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Cumque sequi repellat</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price"><del>$49.99</del> $29.99</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 864px; top: 537px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-8.jpg" alt="">
										<a class="overlay-link popup-img-single" href="/web/images/product-8.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Soluta suscipit dolore</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price">$11.99</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="tab-pane" id="pill-2">
						<div class="row masonry-grid-fitrows grid-space-10" style="position: relative; height: 0px;">
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 0px; top: 0px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-2.jpg" alt="">
										<a class="overlay-link popup-img-single" href="/web/images/product-2.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Consectetur adipisicing elit</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price">$199.00</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 0px; top: 0px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-1.jpg" alt="">
										<span class="badge">New</span>
										<a class="overlay-link popup-img-single" href="/web/images/product-1.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Suscipit consequatur velit</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price">$70.00</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 0px; top: 0px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-4.jpg" alt="">
										<span class="badge">30% OFF</span>
										<a class="overlay-link popup-img-single" href="/web/images/product-4.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Lorem ipsum dolor sit</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price"><del>$99.00</del> $69.00</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 0px; top: 0px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-3.jpg" alt="">
										<a class="overlay-link popup-img-single" href="/web/images/product-3.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Quas inventore modi</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price">$9.99</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 0px; top: 0px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-6.jpg" alt="">
										<span class="badge">20% OFF</span>
										<a class="overlay-link popup-img-single" href="/web/images/product-6.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Reprehenderit a reiciendis</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price"><del>$161.25</del> $129.00</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 0px; top: 0px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-5.jpg" alt="">
										<a class="overlay-link popup-img-single" href="/web/images/product-5.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Velit Suscipit consequatur</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price">$12.99</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 0px; top: 0px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-8.jpg" alt="">
										<span class="badge">Offer</span>
										<a class="overlay-link popup-img-single" href="/web/images/product-8.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Soluta suscipit dolore</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price">$11.99</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 0px; top: 0px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-7.jpg" alt="">
										<a class="overlay-link popup-img-single" href="/web/images/product-7.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Cumque sequi repellat</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price">$29.99</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="tab-pane" id="pill-3">
						<div class="row masonry-grid-fitrows grid-space-10" style="position: relative; height: 0px;">
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 0px; top: 0px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-4.jpg" alt="">
										<span class="badge">30% OFF</span>
										<a class="overlay-link popup-img-single" href="/web/images/product-4.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Lorem ipsum dolor sit</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price"><del>$99.00</del> $69.00</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 0px; top: 0px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-3.jpg" alt="">
										<span class="badge">New</span>
										<a class="overlay-link popup-img-single" href="/web/images/product-3.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Quas inventore modi</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price">$9.99</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 0px; top: 0px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-2.jpg" alt="">
										<span class="badge">30% OFF</span>
										<a class="overlay-link popup-img-single" href="/web/images/product-2.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Consectetur adipisicing elit</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price"><del>$199.00</del> $140.00</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 0px; top: 0px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-1.jpg" alt="">
										<span class="badge">Last 3 Pieces</span>
										<a class="overlay-link popup-img-single" href="/web/images/product-1.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Suscipit consequatur velit</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price">$70.00</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 0px; top: 0px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-8.jpg" alt="">
										<a class="overlay-link popup-img-single" href="/web/images/product-8.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Soluta suscipit dolore</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price">$11.99</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 0px; top: 0px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-7.jpg" alt="">
										<a class="overlay-link popup-img-single" href="/web/images/product-7.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Cumque sequi repellat</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price">$29.99</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 0px; top: 0px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-6.jpg" alt="">
										<a class="overlay-link popup-img-single" href="/web/images/product-6.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Reprehenderit a reiciendis</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price">$129.00</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 masonry-grid-item" style="position: absolute; left: 0px; top: 0px;">
								<div class="listing-item white-bg bordered mb-20">
									<div class="overlay-container">
										<img src="/web/images/product-5.jpg" alt="">
										<a class="overlay-link popup-img-single" href="/web/images/product-5.jpg"><i class="fa fa-search-plus"></i></a>
										<div class="overlay-to-top links">
											<span class="small">
												<a href="/index-shop.html#" class="btn-sm-link"><i class="fa fa-heart-o pr-10"></i>Add to Wishlist</a>
												<a href="/index-shop.html#" class="btn-sm-link"><i class="icon-link pr-5"></i>View Details</a>
											</span>
										</div>
									</div>
									<div class="body">
										<h3><a href="/shop-product.html">Velit Suscipit consequatur</a></h3>
										<p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</p>
										<div class="elements-list clearfix">
											<span class="price">$12.99</span>
											<a href="/index-shop.html#" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">Add To Cart<i class="fa fa-shopping-cart"></i></a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- pills end -->
			</div>
		</div>
	</div>
</section>
<!-- section end -->

<!-- section start -->
<!-- ================ -->
<section class="section dark-translucent-bg background-img-2" style="background-position: 50% 52%;">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="call-to-action text-center">
					<div class="row">
						<div class="col-sm-8">
							<h1 class="title">Don't Miss Out Our Offers</h1>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem quasi explicabo consequatur consectetur, a atque voluptate officiis eligendi nostrum.</p>
						</div>
						<div class="col-sm-4">
							<br>
							<p><a href="/index-shop.html#" class="btn btn-lg btn-default btn-animated">Learn More<i class="fa fa-arrow-right pl-20"></i></a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- section end -->

<!-- section start -->
<!-- ================ -->
<section class="section clearfix">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h3 class="logo-font">Brands</h3>
				<div class="separator-2"></div>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. At distinctio quia, et natus nulla cumque consequuntur, <br> sed, quam aliquam excepturi ea necessitatibus facilis, vero illum dignissimos eligendi quasi consectetur possimus.</p>
				<div class="clients-container">
					<div class="clients">
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="100">
							<a href="/index-shop.html#"><img src="/web/images/client-1.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="200">
							<a href="/index-shop.html#"><img src="/web/images/client-2.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="300">
							<a href="/index-shop.html#"><img src="/web/images/client-3.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="400">
							<a href="/index-shop.html#"><img src="/web/images/client-4.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="500">
							<a href="/index-shop.html#"><img src="/web/images/client-5.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="600">
							<a href="/index-shop.html#"><img src="/web/images/client-6.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="700">
							<a href="/index-shop.html#"><img src="/web/images/client-7.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="800">
							<a href="/index-shop.html#"><img src="/web/images/client-8.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="100">
							<a href="/index-shop.html#"><img src="/web/images/client-1.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="200">
							<a href="/index-shop.html#"><img src="/web/images/client-2.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="300">
							<a href="/index-shop.html#"><img src="/web/images/client-3.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="400">
							<a href="/index-shop.html#"><img src="/web/images/client-4.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="500">
							<a href="/index-shop.html#"><img src="/web/images/client-5.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="600">
							<a href="/index-shop.html#"><img src="/web/images/client-6.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="700">
							<a href="/index-shop.html#"><img src="/web/images/client-7.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="800">
							<a href="/index-shop.html#"><img src="/web/images/client-8.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="100">
							<a href="/index-shop.html#"><img src="/web/images/client-1.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="200">
							<a href="/index-shop.html#"><img src="/web/images/client-2.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="300">
							<a href="/index-shop.html#"><img src="/web/images/client-3.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="400">
							<a href="/index-shop.html#"><img src="/web/images/client-4.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="500">
							<a href="/index-shop.html#"><img src="/web/images/client-5.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="600">
							<a href="/index-shop.html#"><img src="/web/images/client-6.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="700">
							<a href="/index-shop.html#"><img src="/web/images/client-7.png" alt=""></a>
						</div>
						<div class="client-image object-non-visible animated object-visible fadeIn" data-animation-effect="fadeIn" data-effect-delay="800">
							<a href="/index-shop.html#"><img src="/web/images/client-8.png" alt=""></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- section end -->

<!-- section start -->
<!-- ================ -->
<section class="section light-gray-bg clearfix">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<h2 class="text-center">Featured <strong>Categories</strong></h2>
				<div class="separator"></div>
				<p class="lead text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa unde sequi consectetur atque blanditiis rem sed porro ducimus, quidem inventore eum quis.</p>
			</div>
		</div>
	</div>
	<div class="owl-carousel carousel-autoplay pl-10 pr-10">
		<div class="listing-item pl-10 pr-10 mb-20">
			<div class="overlay-container bordered overlay-visible">
				<img src="/web/images/category-1.jpg" alt="">
				<a class="overlay-link" href="#"><i class="fa fa-plus"></i></a>
				<div class="overlay-bottom">
					<div class="text">
						<h3 class="title">Category Title</h3>
						<div class="separator light"></div>
						<p class="small margin-clear"><em>Quia nostrum temporibus et, <br> velit debitis ab, eligendi totam.</em></p>
					</div>
				</div>
			</div>
		</div>
		<div class="listing-item pl-10 pr-10 mb-20">
			<div class="overlay-container bordered overlay-visible">
				<img src="/web/images/category-2.jpg" alt="">
				<a class="overlay-link" href="#"><i class="fa fa-plus"></i></a>
				<div class="overlay-bottom">
					<div class="text">
						<h3 class="title">Category Title</h3>
						<div class="separator light"></div>
						<p class="small margin-clear"><em>Quia nostrum temporibus et, <br> velit debitis ab, eligendi totam.</em></p>
					</div>
				</div>
			</div>
		</div>
		<div class="listing-item pl-10 pr-10 mb-20">
			<div class="overlay-container bordered overlay-visible">
				<img src="/web/images/category-3.jpg" alt="">
				<a class="overlay-link" href="#"><i class="fa fa-plus"></i></a>
				<div class="overlay-bottom">
					<div class="text">
						<h3 class="title">Category Title</h3>
						<div class="separator light"></div>
						<p class="small margin-clear"><em>Quia nostrum temporibus et, <br> velit debitis ab, eligendi totam.</em></p>
					</div>
				</div>
			</div>
		</div>
		<div class="listing-item pl-10 pr-10 mb-20 mb-20">
			<div class="overlay-container bordered overlay-visible">
				<img src="/web/images/category-4.jpg" alt="">
				<a class="overlay-link" href="#"><i class="fa fa-plus"></i></a>
				<div class="overlay-bottom">
					<div class="text">
						<h3 class="title">Category Title</h3>
						<div class="separator light"></div>
						<p class="small margin-clear"><em>Quia nostrum temporibus et, <br> velit debitis ab, eligendi totam.</em></p>
					</div>
				</div>
			</div>
		</div>
		<div class="listing-item pl-10 pr-10 mb-20 mb-20">
			<div class="overlay-container bordered overlay-visible">
				<img src="/web/images/category-5.jpg" alt="">
				<a class="overlay-link" href="#"><i class="fa fa-plus"></i></a>
				<div class="overlay-bottom">
					<div class="text">
						<h3 class="title">Category Title</h3>
						<div class="separator light"></div>
						<p class="small margin-clear"><em>Quia nostrum temporibus et, <br> velit debitis ab, eligendi totam.</em></p>
					</div>
				</div>
			</div>
		</div>
		<div class="listing-item pl-10 pr-10 mb-20 mb-20">
			<div class="overlay-container bordered overlay-visible">
				<img src="/web/images/category-6.jpg" alt="">
				<a class="overlay-link" href="#"><i class="fa fa-plus"></i></a>
				<div class="overlay-bottom">
					<div class="text">
						<h3 class="title">Category Title</h3>
						<div class="separator light"></div>
						<p class="small margin-clear"><em>Quia nostrum temporibus et, <br> velit debitis ab, eligendi totam.</em></p>
					</div>
				</div>
			</div>
		</div>
	</div>		
	<div class="owl-controls"><div class="owl-buttons"><div class="owl-prev"></div><div class="owl-next"></div></div></div></div>
</section>
<!-- section end -->

<!-- section start -->
<!-- ================ -->
<section class="section dark-translucent-bg pv-40" style="background-image:url(&#39;web/images/shop-banner.jpg&#39;);background-position: 50% 32%;">
	<div class="container">
		<div class="row grid-space-10">
			<div class="col-md-3 col-sm-6">
				<div class="pv-30 ph-20 feature-box text-center object-non-visible animated object-visible fadeInDownSmall" data-animation-effect="fadeInDownSmall" data-effect-delay="100">
					<span class="icon default-bg"><i class="fa fa-diamond"></i></span>
					<h3>Premium &amp; Guaranteed Quality</h3>
					<div class="separator clearfix"></div>
					<p>Voluptatem ad provident non repudiandae beatae cupiditate.</p>
					<a href="/page-services.html" class="link-dark">Read More<i class="pl-5 fa fa-angle-double-right"></i></a>
				</div>
			</div>
			<div class="col-md-3 col-sm-6">
				<div class="pv-30 ph-20 feature-box text-center object-non-visible animated object-visible fadeInDownSmall" data-animation-effect="fadeInDownSmall" data-effect-delay="150">
					<span class="icon default-bg"><i class="icon-lock"></i></span>
					<h3>Secure &amp; Safe Payment</h3>
					<div class="separator clearfix"></div>
					<p>Iure sequi unde hic. Sapiente quaerat sequi inventore.</p>
					<a href="/page-services.html" class="link-dark">Read More<i class="pl-5 fa fa-angle-double-right"></i></a>
				</div>
			</div>
			<div class="clearfix visible-sm"></div>
			<div class="col-md-3 col-sm-6">
				<div class="pv-30 ph-20 feature-box text-center object-non-visible animated object-visible fadeInDownSmall" data-animation-effect="fadeInDownSmall" data-effect-delay="200">
					<span class="icon default-bg"><i class="icon-globe"></i></span>
					<h3 class="pl-10 pr-10">Free &amp; Fast Shipping</h3>
					<div class="separator clearfix"></div>
					<p>Inventore dolores aut laboriosam cum consequuntur.</p>
					<a href="/page-services.html" class="link-dark">Read More<i class="pl-5 fa fa-angle-double-right"></i></a>
				</div>
			</div>
			<div class="col-md-3 col-sm-6">
				<div class="pv-30 ph-20 feature-box text-center object-non-visible animated object-visible fadeInDownSmall" data-animation-effect="fadeInDownSmall" data-effect-delay="250">
					<span class="icon default-bg"><i class="icon-thumbs-up"></i></span>
					<h3>24/7 Customer Support</h3>
					<div class="separator clearfix"></div>
					<p>Inventore dolores aut laboriosam cum consequuntur.</p>
					<a href="/page-services.html" class="link-dark">Read More<i class="pl-5 fa fa-angle-double-right"></i></a>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="call-to-action text-center">
					<div class="row">
						<div class="col-md-8 col-md-offset-2">
							<h2 class="title"><strong>Subscribe</strong> To Our Newsletter</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellendus error pariatur deserunt laudantium nam, mollitia quas nihil inventore, quibusdam?</p>
							<div class="separator"></div>
							<form class="form-inline margin-clear">
								<div class="form-group has-feedback">
									<label class="sr-only" for="subscribe3">Email address</label>
									<input type="email" class="form-control form-control-lg" id="subscribe3" placeholder="Enter email" name="subscribe3" required="">
									<i class="fa fa-envelope form-control-feedback"></i>
								</div>
								<button type="submit" class="btn btn-lg btn-gray-transparent btn-animated margin-clear">Submit <i class="fa fa-send"></i></button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- section end -->