<?php
$request = $this->requestHelper();
$cartItems = Application\Lib\Cart::get();
$totalQuantity = 0;
$totalMoney = 0;
if (!empty($cartItems)) {    
    foreach ($cartItems as $item) {
        $totalQuantity += $item['quantity'];
        $totalMoney += $item['quantity'] * $item['price'];
    }
}
$checkoutInfo = Application\Lib\Session::get('checkout_step1');
?>
<!-- main-container start -->
<!-- ================ -->
<section class="main-container">

    <div class="container">
        <div class="row">

            <!-- main start -->
            <!-- ================ -->
            <div class="main col-md-12">
                
                <ul class="step clearfix" id="order_step">
                    <li class="step_todo first">
                        <span><em>01.</em> <?php echo $this->translate('Cart')?></span>
                    </li>
                    <li class="step_current second">
                        <span><em>02.</em> <?php echo $this->translate('Customer information')?></span>
                    </li>
                    <li class="step_todo third">
                        <span><em>03.</em> <?php echo $this->translate('Checkout')?></span>
                    </li>
                    <li id="step_end" class="step_todo last">
                        <span><em>04.</em> <?php echo $this->translate('Confirm')?></span>
                    </li>
                </ul>
                
                <table class="table cart">
                    <thead>
                        <tr>
                            <th><strong><?php echo $this->translate('Product name')?></strong></th>
                            <th><strong><?php echo $this->translate('Price')?></strong></th>
                            <th><strong><?php echo $this->translate('Quantity')?></strong></th>
                            <th class="amount"><strong><?php echo $this->translate('Total')?></strong></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($cartItems as $item) : ?>
                        <tr>
                            <td class="product">
                                <a href="<?php echo $this->url('web/products', array('name' => name_2_url($item['name'])))?>">
                                    <?php echo $item['custom_name']?>
                                </a> 
                            </td>
                            <td class="price"><?php echo app_money_format($item['price'])?></td>
                            <td class="quantity">
                                <div class="form-group">
                                    <input type="text" class="form-control" value="<?php echo $item['quantity']?>" disabled="">
                                </div>											
                            </td>
                            <td class="amount"><?php echo app_money_format($item['quantity'] * $item['price'])?></td>
                        </tr>
                        <?php endforeach ?>                        
                        <tr class="row-total-payment">                           
                            <td colspan="4" align="right">
                                <div class="p-20">
                                    <strong><?php echo $this->translate('Total')?>:</strong> 
                                    <span class="total-amount"><?php echo app_money_format($totalMoney)?></span>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
                
                <?php if (!empty($registerAddressForm)): ?>
                <fieldset>
                    <legend><strong><?php echo $this->translate('Devivery information')?></strong></legend>
                    <?php 
                        $registerAddressForm->prepare();
                        echo $this->form()->openTag($registerAddressForm);                 
                    ?>
                    <div class="row">
                        <!--
                        <div class="col-lg-3">
                            <h3 class="title"><?php echo $this->translate('Personal Info')?></h3>
                        </div>
                        -->
                        <div class="col-lg-10 col-lg-offset-1">
                            <div class="form-group">
                                <div class="col-md-3 control-label"><?php echo $this->formLabel($registerAddressForm->get('name'));?></div>
                                <div class="col-md-9">
                                    <?php echo $this->formText($registerAddressForm->get('name'));?>
                                    <?php echo $this->formErrorMessage($registerAddressForm->get('name')); ?>                                
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-3 control-label"><?php echo $this->formLabel($registerAddressForm->get('mobile'));?></div>
                                <div class="col-md-9">
                                    <?php echo $this->formText($registerAddressForm->get('mobile'));?>
                                    <?php echo $this->formErrorMessage($registerAddressForm->get('mobile')); ?>                                
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-3 control-label"><?php echo $this->formLabel($registerAddressForm->get('email'));?></div>
                                <div class="col-md-9">
                                    <?php echo $this->formText($registerAddressForm->get('email'));?>
                                    <?php echo $this->formErrorMessage($registerAddressForm->get('email')); ?>                                
                                </div>
                            </div>
                            
                            <?php if (!empty($addresses)): ?>
                            <div class="form-group">     
                                <div style="padding-top:0px" class="col-md-3 control-label">Địa chỉ giao hàng</div> 
                                <div class="col-md-9">                                    
                                    <?php foreach($addresses as $addressId => $fullAddress): ?>
                                    <div class="address-row">
                                        <input name="address_id" 
                                               type="radio" 
                                               <?php if (isset($checkoutInfo['address_id']) && $checkoutInfo['address_id']==$addressId) echo 'checked' ?>
                                               value="<?php echo $addressId?>" 
                                               onclick='$("#new-address").addClass("hide");'/> 
                                        <?php echo $fullAddress;?>
                                    </div>                                    
                                    <?php endforeach;?>                                     
                                    <div class="address-row">
                                        <input name="address_id" 
                                               type="radio" 
                                               <?php if (empty($checkoutInfo['address_id'])) echo 'checked' ?>
                                               value="0" 
                                               onclick='$("#new-address").removeClass("hide");$("#city_code").val("");$("#street").val("");'/> 
                                        Địa chỉ khác
                                    </div>                                    
                                </div>
                            </div>
                            <?php endif;?>
                        </div>
                    </div>   
                    
                    <div class="row <?php echo !empty($checkoutInfo['address_id']) ? ' hide' : ''?>" id="new-address">
                        <!--
                        <div class="col-lg-3">
                            <h3 class="title"><?php echo $this->translate('Delivery address')?></h3>
                        </div>
                        -->
                        <div class="col-lg-10 col-lg-offset-1">                            
                            <div class="form-group hide">
                                <div class="col-md-3 control-label"><?php echo $this->formLabel($registerAddressForm->get('country_code'));?></div>
                                <div class="col-md-9">
                                    <?php echo $this->formSelect($registerAddressForm->get('country_code'));?>
                                    <?php echo $this->formErrorMessage($registerAddressForm->get('country_code')); ?>                                
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-3 control-label"><?php echo $this->formLabel($registerAddressForm->get('state_code'));?></div>
                                <div class="col-md-9">
                                    <?php echo $this->formSelect($registerAddressForm->get('state_code'));?>
                                    <?php echo $this->formErrorMessage($registerAddressForm->get('state_code')); ?>                                
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-3 control-label"><?php echo $this->formLabel($registerAddressForm->get('city_code'));?></div>
                                <div class="col-md-9">
                                    <?php echo $this->formSelect($registerAddressForm->get('city_code'));?>
                                    <?php echo $this->formErrorMessage($registerAddressForm->get('city_code')); ?>                                
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-3 control-label"><?php echo $this->formLabel($registerAddressForm->get('street'));?></div>
                                <div class="col-md-9">
                                    <?php echo $this->formText($registerAddressForm->get('street'));?>
                                    <?php echo $this->formErrorMessage($registerAddressForm->get('street')); ?>                                
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-3 control-label"><?php echo $this->formLabel($registerAddressForm->get('address_name'));?></div>
                                <div class="col-md-9">
                                    <?php echo $this->formSelect($registerAddressForm->get('address_name'));?>
                                    <?php echo $this->formErrorMessage($registerAddressForm->get('address_name')); ?>                                
                                </div>
                            </div>                            
                        </div>
                    </div> 
                    <?php                       
                        echo $this->form()->closeTag();
                        unset($registerAddressForm);
                    ?>
                </fieldset>                           
                <?php endif ?>                
                
                <?php if (!empty($registerForm)): ?>
                <?php 
                    $registerForm->prepare();
                    echo $this->form()->openTag($registerForm);                        
                ?>
                <fieldset>
                    <legend><strong><?php echo $this->translate('Signup Account')?></strong></legend>                    
                    <div class="row">                        
                        <div class="col-lg-10 col-lg-offset-1">                            
                            <div class="form-group">
                                <div class="col-md-3 control-label"><?php echo $this->formLabel($registerForm->get('email'));?></div>
                                <div class="col-md-9">
                                    <?php echo $this->formText($registerForm->get('email'));?>
                                    <?php echo $this->formErrorMessage($registerForm->get('email')); ?>                                
                                </div>
                            </div>                            
                            <div class="form-group">
                                <div class="col-md-3 control-label"><?php echo $this->formLabel($registerForm->get('password'));?></div>
                                <div class="col-md-9">
                                    <?php echo $this->formPassword($registerForm->get('password'));?>
                                    <?php echo $this->formErrorMessage($registerForm->get('password')); ?>                                
                                </div>
                            </div>                            
                            <div class="form-group">
                                <div for="password_confirmation" class="col-md-3 control-label"><?php echo $this->formLabel($registerForm->get('password_confirmation'));?></div>
                                <div class="col-md-9">
                                    <?php echo $this->formPassword($registerForm->get('password_confirmation'));?>
                                    <?php echo $this->formErrorMessage($registerForm->get('password_confirmation')); ?>                                
                                </div>
                            </div>
                            <div class="col-sm-offset-3 col-sm-8 mt8m">
                                <a itemprop="url" href="<?php echo $this->url('web/login', array(), array('query' => array('backurl' => $this->requestHelper()->getRequestUri())))?>" class="btn btn-default btn-sm">
                                    <i class="fa fa-lock pr-10"></i> 
                                    <span itemprop="name"><?php echo $this->translate('Login with registed account')?></span>
                                </a>
                            </div>
                            <div class="col-sm-offset-3 col-sm-8 mt8m"> 
                                <span class="text-center text-muted"><?php echo $this->translate('Or login with')?></span>
                                <ul class="social-links colored circle clearfix mt5 ml0">
                                    <li class="facebook"><a href="<?php echo $this->url('web/fblogin', array(), array('query' => array('backurl' => $request->getRequestUri())))?>"><i class="fa fa-facebook"></i></a></li>                              
                                    <li class="googleplus"><a href="<?php echo $this->url('web/glogin', array(), array('query' => array('backurl' => $request->getRequestUri())))?>"><i class="fa fa-google-plus"></i></a></li>
                                </ul>
                            </div>                            
                        </div>                            
                    </div>                            
                </fieldset>   
                 
                <div class="space-bottom"></div> 
                
                <fieldset>
                    <legend><strong><?php echo $this->translate('Devivery information')?></strong></legend>                    
                    <div class="row">
                        <div class="col-lg-10 col-lg-offset-1"> 
                            <div class="form-group">
                                <div for="name" class="col-md-3 control-label"><?php echo $this->formLabel($registerForm->get('name'));?></div>
                                <div class="col-md-9">
                                    <?php echo $this->formText($registerForm->get('name'));?>
                                    <?php echo $this->formErrorMessage($registerForm->get('name')); ?>                                
                                </div>
                            </div>
                            <div class="form-group">
                                <div for="mobile" class="col-md-3 control-label"><?php echo $this->formLabel($registerForm->get('mobile'));?></div>
                                <div class="col-md-9">
                                    <?php echo $this->formText($registerForm->get('mobile'));?>
                                    <?php echo $this->formErrorMessage($registerForm->get('mobile')); ?>                                
                                </div>
                            </div>
                            <div class="form-group hide">
                                <div for="country_code" class="col-md-3 control-label"><?php echo $this->formLabel($registerForm->get('country_code'));?></div>
                                <div class="col-md-9">
                                    <?php echo $this->formSelect($registerForm->get('country_code'));?>
                                    <?php echo $this->formErrorMessage($registerForm->get('country_code')); ?>                                
                                </div>
                            </div>
                            <div class="form-group">
                                <div for="state_code" class="col-md-3 control-label"><?php echo $this->formLabel($registerForm->get('state_code'));?></div>
                                <div class="col-md-9">
                                    <?php echo $this->formSelect($registerForm->get('state_code'));?>
                                    <?php echo $this->formErrorMessage($registerForm->get('state_code')); ?>                                
                                </div>
                            </div>
                            <div class="form-group">
                                <div for="city_code" class="col-md-3 control-label"><?php echo $this->formLabel($registerForm->get('city_code'));?></div>
                                <div class="col-md-9">
                                    <?php echo $this->formSelect($registerForm->get('city_code'));?>
                                    <?php echo $this->formErrorMessage($registerForm->get('city_code')); ?>                                
                                </div>
                            </div>
                            <div class="form-group">
                                <div for="street" class="col-md-3 control-label"><?php echo $this->formLabel($registerForm->get('street'));?></div>
                                <div class="col-md-9">
                                    <?php echo $this->formText($registerForm->get('street'));?>
                                    <?php echo $this->formErrorMessage($registerForm->get('street')); ?>                                
                                </div>
                            </div>
                            
                            <?php foreach($addresses as $addressId => $fullAddress): ?>
                            <div class="form-group">                                
                                <div class="col-md-12">
                                    <?php echo $fullAddress;?>
                                </div>
                            </div>
                            <?php endforeach;?>  
                            
                            <div class="form-group">
                                <div for="address_name" class="col-md-3 control-label"><?php echo $this->formLabel($registerForm->get('address_name'));?></div>
                                <div class="col-md-9">
                                    <?php echo $this->formSelect($registerForm->get('address_name'));?>
                                    <?php echo $this->formErrorMessage($registerForm->get('address_name')); ?>                                
                                </div>
                            </div>
                        </div>
                    </div>                            
                </fieldset>            
                
                
                <?php                       
                    echo $this->form()->closeTag();
                    unset($registerForm);
                ?>
                <?php endif ?>
                
                <div class="space-bottom"></div> 
                
                <fieldset>
                    <legend><strong><?php echo $this->translate('Shipping money')?></strong></legend>                    
                    <div class="row" id="ship_money">
                        <?php echo \Web\Module::getConfig('ship_money')?>
                    </div>
                </fieldset>
                
                <div class="space-bottom"></div>
                
                <div class="text-right checkout-button">
                    <a href="<?php echo $this->url('web/carts', array('action' => 'view'))?>" class="btn btn-group btn-default"><i class="icon-left-open-big"></i> <?php echo $this->translate('Back to cart')?></a>
                    <a id="checkout-next" href="<?php echo $this->url('web/checkout', array('action' => 'payment'))?>" class="btn btn-group btn-default" style="margin-left:3px;"><?php echo !empty($AppUI) ? $this->translate('Next step') : $this->translate('Signup Account and Go next step')?> <i class="icon-right-open-big"></i></a>
                </div>

            </div>
            <!-- main end -->

        </div>
    </div>
</section>
<!-- main-container end -->
<?php
$this->headScript()->offsetSetScript(100, " 
    $(function() {
        var address_id = $('#address_id').val(); 
        if (address_id == '') {
            $('#new-address').removeClass('hide');
        }
    });
");
?>	