<?php
$checkoutInfo = Application\Lib\Session::get('checkout_step1');
$cartItems = Application\Lib\Cart::get();
$totalQuantity = 0;
$totalMoney = 0;
if (!empty($cartItems)) {    
    foreach ($cartItems as $item) {
        $totalQuantity += $item['quantity'];
        $totalMoney += $item['quantity'] * $item['price'];
    }
}
?>
<!-- main-container start -->
<!-- ================ -->
<section class="main-container">

    <div class="container">
        <div class="row">

            <!-- main start -->
            <!-- ================ -->
            <div class="main col-md-12">

                <ul class="step clearfix" id="order_step">
                    <li class="step_todo first">
                        <span><em>01.</em> <?php echo $this->translate('Cart')?></span>
                    </li>
                    <li class="step_todo second">
                        <span><em>02.</em> <?php echo $this->translate('Customer information')?></span>
                    </li>
                    <li class="step_todo third">
                        <span><em>03.</em> <?php echo $this->translate('Checkout')?></span>
                    </li>
                    <li id="step_end" class="step_current last">
                      <span><em>04.</em> <?php echo $this->translate('Confirm')?></span>
                    </li>
                </ul>

                <table class="table cart">
                    <thead>
                        <tr>
                            <th><strong><?php echo $this->translate('Product name')?></strong></th>
                            <th><strong><?php echo $this->translate('Price')?></strong></th>
                            <th><strong><?php echo $this->translate('Quantity')?></strong></th>
                            <th class="amount"><strong><?php echo $this->translate('Total')?></strong></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($cartItems as $item) : ?>
                        <tr>
                            <td class="product">
                                <a href="<?php echo $this->url('web/products', array('name' => name_2_url($item['name'])))?>">
                                    <?php echo $item['custom_name']?>
                                </a> 
                            </td>
                            <td class="price"><?php echo app_money_format($item['price'])?></td>
                            <td class="quantity">
                                <div class="form-group">
                                    <input type="text" class="form-control" value="<?php echo $item['quantity']?>" disabled="">
                                </div>											
                            </td>
                            <td class="amount"><?php echo app_money_format($item['quantity'] * $item['price'])?></td>
                        </tr>
                        <?php endforeach ?>                        
                       
                    </tbody>
                </table>
                            
                
                <?php 
                    $reviewForm->prepare();
                    echo $this->form()->openTag($reviewForm);                 
                ?>
                
                
                    
                <table class="table">
                    <thead>
                        <tr>
                            <th colspan="2"><strong><?php echo $this->translate('Order confirmation')?></strong></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (!empty($checkoutInfo['name'])): ?>
                        <tr>
                            <td><?php echo $this->translate('Customer name')?></td>
                            <td class="information"><?php echo $checkoutInfo['name'];?></td>
                        </tr>
                        <?php endif ?>                        
                        <?php if (!empty($checkoutInfo['phone'])): ?>
                        <tr>
                            <td><?php echo $this->translate('Home phone')?></td>
                            <td class="information"><?php echo $checkoutInfo['phone'];?></td>
                        </tr>
                        <?php endif ?>
                        <?php if (!empty($checkoutInfo['mobile'])): ?>
                        <tr>
                            <td><?php echo $this->translate('Mobile')?></td>
                            <td class="information"><?php echo $checkoutInfo['mobile'];?></td>
                        </tr>
                        <?php endif ?>
                        <?php if (!empty($checkoutInfo['email'])): ?>
                        <tr>
                            <td><?php echo $this->translate('Email')?></td>
                            <td class="information"><?php echo $checkoutInfo['email'];?></td>
                        </tr>
                        <?php endif ?>
                        <tr>
                            <td><?php echo $this->translate('Delivery address')?></td>
                            <td class="information">
                                <?php
                                    $address = array();
                                    if (!empty($checkoutInfo['street'])) {
                                        $address[] = $checkoutInfo['street'];
                                    }
                                    if (!empty($checkoutInfo['city_code']) 
                                        && !empty($checkoutInfo['state_code']) 
                                        && !empty($checkoutInfo['country_code'])) {
                                        $cities = \Application\Model\LocaleCities::getAll($checkoutInfo['state_code'], $checkoutInfo['country_code']);                                                
                                        $address[] = $cities[$checkoutInfo['city_code']];
                                    }   
                                    if (!empty($checkoutInfo['state_code']) 
                                        && !empty($checkoutInfo['country_code'])) {
                                        $states = \Application\Model\LocaleStates::getAll($checkoutInfo['country_code']);                                                
                                        $address[] = $states[$checkoutInfo['state_code']];
                                    }                                   
                                    if (!empty($checkoutInfo['country_code'])) {
                                        $countries = \Application\Model\LocaleCountries::getAll();  
                                        $address[] = $countries[$checkoutInfo['country_code']];
                                    }                                    
                                    echo implode(', ', $address);
                                ?>
                            </td>
                        </tr>                         
                        <?php if (!empty($checkoutInfo['discount'])): ?> 
                        <tr>
                            <td><?php echo $this->translate('Total');?></td>
                            <td class="information total-amount">                                
                                <?php echo app_money_format($totalMoney)?>
                            </td>
                        </tr>
                        <tr>
                            <td><?php echo $this->translate('Discount')?></td>
                            <td class="information">
                                <span class="total-amount"><?php echo app_money_format($checkoutInfo['discount']); ?></span>
                                (<?php echo $this->translate('Voucher code')?>: <strong><?php echo $checkoutInfo['voucher_code']; ?></strong>)
                            </td>
                        </tr> 
                        <tr>
                            <td><?php echo $this->translate('Shipping money')?></td>
                            <td class="information">
                                <span class="total-amount"><?php echo app_money_format($checkoutInfo['ship_money']); ?></span>                               
                            </td>
                        </tr>
                        <tr>
                            <td><?php echo $this->translate('Total payment')?></td>
                            <td class="information total-amount">
                                <?php echo app_money_format($checkoutInfo['last_total_money']); ?>
                            </td>
                        </tr>                        
                        <?php else: ?>
                        <tr>
                            <td><?php echo $this->translate('Total');?></td>
                            <td class="information total-amount">                                
                                <?php echo app_money_format($totalMoney)?>
                            </td>
                        </tr>
                        <tr>
                            <td><?php echo $this->translate('Shipping money')?></td>
                            <td class="information">
                                <span class="total-amount"><?php echo app_money_format($checkoutInfo['ship_money']); ?></span>                               
                            </td>
                        </tr>
                        <tr>
                            <td><?php echo $this->translate('Total payment');?></td>
                            <td class="information total-amount">                                
                                <?php echo app_money_format($checkoutInfo['ship_money'] + $totalMoney)?>
                            </td>
                        </tr>
                        <?php endif ?>
                        
                        <tr>
                            <td><?php echo $this->translate('Payment')?></td>
                            <td class="information">
                            <?php if ($checkoutInfo['payment'] == 'ATM'): ?> 
                                ✓ <?php echo $this->translate('Transfer via Bank') ?>
                                <div class="bank-account" style="padding-left:0px;"><?php echo \Web\Module::getConfig('bank_account')?></div>
                            <?php else: ?>   
                                ✓ <?php echo $this->translate('COD'); ?>
                            <?php endif ?> 
                            </td>
                        </tr>
                        
                        <tr>
                            <td><?php echo $this->formLabel($reviewForm->get('note'));?></td>
                            <td class="information">
                                <?php echo $this->formTextArea($reviewForm->get('note'));?>
                                <?php echo $this->formErrorMessage($reviewForm->get('note')); ?>
                            </td>
                        </tr>
                        <!--
                        <tr>
                            <td>&nbsp;</td>
                            <td class="information">                                
                                <span><input id="confirmation" name="confirmation" type="checkbox" style="width:20px; float:left;"/></span>                                
                                <span><?php echo $this->translate('I want to have this order')?></span>                                
                            </td>
                        </tr>
                        -->
                    </tbody>
                </table>
                
                <div class="text-right checkout-button">
                    <a href="<?php echo $this->url('web/checkout', array('action' => 'payment'))?>" class="btn btn-group btn-default"><i class="icon-left-open-big"></i> <?php echo $this->translate('Go back')?></a>
                    <a  id="checkoutFinish" 
                        class="btn btn-group btn-default"
                        style="margin-left:3px;"
                        href="<?php echo $this->url('web/checkout', array('action' => 'comoleted'))?>">
                        <i class="icon-check"></i> <?php echo $this->translate('Complete your order')?>
                    </a>
                </div>
                <?php           
                    echo $this->formHidden($reviewForm->get('csrf'));
                    echo $this->form()->closeTag();
                    unset($reviewForm);
                ?>                
            </div>
            <!-- main end -->

        </div>
    </div>
</section>
<!-- main-container end -->
