<!-- main-container start -->
<!-- ================ -->
<section class="main-container">

    <div class="container">
        <div class="row">

            <!-- main start -->
            <!-- ================ -->
            <div class="main col-md-12">

                <!-- page-title start -->
                <!-- ================ -->
                <h1 class="page-title"><?php echo $this->translate('Shopping Cart')?></h1>
                <div class="separator-2"></div>
                <!-- page-title end -->

                <table class="table cart table-hover table-colored">
                    <thead>
                        <tr>
                            <th class="th-remove"><?php echo $this->translate('Remove')?></th>
                            <th class="th-product-name"><?php echo $this->translate('Product')?></th>
                            <th class="th-product-price"><?php echo $this->translate('Price')?></th>
                            <th class="th-product-qunatity"><?php echo $this->translate('Quantity')?></th>                            
                            <th class="th-product-amount" class="amount"><?php echo $this->translate('Total')?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="remove-data">
                            <td class="product"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Product Title 1</a> <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</small></td>
                            <td class="price">$99.50 </td>
                            <td class="quantity">
                                <div class="form-group">
                                    <input type="text" class="form-control" value="2">
                                </div>											
                            </td>
                            <td class="remove"><a class="btn btn-remove btn-sm btn-default">Remove</a></td>
                            <td class="amount">$199.00 </td>
                        </tr>
                        <tr class="remove-data">
                            <td class="product"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Product Title 2</a> <small>Quas inventore modi</small></td>
                            <td class="price"> $99.66 </td>
                            <td class="quantity">
                                <div class="form-group">
                                    <input type="text" class="form-control" value="3">
                                </div>											
                            </td>
                            <td class="remove"><a class="btn btn-remove btn-sm btn-default">Remove</a></td>
                            <td class="amount">$299.00 </td>
                        </tr>
                        <tr class="remove-data">
                            <td class="product"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Product Title 3</a> <small>Fugiat nemo enim officiis repellendus</small></td>
                            <td class="price"> $499.66 </td>
                            <td class="quantity">
                                <div class="form-group">
                                    <input type="text" class="form-control" value="3">
                                </div>											
                            </td>
                            <td class="remove"><a class="btn btn-remove btn-sm btn-default">Remove</a></td>
                            <td class="amount">$1499.00 </td>
                        </tr>
                        <tr>
                            <td colspan="3">Discount Coupon</td>
                            <td colspan="2">
                                <div class="form-group">
                                    <input type="text" class="form-control">
                                </div>											
                            </td>
                        </tr>
                        <tr>
                            <td class="total-quantity" colspan="4">Total 8 Items</td>
                            <td class="total-amount">$1997.00</td>
                        </tr>
                    </tbody>
                </table>
                <div class="text-right">	
                    <a href="/web/images/cart.html" class="btn btn-group btn-default">Update Cart</a>
                    <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-checkout.html" class="btn btn-group btn-default">Checkout</a>
                </div>

            </div>
            <!-- main end -->

        </div>
    </div>
</section>
<!-- main-container end -->

<!-- section start -->
<!-- ================ -->
<section class="pv-30 dark-translucent-bg padding-bottom-clear" style="background-image:url(&#39;images/shop-banner.jpg&#39;);background-position: 50% 32%;">
    <div class="container">
        <div class="row grid-space-10">
            <div class="col-md-3 col-sm-6">
                <div class="pv-30 ph-20 feature-box text-center object-non-visible" data-animation-effect="fadeInDownSmall" data-effect-delay="100">
                    <span class="icon default-bg"><i class="fa fa-diamond"></i></span>
                    <h3>Premium &amp; Guaranteed Quality</h3>
                    <div class="separator clearfix"></div>
                    <p>Voluptatem ad provident non repudiandae beatae cupiditate.</p>
                    <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/page-services.html" class="link-dark">Read More<i class="pl-5 fa fa-angle-double-right"></i></a>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="pv-30 ph-20 feature-box text-center object-non-visible" data-animation-effect="fadeInDownSmall" data-effect-delay="150">
                    <span class="icon default-bg"><i class="icon-lock"></i></span>
                    <h3>Secure &amp; Safe Payment</h3>
                    <div class="separator clearfix"></div>
                    <p>Iure sequi unde hic. Sapiente quaerat sequi inventore.</p>
                    <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/page-services.html" class="link-dark">Read More<i class="pl-5 fa fa-angle-double-right"></i></a>
                </div>
            </div>
            <div class="clearfix visible-sm"></div>
            <div class="col-md-3 col-sm-6">
                <div class="pv-30 ph-20 feature-box text-center object-non-visible" data-animation-effect="fadeInDownSmall" data-effect-delay="200">
                    <span class="icon default-bg"><i class="icon-globe"></i></span>
                    <h3 class="pl-10 pr-10">Free &amp; Fast Shipping</h3>
                    <div class="separator clearfix"></div>
                    <p>Inventore dolores aut laboriosam cum consequuntur.</p>
                    <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/page-services.html" class="link-dark">Read More<i class="pl-5 fa fa-angle-double-right"></i></a>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="pv-30 ph-20 feature-box text-center object-non-visible" data-animation-effect="fadeInDownSmall" data-effect-delay="250">
                    <span class="icon default-bg"><i class="icon-thumbs-up"></i></span>
                    <h3>24/7 Customer Support</h3>
                    <div class="separator clearfix"></div>
                    <p>Inventore dolores aut laboriosam cum consequuntur.</p>
                    <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/page-services.html" class="link-dark">Read More<i class="pl-5 fa fa-angle-double-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- section end -->

<!-- section start -->
<!-- ================ -->
<section class="pv-30 clearfix">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="block clearfix">
                    <h3 class="title">Top Rated</h3>
                    <div class="separator-2"></div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-1.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Lorem ipsum dolor sit amet</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                            </p>
                            <p class="price">$99.00</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-2.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Eum repudiandae ipsam</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$299.00</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-3.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Quia aperiam velit fuga</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$9.99</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-4.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Fugit non natus officiis</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$399.00</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="block clearfix">
                    <h3 class="title">Related</h3>
                    <div class="separator-2"></div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-5.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Lorem ipsum dolor sit amet</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                            </p>
                            <p class="price">$99.00</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-6.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Eum repudiandae ipsam</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$299.00</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-7.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Quia aperiam velit fuga</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$9.99</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-8.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Fugit non natus officiis</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$399.00</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="block clearfix">
                    <h3 class="title">Best Sellers</h3>
                    <div class="separator-2"></div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-3.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Lorem ipsum dolor sit amet</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                            </p>
                            <p class="price">$99.00</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-5.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Eum repudiandae ipsam</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$299.00</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-7.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Quia aperiam velit fuga</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$9.99</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-1.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Fugit non natus officiis</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$399.00</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- section end -->