<?php 
    $request = $this->requestHelper();
    $priceFrom = $request->getQuery('price_from', '');
    $priceTo = $request->getQuery('price_to', '');    
    $categoryId = !empty($detailCategory['category_id']) ? $detailCategory['category_id'] : 0;
    $brandId = !empty($detailBrand['brand_id']) ? $detailBrand['brand_id'] : 0;    
?>
<div id="page-start"></div>
<!-- section start -->
<!-- ================ -->
<section class="section light-gray-bg clearfix">
	<div class="container">        
		<div class="row">
            <div class="col-md-3">
                <form id="sidebar_products_index_form">                
                    <div class="sidebar">
                        <?php if (!empty($subCategories)): ?>
                        <div class="block clearfix">
                            <h3 class="title"><?php echo $this->translate('Catalog') ?></h3>
                            <div class="separator-2"></div>
                            <nav class="app-category">
                                <ul itemscope itemtype="http://schema.org/Product" class="nav nav-pills nav-stacked nav-show">
                                    <?php foreach ($subCategories as $category) : ?>  
                                    <?php if (!empty($category['sub'])) : ?>  
                                        <li class="dropdown<?php if ($openCategoryId==$category['category_id']) echo ' open'?><?php if ($categoryId==$category['category_id']) echo ' active'?>">
                                            <a itemprop="name" class="dropdown-toggle" href="<?php echo $this->url('web/products', array('name' => name_2_url($category['name'])))?>">
                                                <?php echo $category['name'] ?>
                                            </a>
                                            <ul class="dropdown-menu">
                                                <?php foreach ($category['sub'] as $subCategory1) : ?> 
                                                <?php if (!empty($subCategory1['sub'])) : ?>  
                                                <li class="divider"></li>
                                                <li class="dropdown-header"><?php echo $subCategory1['name'] ?></li>
                                                <?php foreach ($subCategory1['sub'] as $subCategory2) : ?>
                                                <li class="sub-category2">
                                                    <a itemprop="name" href="<?php echo $this->url('web/products', array('name' => name_2_url($subCategory2['name'])))?>">
                                                        <?php echo $subCategory2['name'] ?>
                                                    </a>                                        
                                                </li>    
                                                <?php endforeach ?>  
                                                <?php else: ?>     
                                                <li<?php if ($categoryId==$subCategory1['category_id']) echo ' class="active"'?>>
                                                    <a itemprop="name" href="<?php echo $this->url('web/products', array('name' => name_2_url($subCategory1['name'])))?>">
                                                        <?php echo $subCategory1['name'] ?>
                                                    </a>                                        
                                                </li>
                                                <?php endif ?>
                                                <?php endforeach ?>                       
                                            </ul>
                                        </li>   
                                    <?php else: ?>     
                                         <li<?php if ($categoryId==$category['category_id']) echo ' class="active"'?>>
                                            <a itemprop="name" href="<?php echo $this->url('web/products', array('name' => name_2_url($category['name'])))?>">
                                                <?php echo $category['name'] ?>
                                            </a>                                        
                                        </li>  
                                    <?php endif ?>                                
                                    <?php endforeach ?>                                
                                </ul>
                            </nav>
                        </div>
                        <?php endif ?>

                        <?php if (empty($subCategories) && !empty($filter['category'])): ?>
                        <div class="block clearfix">
                            <h3 class="title"><?php echo $this->translate('Catalog') ?></h3>
                            <div class="separator-2"></div>
                            <nav>
                                <ul itemscope itemtype="http://schema.org/Product" class="nav nav-pills nav-stacked">
                                    <?php foreach ($filter['category'] as $category) : ?>  
                                    <li <?php if ($categoryId==$category['category_id']) echo ' class="active"'?>>
                                        <a itemprop="name" href="
                                            <?php
                                                $routeUrl = array(
                                                    'name' => name_2_url($category['category_name'])                                                   
                                                );
                                                /*
                                                if (!empty($detailBrand['name'])) {
                                                    $routeUrl['name2'] = name_2_url($detailBrand['name']);
                                                }
                                                 * 
                                                 */
                                                echo $this->url(
                                                    'web/products', 
                                                    $routeUrl
                                                )
                                            ?>">
                                            <?php echo $category['category_name'] ?>
                                        </a>
                                    </li>
                                    <?php endforeach ?>                                
                                </ul>
                            </nav>
                        </div>
                        <?php endif ?>                  

                        <?php if (!empty($filter['brand'])): ?>
                        <div class="block clearfix">
                            <h3 class="title"><?php echo $this->translate('Brand') ?></h3>
                            <div class="separator-2"></div>
                            <nav>
                                <ul itemscope itemtype="http://schema.org/Brand" class="nav nav-pills nav-stacked">
                                    <?php foreach ($filter['brand'] as $brand) : ?> 
                                    <?php if (!empty($brand['brand_name'])): ?>
                                    <li<?php if ($brandId==$brand['brand_id']) echo ' class="active"'?>>
                                        <a href="<?php 
                                            $routerParam = array(
                                                'name2' => name_2_url($brand['brand_name'])
                                            );
                                            if (!empty($detailCategory['name'])) {
                                                $routerParam['name'] = name_2_url($detailCategory['name']);
                                            }
                                            echo $this->url(
                                                'web/products', 
                                                $routerParam
                                            )?>">
                                            <span itemprop="name"><?php echo $brand['brand_name'] ?></span>
                                        </a>
                                    </li>
                                    <?php endif ?>                                
                                    <?php endforeach ?>                                
                                </ul>
                            </nav>
                        </div>
                        <?php endif ?>
                        
                        <?php if (!empty($filter['fields'])): ?>
                        <?php foreach ($filter['fields'] as $field) : ?> 
                        <div class="block clearfix">
                            <h3 class="title"><?php echo $field['name'] ?></h3>
                            <div class="separator-2"></div>
                            <nav>
                                <ul itemscope itemtype="http://schema.org/Brand" class="nav nav-pills nav-stacked">
                                    <?php foreach ($field['options']['value_options'] as $optId => $optionName): ?> 
                                    <?php if (!empty($optionName)): ?>
                                    <li<?php if ($optionId==$optId) echo ' class="active"'?>>
                                        <a href="<?php 
                                            $routerParam = array(
                                                'name2' => name_2_url($field['name'] . '-' . $optionName)
                                            );
                                            if (!empty($detailCategory['name'])) {
                                                $routerParam['name'] = name_2_url($detailCategory['name']);
                                            }
                                            echo $this->url(
                                                'web/products', 
                                                $routerParam
                                            )?>">
                                            <span itemprop="name"><?php echo $optionName ?></span>
                                        </a>
                                    </li>
                                    <?php endif ?>                                
                                    <?php endforeach ?>                                
                                </ul>
                            </nav>
                        </div>
                        <?php endforeach ?>  
                        <?php endif ?>
                        
                        <?php if (!empty($filter['price']['max'])): ?>
                        <div class="block clearfix">
                            <h3 class="title"><?php echo $this->translate('Price') ?></h3>
                            <div class="separator-2"></div>
                            <?php
                                $slideValue = $filter['price']['min'] . ',' . $filter['price']['max'];
                                if ($priceFrom !== '' && $priceTo !== '') {
                                    $slideValue = db_float($priceFrom) . ',' . db_float($priceTo);
                                }
                                echo $this->sliderHelper(
                                    'price-range', 
                                    'price_from', 
                                    'price_to',
                                    $filter['price']['min'],
                                    $filter['price']['max'],
                                    '5000',
                                    $slideValue
                                );
                            ?>                                                   
                        </div>
                        <?php endif ?>
                        
                    </div>
                </form>
            </div>
			<div class="col-md-9">                
				
				<div class="tab-content clear-style">
					<div class="tab-pane active" id="pill-1">
						<div class="row masonry-grid-fitrows grid-space-10" style="position: relative; height: 1082.02px;">
                        <?php                         
                            $locales = \Application\Module::getConfig('general.locales');
                            $request = $this->requestHelper();    
                            $products = !empty($result['data']) ? $result['data'] : array();
                            $limit = !empty($result['limit']) ? $result['limit'] : 10;
                            $count = !empty($result['count']) ? $result['count'] : 0; 
                            if (!empty($products)) {
                                foreach ($products as $product) {
                                    echo $this->productItemHelper($product);                                                                                                                    
                                }
                            } else {
                                echo "<center class=\"not-found\">{$this->translate('Catelog is importing')}</center>";
                            }
                        ?>   
						</div>
					</div>
                    <!-- pills end -->
                    <!-- pagination start -->
                    <nav class="text-center">
                        <?php   
                            if ($count > $limit) {
                                echo $this->paginatorHelper(
                                    $params, 
                                    $count, 
                                    $limit,
                                    Web\Module::getConfig('display_page')
                                );
                            }
                        ?>
                    </nav>                    
				</div>
				<!-- pills end -->
			</div>
		</div>
	</div>
</section>
<!-- section end -->