<?php
//if (!($controller == 'productorders' && $action == 'add')) {
    $cartItems = Application\Lib\Cart::get();
    $totalQuantity = 0;
    $totalMoney = 0;
    if (!empty($cartItems)) {    
        foreach ($cartItems as $item) {
            $totalQuantity += $item['quantity'];
            $totalMoney += $item['quantity'] * $item['price'];
        }
    }
//}
?>
<header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>CMS</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>CMS</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">                
                <li class="dropdown messages-menu" id="dropdown-cart"> 
                    <?php if (!empty($cartItems)) : ?>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-fw fa-cart-plus"></i>
                        <span class="label label-success total-quantity"><span><?php echo $totalQuantity ?></span></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; min-height: 50px;"><ul class="menu" style="overflow: hidden; width: 100%; max-height: 400px;">
                                <?php foreach ($cartItems as $item) : ?>
                                <li class="cart-item-row-<?php echo $item['product_id']?>">
                                    <a href="#">
                                        <div class="pull-left">
                                            <img src="<?php echo $item['url_image']?>" class="img-circle" alt="<?php echo $item['name']?>">
                                        </div>
                                        <h4 title="<?php echo $item['name']?>">
                                            <?php echo truncate($item['name'], 30)?>
                                            <small
                                                title="<?php echo $this->translate('Delete')?>"
                                                class="ajax-submit"
                                                data-callback = "      
                                                    <?php echo "var _id = '{$item['_id']}'" ?>;
                                                    var li = btn.closest('li'); 
                                                    li.remove();
                                                    $('.total-quantity span').html(result.totalQuantity);
                                                    $('.total-money span').html(result.totalMoney);
                                                    if ($('#cartForm .form-table-row-'+_id).length > 0) {
                                                        $('#cartForm .form-table-row-'+_id).remove();
                                                    }
                                                "
                                                data-url="                                                
                                                <?php echo $this->url(
                                                        'admin/carts', 
                                                        array(
                                                            'action' => 'removeitem',
                                                            'id' => $item['_id']
                                                        ))
                                                ?>">
                                                <i class="fa fa-fw fa-remove"></i>
                                            </small>
                                        </h4>
                                        <p>
                                            <span class="cart-item-quantity-<?php echo $item['product_id']?>"><?php echo $item['quantity']?></span> 
                                            x 
                                            <span class="cart-item-price-<?php echo $item['product_id']?>"><?php echo app_money_format($item['price'])?></span> 
                                            = 
                                            <span class="cart-item-total-money-<?php echo $item['product_id']?>"><?php echo app_money_format($item['quantity'] * $item['price'])?></span>
                                        </p>
                                    </a>
                                </li>
                                <?php endforeach ?>                                
                            </div>  
                        </li>
                        <li class="footer total-money">
                            <?php echo $this->translate('Total')?>: <span><?php echo app_money_format($totalMoney)?></span>
                        </li>
                        <li class="footer add-order">
                            <a href="<?php echo $this->url('admin/productorders', array('action' => 'add'))?>"><i class="fa fa-fw fa-arrow-right"></i><?php echo $this->translate('Add Order')?></a>
                        </li>
                    </ul>
                    <?php endif ?>
                </li>
 
                <?php if ($AppUI) : ?>
                <!-- User Account: style can be found in dropdown.less -->
                <li>
                    <a target="_blank" href="http://vuongquocbalo.com/"/>Visit site</a> 
                </li>
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <?php if ($AppUI->url_image): ?>
                        <img src="<?php echo $AppUI->url_image;?>" class="user-image" alt="User Image">
                        <?php endif ?>
                        <span class="hidden-xs"><?php echo $AppUI->display_name;?></span>
                    </a>
                    <ul itemscope itemtype="http://schema.org/ItemList" class="dropdown-menu">                                            
                        <li itemprop="itemListElement" class="user-body">
                            <div class="col-xs-12 text-left">
                                <a itemprop="url" href="<?php echo $this->url('admin/admins', array('action' => 'profile'))?>">
                                    <span itemprop="name"><?php echo $this->translate('Profile')?></span>
                                </a>
                            </div>                                                      
                            <div class="col-xs-12 text-left">
                                <a itemprop="url" href="<?php echo $this->url('admin/websites', array('action' => 'profile'))?>">
                                    <span itemprop="name"><?php echo $this->translate('Website Profile')?></span>
                                </a>
                            </div>                                          
                            <div class="col-xs-12 text-left">
                                <a itemprop="url" href="<?php echo $this->url('admin/admins', array('action' => 'profile'), array('query' => array('tab' => 'password')))?>"><?php echo $this->translate('Change password')?></a>
                            </div>
                            <div class="col-xs-12 text-left">
                                <a itemprop="url" href="<?php echo $this->url('admin/page', array('action' => 'logout'))?>">
                                    <span itemprop="name"><?php echo $this->translate('Sign out')?></span>
                                </a>
                            </div>
                        </li>                                            
                    </ul>
                </li>
                <?php endif; ?>
            </ul>
        </div>
    </nav>
</header>