<section class="main-container">
    <div class="container">
        <div class="row">
            <div class="main col-md-6 col-md-offset-3 pv-40">
                <h1 class="page-title"><span class="text-default">404</span></h1>
                <h2><?php echo $this->translate('Ooops! Page Not Found') ?></h2>
                <p><?php echo $this->translate('The requested URL was not found on this server. Make sure that the Web site address displayed in the address bar of your browser is spelled and formatted correctly') ?></p>
                <form id="searchForm404" role="search" action="/search">
                    <div class="form-group has-feedback">
                        <input id="keyword" name="q" type="text" class="form-control" placeholder="<?php echo $this->translate('Enter product name or brand name')?>">
                        <i class="fa fa-search form-control-feedback"></i>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>