<section class="main-container  jumbotron light-gray-bg text-center margin-clear">
    <div class="container">
        <div class="row">
            <div class="main col-md-6 col-md-offset-3 pv-40">
                <h1 class="page-title"><span class="text-default">500</span></h1>
                <h2><?php echo $this->translate('Ooops! System Error') ?></h2>
                <p>Tại thời điểm này, có một vấn đề nào đó không mong muốn đã xãy ra với hệ thống của chúng tôi, vui lòng đợi trong chút lát và nhấn F5 để thử lại</p>
                <form id="searchForm404" role="search" action="/search">
                    <div class="form-group has-feedback">
                        <input id="keyword" name="q" type="text" class="form-control" placeholder="<?php echo $this->translate('Enter product name or brand name')?>">
                        <i class="fa fa-search form-control-feedback"></i>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>