<div id="page-start"></div>
<!-- section start -->
<!-- ================ -->
<section class="section light-gray-bg clearfix">
	<div class="container">        
            
			<div class="col-md-12">
                
				<div class="tab-content clear-style">
					<div class="tab-pane active">
						<div class="row masonry-grid-fitrows grid-space-10" style="position: relative;">
                        <?php  
                            $locales = \Application\Module::getConfig('general.locales');
                            $request = $this->requestHelper();    
                            $products = !empty($result['data']) ? $result['data'] : array();
                            $limit = !empty($result['limit']) ? $result['limit'] : 20;
                            $count = !empty($result['count']) ? $result['count'] : 0;                       
                            if (!empty($products)) {
                                foreach ($products as $product) {
                                    echo $this->productItemHelper($product, 4);                                                                                                                    
                                }
                            } else {
                                echo "<center class=\"not-found\">{$this->translate('Product not found')}</center>";
                            }
                        ?>  
						</div>
					</div>
                    <!-- pagination start -->
                    <nav class="text-center">
                        <?php   
                            if ($count > $limit) {
                                echo $this->paginatorHelper(
                                    $params, 
                                    $count, 
                                    $limit
                                );
                            }
                        ?>
                    </nav>
                </div>
                
			</div>
		</div>
	</div>
</section>
<!-- section end -->

<!-- section start -->
<!-- ================ -->
<!--
<section class="section dark-translucent-bg background-img-2" style="background-position: 50% 52%;">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="call-to-action text-center">
					<div class="row">
						<div class="col-sm-8">
							<h1 class="title">Don't Miss Out Our Offers</h1>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem quasi explicabo consequatur consectetur, a atque voluptate officiis eligendi nostrum.</p>
						</div>
						<div class="col-sm-4">
							<br>
							<p><a href="/" class="btn btn-lg btn-default btn-animated">Learn More<i class="fa fa-arrow-right pl-20"></i></a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
-->
<!-- section end -->