<!-- breadcrumb start -->
<!-- ================ -->
<div class="breadcrumb-container">
    <div class="container">
        <ol class="breadcrumb">
            <li><i class="fa fa-home pr-10"></i><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/index.html">Home</a></li>
            <li class="active">Checkout Payment</li>
        </ol>
    </div>
</div>
<!-- breadcrumb end -->

<!-- main-container start -->
<!-- ================ -->
<section class="main-container">

    <div class="container">
        <div class="row">

            <!-- main start -->
            <!-- ================ -->
            <div class="main col-md-12">

                <!-- page-title start -->
                <!-- ================ -->
                <h1 class="page-title">Checkout Payment</h1>
                <div class="separator-2"></div>
                <!-- page-title end -->

                <fieldset>
                    <legend>Payment</legend>
                    <form role="form" class="form-horizontal" id="payment-information">
                        <div class="row">
                            <div class="col-lg-3">
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked="">
                                        Credit Card<i class="fa fa-cc-visa pl-10"></i><i class="fa fa-cc-amex pl-10"></i><i class="fa fa-cc-mastercard pl-10"></i>
                                    </label>
                                </div>
                                <div class="space-bottom"></div>
                            </div>
                            <div class="col-lg-9">
                                <div class="form-group">
                                    <label for="paymentFirstName" class="col-md-3 control-label">First Name<small class="text-default">*</small></label>
                                    <div class="col-md-9">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <input type="text" class="form-control" id="paymentFirstName" value="First Name">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="paymentLastName" class="col-md-3 control-label">Last Name<small class="text-default">*</small></label>
                                    <div class="col-md-9">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <input type="text" class="form-control" id="paymentLastName" value="Last Name">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-3 control-label">Credit Card<small class="text-default">*</small></label>
                                    <div class="col-md-9">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <select class="form-control">
                                                    <option value="visa" selected="selected">VISA</option>
                                                    <option value="master-card">Master Card</option>
                                                    <option value="american-express">American Express</option>
                                                </select>															
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-3 control-label">Card Number<small class="text-default">*</small></label>
                                    <div class="col-md-9">
                                        <div class="row">
                                            <div class="col-xs-6 col-sm-2">
                                                <input type="text" class="form-control">
                                            </div>
                                            <div class="col-xs-6 col-sm-2">
                                                <input type="text" class="form-control">
                                            </div>
                                            <div class="clearfix space-bottom visible-xs"></div>
                                            <div class="col-xs-6 col-sm-2">
                                                <input type="text" class="form-control">
                                            </div>
                                            <div class="col-xs-6 col-sm-2">
                                                <input type="text" class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-3 control-label">Expiration Date<small class="text-default">*</small></label>
                                    <div class="col-md-9">
                                        <div class="row">
                                            <div class="col-xs-6 col-sm-2">
                                                <select class="form-control">
                                                    <option value="01" selected="selected">01</option>
                                                    <option value="03">02</option>
                                                    <option value="03">03</option>
                                                    <option value="04">04</option>
                                                    <option value="05">05</option>
                                                    <option value="06">06</option>
                                                    <option value="07">07</option>
                                                    <option value="08">08</option>
                                                    <option value="09">09</option>
                                                    <option value="10">10</option>
                                                    <option value="11">11</option>
                                                    <option value="12">12</option>
                                                </select>
                                            </div>
                                            <div class="col-xs-6 col-sm-2">
                                                <select class="form-control">
                                                    <option value="2014" selected="selected">2014</option>
                                                    <option value="2015">2015</option>
                                                    <option value="2016">2016</option>
                                                    <option value="2017">2017</option>
                                                    <option value="2018">2018</option>
                                                    <option value="2019">2019</option>
                                                    <option value="2020">2020</option>
                                                    <option value="2021">2021</option>
                                                    <option value="2022">2022</option>
                                                    <option value="2023">2023</option>
                                                    <option value="2024">2024</option>
                                                    <option value="2025">2025</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-3 control-label">CVS<small class="text-default">*</small></label>
                                    <div class="col-md-9">
                                        <div class="row">
                                            <div class="col-xs-6 col-sm-2">
                                                <input type="text" class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="space"></div>
                        <div class="row">
                            <div class="col-lg-3">
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
                                        Paypal<i class="fa fa-cc-paypal pl-10"></i>
                                    </label>
                                </div>
                                <div class="space-bottom"></div>
                            </div>
                            <div class="col-lg-9">
                                <div class="form-group">
                                    <label for="paymentEmail" class="col-md-3 control-label">Email<small class="text-default">*</small></label>
                                    <div class="col-md-9">
                                        <div class="row">
                                            <div class="col-md-8">
                                                <input type="email" class="form-control" id="paymentEmail" value="Email">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="space"></div>
                        <div class="row">
                            <div class="col-lg-3">
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="optionsRadios" id="optionsRadios3" value="option3">
                                        Cash On Delivery
                                    </label>
                                </div>
                                <div class="space-bottom"></div>
                            </div>
                            <div class="col-lg-9">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. At, quo, non sint nisi, corrupti fuga qui quod autem totam, molestias reiciendis ex unde. Molestias, nostrum numquam, beatae totam esse ab.</p>
                            </div>
                        </div>
                    </form>
                </fieldset>
                <div class="text-right">	
                    <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-checkout.html" class="btn btn-group btn-default"><i class="icon-left-open-big"></i> Go Back</a>
                    <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-checkout-review.html" class="btn btn-group btn-default">Review and Complete Your Order <i class="icon-right-open-big"></i></a>
                </div>

            </div>
            <!-- main end -->

        </div>
    </div>
</section>
<!-- main-container end -->

<!-- section start -->
<!-- ================ -->
<section class="pv-30 dark-translucent-bg padding-bottom-clear" style="background-image:url(&#39;images/shop-banner.jpg&#39;);background-position: 50% 32%;">
    <div class="container">
        <div class="row grid-space-10">
            <div class="col-md-3 col-sm-6">
                <div class="pv-30 ph-20 feature-box text-center object-non-visible animated object-visible fadeInDownSmall" data-animation-effect="fadeInDownSmall" data-effect-delay="100">
                    <span class="icon default-bg"><i class="fa fa-diamond"></i></span>
                    <h3>Premium &amp; Guaranteed Quality</h3>
                    <div class="separator clearfix"></div>
                    <p>Voluptatem ad provident non repudiandae beatae cupiditate.</p>
                    <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/page-services.html" class="link-dark">Read More<i class="pl-5 fa fa-angle-double-right"></i></a>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="pv-30 ph-20 feature-box text-center object-non-visible animated object-visible fadeInDownSmall" data-animation-effect="fadeInDownSmall" data-effect-delay="150">
                    <span class="icon default-bg"><i class="icon-lock"></i></span>
                    <h3>Secure &amp; Safe Payment</h3>
                    <div class="separator clearfix"></div>
                    <p>Iure sequi unde hic. Sapiente quaerat sequi inventore.</p>
                    <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/page-services.html" class="link-dark">Read More<i class="pl-5 fa fa-angle-double-right"></i></a>
                </div>
            </div>
            <div class="clearfix visible-sm"></div>
            <div class="col-md-3 col-sm-6">
                <div class="pv-30 ph-20 feature-box text-center object-non-visible animated object-visible fadeInDownSmall" data-animation-effect="fadeInDownSmall" data-effect-delay="200">
                    <span class="icon default-bg"><i class="icon-globe"></i></span>
                    <h3 class="pl-10 pr-10">Free &amp; Fast Shipping</h3>
                    <div class="separator clearfix"></div>
                    <p>Inventore dolores aut laboriosam cum consequuntur.</p>
                    <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/page-services.html" class="link-dark">Read More<i class="pl-5 fa fa-angle-double-right"></i></a>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="pv-30 ph-20 feature-box text-center object-non-visible animated object-visible fadeInDownSmall" data-animation-effect="fadeInDownSmall" data-effect-delay="250">
                    <span class="icon default-bg"><i class="icon-thumbs-up"></i></span>
                    <h3>24/7 Customer Support</h3>
                    <div class="separator clearfix"></div>
                    <p>Inventore dolores aut laboriosam cum consequuntur.</p>
                    <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/page-services.html" class="link-dark">Read More<i class="pl-5 fa fa-angle-double-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- section end -->

<!-- section start -->
<!-- ================ -->
<section class="pv-30 clearfix">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="block clearfix">
                    <h3 class="title">Top Rated</h3>
                    <div class="separator-2"></div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-1.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Lorem ipsum dolor sit amet</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                            </p>
                            <p class="price">$99.00</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-2.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Eum repudiandae ipsam</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$299.00</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-3.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Quia aperiam velit fuga</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$9.99</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-4.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Fugit non natus officiis</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$399.00</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="block clearfix">
                    <h3 class="title">Related</h3>
                    <div class="separator-2"></div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-5.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Lorem ipsum dolor sit amet</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                            </p>
                            <p class="price">$99.00</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-6.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Eum repudiandae ipsam</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$299.00</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-7.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Quia aperiam velit fuga</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$9.99</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-8.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Fugit non natus officiis</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$399.00</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="block clearfix">
                    <h3 class="title">Best Sellers</h3>
                    <div class="separator-2"></div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-3.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Lorem ipsum dolor sit amet</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                            </p>
                            <p class="price">$99.00</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-5.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Eum repudiandae ipsam</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$299.00</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-7.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Quia aperiam velit fuga</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$9.99</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-1.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Fugit non natus officiis</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$399.00</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- section end -->