<!-- breadcrumb start -->
<!-- ================ -->
<div class="breadcrumb-container">
    <div class="container">
        <ol class="breadcrumb">
            <li><i class="fa fa-home pr-10"></i><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/index.html">Home</a></li>
            <li class="active">Checkout Review</li>
        </ol>
    </div>
</div>
<!-- breadcrumb end -->

<!-- main-container start -->
<!-- ================ -->
<section class="main-container">

    <div class="container">
        <div class="row">

            <!-- main start -->
            <!-- ================ -->
            <div class="main col-md-12">

                <!-- page-title start -->
                <!-- ================ -->
                <h1 class="page-title">Checkout Review</h1>
                <div class="separator-2"></div>
                <!-- page-title end -->

                <table class="table cart">
                    <thead>
                        <tr>
                            <th>Product </th>
                            <th>Price </th>
                            <th>Quantity</th>
                            <th class="amount">Total </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="product"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Product Title 1</a> <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas inventore modi.</small></td>
                            <td class="price">$99.50 </td>
                            <td class="quantity">
                                <div class="form-group">
                                    <input type="text" class="form-control" value="2" disabled="">
                                </div>											
                            </td>
                            <td class="amount">$199.00 </td>
                        </tr>
                        <tr>
                            <td class="product"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Product Title 2</a> <small>Quas inventore modi</small></td>
                            <td class="price"> $99.66 </td>
                            <td class="quantity">
                                <div class="form-group">
                                    <input type="text" class="form-control" value="3" disabled="">
                                </div>											
                            </td>
                            <td class="amount">$299.00 </td>
                        </tr>
                        <tr>
                            <td class="product"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Product Title 3</a> <small>Fugiat nemo enim officiis repellendus</small></td>
                            <td class="price"> $499.66 </td>
                            <td class="quantity">
                                <div class="form-group">
                                    <input type="text" class="form-control" value="3" disabled="">
                                </div>											
                            </td>
                            <td class="amount">$1499.00 </td>
                        </tr>
                        <tr>
                            <td class="total-quantity" colspan="3">Subtotal</td>
                            <td class="amount">$1997.00</td>
                        </tr>
                        <tr>										
                            <td class="total-quantity" colspan="2">Discount Coupon</td>
                            <td class="price">TheProject25672</td>
                            <td class="amount">-20%</td>
                        </tr>
                        <tr>
                            <td class="total-quantity" colspan="3">Total 8 Items</td>
                            <td class="total-amount">$1597.00</td>
                        </tr>
                    </tbody>
                </table>
                <div class="space-bottom"></div>
                <table class="table">
                    <thead>
                        <tr>
                            <th colspan="2">Billing Information </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Full Name</td>
                            <td class="information">John Doe </td>
                        </tr>
                        <tr>
                            <td>Email</td>
                            <td class="information">johndoe@mail.com </td>
                        </tr>
                        <tr>
                            <td>Telephone</td>
                            <td class="information">+00 123 123 1234</td>
                        </tr>
                        <tr>
                            <td>Address</td>
                            <td class="information">One infinity loop, 54100, United States</td>
                        </tr>
                        <tr>
                            <td>Additional Info</td>
                            <td class="information">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum accusamus pariatur odit neque.</td>
                        </tr>
                    </tbody>
                </table>
                <div class="space-bottom"></div>
                <table class="table">
                    <thead>
                        <tr>
                            <th colspan="2">Shipping Information </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Full Name</td>
                            <td class="information">John Doe </td>
                        </tr>
                        <tr>
                            <td>Email</td>
                            <td class="information">johndoe@mail.com </td>
                        </tr>
                        <tr>
                            <td>Telephone</td>
                            <td class="information">+00 123 123 1234</td>
                        </tr>
                        <tr>
                            <td>Address</td>
                            <td class="information">One infinity loop, 54100, United States</td>
                        </tr>
                    </tbody>
                </table>
                <div class="space-bottom"></div>
                <table class="table">
                    <thead>
                        <tr>
                            <th colspan="2">Payment </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Credit Card</td>
                            <td class="information">Visa ***917 </td>
                        </tr>
                    </tbody>
                </table>
                <div class="text-right">	
                    <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-checkout-payment.html" class="btn btn-group btn-default"><i class="icon-left-open-big"></i> Go Back</a>
                    <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-checkout-completed.html" class="btn btn-group btn-default"><i class="icon-check"></i> Complete Your Order</a>
                </div>

            </div>
            <!-- main end -->

        </div>
    </div>
</section>
<!-- main-container end -->

<!-- section start -->
<!-- ================ -->
<section class="pv-30 dark-translucent-bg padding-bottom-clear" style="background-image:url(&#39;images/shop-banner.jpg&#39;);background-position: 50% 32%;">
    <div class="container">
        <div class="row grid-space-10">
            <div class="col-md-3 col-sm-6">
                <div class="pv-30 ph-20 feature-box text-center object-non-visible animated object-visible fadeInDownSmall" data-animation-effect="fadeInDownSmall" data-effect-delay="100">
                    <span class="icon default-bg"><i class="fa fa-diamond"></i></span>
                    <h3>Premium &amp; Guaranteed Quality</h3>
                    <div class="separator clearfix"></div>
                    <p>Voluptatem ad provident non repudiandae beatae cupiditate.</p>
                    <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/page-services.html" class="link-dark">Read More<i class="pl-5 fa fa-angle-double-right"></i></a>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="pv-30 ph-20 feature-box text-center object-non-visible animated object-visible fadeInDownSmall" data-animation-effect="fadeInDownSmall" data-effect-delay="150">
                    <span class="icon default-bg"><i class="icon-lock"></i></span>
                    <h3>Secure &amp; Safe Payment</h3>
                    <div class="separator clearfix"></div>
                    <p>Iure sequi unde hic. Sapiente quaerat sequi inventore.</p>
                    <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/page-services.html" class="link-dark">Read More<i class="pl-5 fa fa-angle-double-right"></i></a>
                </div>
            </div>
            <div class="clearfix visible-sm"></div>
            <div class="col-md-3 col-sm-6">
                <div class="pv-30 ph-20 feature-box text-center object-non-visible animated object-visible fadeInDownSmall" data-animation-effect="fadeInDownSmall" data-effect-delay="200">
                    <span class="icon default-bg"><i class="icon-globe"></i></span>
                    <h3 class="pl-10 pr-10">Free &amp; Fast Shipping</h3>
                    <div class="separator clearfix"></div>
                    <p>Inventore dolores aut laboriosam cum consequuntur.</p>
                    <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/page-services.html" class="link-dark">Read More<i class="pl-5 fa fa-angle-double-right"></i></a>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="pv-30 ph-20 feature-box text-center object-non-visible animated object-visible fadeInDownSmall" data-animation-effect="fadeInDownSmall" data-effect-delay="250">
                    <span class="icon default-bg"><i class="icon-thumbs-up"></i></span>
                    <h3>24/7 Customer Support</h3>
                    <div class="separator clearfix"></div>
                    <p>Inventore dolores aut laboriosam cum consequuntur.</p>
                    <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/page-services.html" class="link-dark">Read More<i class="pl-5 fa fa-angle-double-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- section end -->

<!-- section start -->
<!-- ================ -->
<section class="pv-30 clearfix">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="block clearfix">
                    <h3 class="title">Top Rated</h3>
                    <div class="separator-2"></div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-1.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Lorem ipsum dolor sit amet</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                            </p>
                            <p class="price">$99.00</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-2.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Eum repudiandae ipsam</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$299.00</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-3.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Quia aperiam velit fuga</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$9.99</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-4.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Fugit non natus officiis</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$399.00</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="block clearfix">
                    <h3 class="title">Related</h3>
                    <div class="separator-2"></div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-5.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Lorem ipsum dolor sit amet</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                            </p>
                            <p class="price">$99.00</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-6.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Eum repudiandae ipsam</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$299.00</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-7.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Quia aperiam velit fuga</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$9.99</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-8.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Fugit non natus officiis</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$399.00</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="block clearfix">
                    <h3 class="title">Best Sellers</h3>
                    <div class="separator-2"></div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-3.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Lorem ipsum dolor sit amet</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                            </p>
                            <p class="price">$99.00</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-5.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Eum repudiandae ipsam</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$299.00</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-7.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Quia aperiam velit fuga</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$9.99</p>
                        </div>
                        <hr>
                    </div>
                    <div class="media margin-clear">
                        <div class="media-left">
                            <div class="overlay-container">
                                <img class="media-object" src="/web/images/product-1.jpg" alt="blog-thumb">
                                <a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html" class="overlay-link small"><i class="fa fa-link"></i></a>
                            </div>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/shop-product.html">Fugit non natus officiis</a></h6>
                            <p class="margin-clear">
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star text-default"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </p>
                            <p class="price">$399.00</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- section end -->