<?php
/**
 * Zend Framework (http://framework.zend.com/)
 *
 * @link      http://github.com/zendframework/ZendSkeletonApplication for the canonical source repository
 * @copyright Copyright (c) 2005-2015 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 */

return array(
    'api' => array(
        'base_uri' => 'http://api.ken.dev/',
        'oauth2_base_uri' => 'http://oauth2.ken.dev/',
        'timeout' => 30.0,
        'client_id' => 'testclient',
        'client_secret' => 'testpass',
        
        'url_categories_lists' => 'categories/lists',
        'url_categories_all' => 'categories/all',
        'url_categories_add' => 'categories/add',
        'url_categories_update' => 'categories/update',
        'url_categories_detail' => 'categories/detail',
        'url_categories_addupdatelocale' => 'categories/addupdatelocale',
		
        'url_validator_duplicateemail' => 'validator/duplicateemail',
        'url_locationcountries_all' => 'locationcountries/all',  
        'url_locationstates_all' => 'locationstates/all',  
        'url_locationcities_all' => 'locationcities/all',  
        'url_oauth2_token' => 'oauth2/token',        
        
        'url_images_add' => 'images/add',
        'url_images_detail' => array('images/detail', 'get'),
        'url_images_all' => array('images/all', 'get'),
        
		'url_services_lists' => 'services/lists',
        'url_services_add' => 'services/add',
        'url_services_update' => 'services/update',
        'url_services_updateiseq' => 'services/updateiseq',
        'url_services_delete' => 'services/delete',
        'url_services_detail' => 'services/detail',
        'url_hotels_lists' => 'hotels/lists',
        'url_hotels_add' => 'hotels/add',
        'url_hotels_update' => 'hotels/update',
        'url_hotels_delete' => 'hotels/delete',
        'url_hotels_detail' => 'hotels/detail',
        
        'url_users_lists' => 'users/lists',
        'url_users_add' => 'users/add',        
        'url_users_update' => 'users/update',
        'url_users_addupdatelocale' => 'users/addupdatelocale',
        'url_users_detail' => 'users/detail',
        'url_users_login' => 'users/login',
        'url_users_getlogin' => 'users/getlogin',
        'url_users_register' => 'users/register',
        'url_users_onoff' => 'users/onoff',
        'url_users_all' => 'users/all',
        'url_users_search' => 'users/search',
        'url_users_fblogin' => 'users/fblogin',
        'url_users_checklogin' => 'users/checklogin',
        'url_users_updatepassword' => 'users/updatepassword',

        'url_place_categories_lists' => 'placecategories/lists',
        'url_place_categories_all' => 'placecategories/all',
        'url_place_categories_add' => 'placecategories/add',
        'url_place_categories_update' => 'placecategories/update',
        'url_place_categories_detail' => 'placecategories/detail',
        'url_place_categories_addupdatelocale' => 'placecategories/addupdatelocale',
        'url_place_categories_updateiseq' => 'placecategories/updateiseq',

        'url_news_categories_lists' => 'newscategories/lists',
        'url_news_categories_all' => 'newscategories/all',
        'url_news_categories_add' => 'newscategories/add',
        'url_news_categories_update' => 'newscategories/update',
        'url_news_categories_detail' => 'newscategories/detail',
        'url_news_categories_addupdatelocale' => 'newscategories/addupdatelocale',
        'url_news_categories_updatesort' => 'newscategories/updatesort',
        'url_news_categories_onoff' => 'newscategories/onoff',
                
        'url_news_lists' => 'news/lists',
        'url_news_all' => 'news/all',
        'url_news_add' => 'news/add',
        'url_news_update' => 'news/update',
        'url_news_detail' => 'news/detail',        
        'url_news_onoff' => 'news/onoff',
        
        'url_website_categories_lists' => 'websitecategories/lists',
        'url_website_categories_all' => 'websitecategories/all',
        'url_website_categories_add' => 'websitecategories/add',
        'url_website_categories_update' => 'websitecategories/update',
        'url_website_categories_detail' => 'websitecategories/detail',
        'url_website_categories_addupdatelocale' => 'websitecategories/addupdatelocale',
        'url_website_categories_updatesort' => 'websitecategories/updatesort',
        'url_website_categories_onoff' => 'websitecategories/onoff',
        
        'url_websites_lists' => 'websites/lists',
        'url_websites_all' => 'websites/all',
        'url_websites_add' => 'websites/add',
        'url_websites_update' => 'websites/update',
        'url_websites_detail' => 'websites/detail',
        'url_websites_addupdatelocale' => 'websites/addupdatelocale',
        'url_websites_updatesort' => 'websites/updatesort',
        'url_websites_onoff' => 'websites/onoff',
        
        'url_admins_lists' => 'admins/lists',
        'url_admins_all' => 'admins/all',
        'url_admins_add' => 'admins/add',
        'url_admins_update' => 'admins/update',
        'url_admins_detail' => 'admins/detail',
        'url_admins_onoff' => 'admins/onoff',
        'url_admins_updatepassword' => 'admins/updatepassword',
        'url_admins_login' => 'admins/login',
        
        'url_inputfields_lists' => 'inputfields/lists',
        'url_inputfields_all' => 'inputfields/all',
        'url_inputfields_add' => 'inputfields/add',
        'url_inputfields_update' => 'inputfields/update',
        'url_inputfields_detail' => 'inputfields/detail',
        'url_inputfields_onoff' => 'inputfields/onoff',
        'url_inputfields_updatesort' => 'inputfields/updatesort',
        'url_inputfields_addupdatelocale' => 'inputfields/addupdatelocale',
        'url_inputfields_save' => 'inputfields/save',
        
        'url_inputoptions_lists' => 'inputoptions/lists',
        'url_inputoptions_all' => 'inputoptions/all',
        'url_inputoptions_add' => 'inputoptions/add',
        'url_inputoptions_update' => 'inputoptions/update',
        'url_inputoptions_detail' => 'inputoptions/detail',
        'url_inputoptions_onoff' => 'inputoptions/onoff',
        'url_inputoptions_updatesort' => 'inputoptions/updatesort',
        'url_inputoptions_addupdatelocale' => 'inputoptions/addupdatelocale',
        'url_inputoptions_save' => 'inputoptions/save',
        
        'url_productcategories_lists' => 'productcategories/lists',
        'url_productcategories_all' => 'productcategories/all',
        'url_productcategories_add' => 'productcategories/add',
        'url_productcategories_update' => 'productcategories/update',
        'url_productcategories_detail' => 'productcategories/detail',
        'url_productcategories_addupdatelocale' => 'productcategories/addupdatelocale',
        'url_productcategories_updatesort' => 'productcategories/updatesort',
        'url_productcategories_onoff' => 'productcategories/onoff',
        'url_productcategories_addfield' => 'productcategories/addfield',
        'url_productcategories_allbrand' => 'productcategories/allbrand',
        'url_productcategories_filter' => 'productcategories/filter',
        
        'url_productsizes_lists' => 'productsizes/lists',
        'url_productsizes_all' => 'productsizes/all',
        'url_productsizes_add' => 'productsizes/add',
        'url_productsizes_update' => 'productsizes/update',
        'url_productsizes_detail' => 'productsizes/detail',
        'url_productsizes_addupdatelocale' => 'productsizes/addupdatelocale',
        'url_productsizes_updatesort' => 'productsizes/updatesort',
        'url_productsizes_onoff' => 'productsizes/onoff',        
        
        'url_products_lists' => array('products/lists', 'get'),
        'url_products_all' => array('products/all', 'get'),
        'url_products_add' => 'products/add',
        'url_products_update' => 'products/update',
        'url_products_detail' => array('products/detail', 'get'),
        'url_products_addupdatelocale' => 'products/addupdatelocale',
        'url_products_updatesort' => 'products/updatesort',
        'url_products_onoff' => 'products/onoff',
        'url_products_saveattribute' => 'products/saveattribute',
        'url_products_search' => 'products/search',
        
        'url_products_reviews_add' => 'productreviews/add',
        'url_products_reviews_lists' => 'productreviews/lists',
        'url_products_reviews_all' => 'productreviews/all',
		
        'url_products_addfeatured' => 'products/addfeatured',
        'url_products_removefeatured' => 'products/removefeatured',
        'url_products_updatesortfeatured' => 'products/updatesortfeatured',
		
		'url_products_addtopseller' => 'products/addtopseller',
        'url_products_removetopseller' => 'products/removetopseller',
        'url_products_updatesorttopseller' => 'products/updatesorttopseller',
		
		'url_products_homepage' => 'products/homepage',
		'url_products_addlatestarrival' => 'products/addlatestarrival',
        'url_products_removelatestarrival' => 'products/removelatestarrival',
        'url_products_updatesortlatestarrival' => 'products/updatesortlatestarrival',
		      
        'url_brands_lists' => 'brands/lists',
        'url_brands_all' => 'brands/all',
        'url_brands_add' => 'brands/add',
        'url_brands_update' => 'brands/update',
        'url_brands_detail' => 'brands/detail',
        'url_brands_addupdatelocale' => 'brands/addupdatelocale',
        'url_brands_updatesort' => 'brands/updatesort',
        'url_brands_onoff' => 'brands/onoff',
        
        'url_addresses_lists' => 'addresses/lists',
        'url_addresses_all' => 'addresses/all',
        'url_addresses_add' => 'addresses/add',
        'url_addresses_update' => 'addresses/update',
        'url_addresses_detail' => 'addresses/detail',
        'url_addresses_updatesort' => 'addresses/updatesort',
        'url_addresses_onoff' => 'addresses/onoff',
        
        'url_productorders_lists' => 'productorders/lists',
        'url_productorders_all' => 'productorders/all',
        'url_productorders_add' => 'productorders/add',
        'url_productorders_update' => 'productorders/update',
        'url_productorders_detail' => 'productorders/detail',
        'url_productorders_savedetail' => 'productorders/savedetail',
        'url_productorders_addproduct' => 'productorders/addproduct',
        'url_productorders_onoffproduct' => 'productorders/onoffproduct',
        'url_productorders_onoff' => 'productorders/onoff',
		
		'url_banners_lists' => 'banners/lists',
        'url_banners_all' => 'banners/all',
        'url_banners_add' => 'banners/add',
        'url_banners_update' => 'banners/update',
        'url_banners_detail' => 'banners/detail',
        'url_banners_addupdatelocale' => 'banners/addupdatelocale',
        'url_banners_updatesort' => 'banners/updatesort',
        'url_banners_onoff' => 'banners/onoff',
        
        'url_menus_lists' => 'menus/lists',
        'url_menus_all' => 'menus/all',
        'url_menus_add' => 'menus/add',
        'url_menus_update' => 'menus/update',
        'url_menus_detail' => 'menus/detail',
        'url_menus_addupdatelocale' => 'menus/addupdatelocale',
        'url_menus_updatesort' => 'menus/updatesort',
        'url_menus_onoff' => 'menus/onoff',
        
        'url_pages_lists' => 'pages/lists',
        'url_pages_all' => 'pages/all',
        'url_pages_add' => 'pages/add',
        'url_pages_update' => 'pages/update',
        'url_pages_detail' => 'pages/detail',
        'url_pages_addupdatelocale' => 'pages/addupdatelocale',
        'url_pages_updatesort' => 'pages/updatesort',
        'url_pages_onoff' => 'pages/onoff',
		
	    'url_contacts_lists' => 'contacts/lists',
        'url_contacts_all' => 'contacts/all',
        'url_contacts_add' => 'contacts/add',
        'url_contacts_update' => 'contacts/update',
        'url_contacts_detail' => 'contacts/detail',       
        'url_contacts_onoff' => 'contacts/onoff',
		
		'url_urlids_detail' => 'urlids/detail',
		
		'url_blocks_lists' => 'blocks/lists',
        'url_blocks_all' => 'blocks/all',
        'url_blocks_add' => 'blocks/add',
        'url_blocks_update' => 'blocks/update',
        'url_blocks_detail' => 'blocks/detail',       
        'url_blocks_onoff' => 'blocks/onoff',
		'url_blocks_addproduct' => 'blocks/addproduct',
		'url_blocks_removeproduct' => 'blocks/removeproduct',
		'url_blocks_updatesortproduct' => 'blocks/updatesortproduct',
		'url_blocks_updatesort' => 'blocks/updatesort',		
    ),
);
