<div class="row">
    <div class="col-xs-12"> 
        <div class="box box-primary collapsed-box">
            <div class="box-header" data-toggle="" title="" data-original-title="Header tooltip">
                <h3 class="box-title"><?php echo $this->translate('Basic information') ?></h3>
                <div class="box-tools pull-right">
                    <button class="btn btn-primary btn-xs search-collapse" data-widget="collapse"><i class="fa fa-plus"></i></button>
                </div>
            </div>  
            <div class="box-body" style="display: none;">
                <?php                
                    echo $this->htmlForm($form);            
                ?>           
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">       
        <div class="box box-primary">
            <div class="box-body">
                <?php                
                    echo $this->htmlForm($localeForm);            
                ?>           
            </div>
        </div>
    </div>
</div>