<?php  
    $locales = \Application\Module::getConfig('general.locales');
    $request = $this->requestHelper();    
    $products = !empty($result['data']) ? $result['data'] : array();
    $limit = !empty($result['limit']) ? $result['limit'] : 10;
    $count = !empty($result['count']) ? $result['count'] : 0;    
?>
<div class="row">
    <div class="col-md-10">
        <div class="box box-widget">
            <div class="box-body no-padding products">          
            <?php
                if (!empty($products)) {
                    foreach ($products as $product) {
                        $product['url'] = $this->url(
                            'admin/products', 
                            array(
                                'action' => 'detail',
                                'id' => $product['_id']
                            )
                        );
                        $product['url_add_to_cart'] = $this->url(
                            'admin/carts', 
                            array(
                                'action' => 'additem',
                                'id' => $product['_id']
                            )
                        );                            
                        $product['original_price'] = !empty($product['original_price']) ? money_format($product['original_price']) : '';
                        $product['price'] = money_format($product['price']);
                        $product['name'] = truncate($product['short'], 60);
                        $product['short'] = truncate($product['short'], 80);                    
                        echo "
                            <div class=\"item  col-xs-4 col-lg-4\">
                                <div class=\"thumbnail\">
                                    <div class=\"image\">
                                        <a href=\"{$product['url']}\">
                                            <img class=\"group list-group-image\" src=\"{$product['url_image']}\" alt=\"\" />
                                        </a>
                                    </div>
                                    <div class=\"caption\">
                                        <h4 class=\"group inner list-group-item-heading\">
                                            <a href=\"{$product['url']}\">{$product['name']}</a>
                                        </h4>
                                        <!--
                                        <p class=\"group inner list-group-item-text\">
                                            {$product['short']}
                                        </p>
                                        -->
                                        <div class=\"row\">
                                            <div class=\"col-xs-12 col-md-6\">                                                
                                                <div class=\"lead\">
                                                    <span class=\"original-price\">{$product['original_price']}</span>
                                                    <span class=\"price\">{$product['price']}</span>
                                                </div>
                                            </div>
                                            <div class=\"col-xs-12 col-md-6\">
                                                <p class=\"p-buy-now\">
                                                    <a  href=\"#\" 
                                                        class=\"btn btn-social btn-instagram ajax-submit\"
                                                        data-url=\"{$product['url_add_to_cart']}\"
                                                        data-callback=\"
                                                            loadCart(1);                                    
                                                            showMessage('{$this->translate('Added to cart')}')
                                                        \"><i class=\"fa fa-fw fa-cart-arrow-down\"></i> {$this->translate('Buy now')}
                                                    </a> 
                                                </p> 
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        ";                                                      
                    }
                }
            ?>          
            </div>
            <div class="box-footer clearfix">
            <?php   
                if ($count > $limit) {
                    echo $this->paginatorHelper(
                        $params, 
                        $count, 
                        $limit
                    );
                }
            ?>
            </div>
        </div>
    </div>
</div>