<?php echo $this->doctype(); ?>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" 
xmlns:og="http://opengraphprotocol.org/schema/" 
xmlns:fb="http://www.facebook.com/2008/fbml">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<?php 
            echo $this->headTitle()
                ->setSeparator(' - ')
                ->setAutoEscape(false);
            
            echo $this->headMeta();
            
            $stHost = Web\Module::getConfig('st_host');            
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
         ;?>
		<style>
			html, body {
				margin: 0;
				width: 100%;
				height: 100%;
			}

			#fullscreen {
				width: 100%;
				height: 100%;
				display: table;
				background-color: #0b0b0b;
                opacity: 0.7;
			}

			#fullscreen .fullscreen-content {
				display: table-cell;
				text-align: center;
				vertical-align: middle;
				padding: 0 100px;
			}
		</style>		
        <link rel="alternate" href="http://vuongquocbalo.com" hreflang="vi-vn" />
        <link rel="apple-touch-icon" sizes="57x57" href="/img/vuongquocbalo/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="/img/vuongquocbalo/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/img/vuongquocbalo/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="/img/vuongquocbalo/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="/img/vuongquocbalo/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="/img/vuongquocbalo/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="/img/vuongquocbalo/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="/img/vuongquocbalo/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="/img/vuongquocbalo/apple-icon-180x180.png">
        <link rel="icon" type="image/png" sizes="192x192"  href="/img/vuongquocbalo/android-icon-192x192.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/img/vuongquocbalo/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="/img/vuongquocbalo/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/img/vuongquocbalo/favicon-16x16.png">
        <link rel="manifest" href="/img/vuongquocbalo/manifest.json">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="/img/vuongquocbalo/ms-icon-144x144.png">
        <meta name="theme-color" content="#ffffff">
        <meta name="google-site-verification" content="V49mj8WBanjG1gsoEpA7m3WfQ0t1QO9yRBFd53QpxVs" />
		<?php echo Web\Module::getConfig('ga') ?>   
		
    </head>   
    
    <body class="wide" id="<?php echo "{$controller}_{$action}"?>">	
		<?php
			echo $this->content; 
		?> 
        <?php echo $this->inlineScript() ?>         
    </body>
</html>