<?php echo $this->doctype(); ?>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" 
xmlns:og="http://opengraphprotocol.org/schema/" 
xmlns:fb="http://www.facebook.com/2008/fbml">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<?php 
            echo $this->headTitle()
                ->setSeparator(' - ')
                ->setAutoEscape(false);
            
            echo $this->headMeta();
            
            $stHost = Web\Module::getConfig('st_host');            
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($stHost . ('/css/web.css'))  
                ->prependStylesheet($stHost . ('/plugins/notification/css/jquery_notification.css')) 
//                ->prependStylesheet($stHost . ('/css/magnific-popup.css'))   
//                ->prependStylesheet($stHost . ('/plugins/notification/css/jquery_notification.css')) 
//                ->prependStylesheet($stHost . ('/plugins/lightbox/jquery.lightbox-0.5.css')) 
//                ->prependStylesheet($stHost . ('/plugins/select2/select2.css'))  
//                ->prependStylesheet($stHost . ('/plugins/nivo-slider/themes/default/default.css'))  
//                ->prependStylesheet($stHost . ('/plugins/nivo-slider/nivo-slider.css'))  
//                ->prependStylesheet($stHost . ('/plugins/jquery-ui/jquery-ui.css'))  
//                ->prependStylesheet($stHost . ('/plugins/datepicker/datepicker3.css')) 
//                ->prependStylesheet($stHost . ('/plugins/timepicker/bootstrap-timepicker.css'))
//                ->prependStylesheet($stHost . ('/plugins/datatables/dataTables.bootstrap.css')) 
//                ->prependStylesheet($stHost . ('/css/style-switcher.css')) 
//                ->prependStylesheet($stHost . ('/css/light_blue.css')) 
//                ->prependStylesheet($stHost . ('/css/style.css')) 
//                ->prependStylesheet($stHost . ('/css/hover-min.css')) 
//                ->prependStylesheet($stHost . ('/css/owl.transitions.css'))   
//                ->prependStylesheet($stHost . ('/css/owl.carousel.css')) 
//                ->prependStylesheet($stHost . ('/css/animations.css')) 
//                ->prependStylesheet($stHost . ('/css/settings.css'))              
//                ->prependStylesheet($stHost . ('/css/magnific-popup.css'))     
//                ->prependStylesheet($stHost . ('/css/fontello.css'))                  
//                ->prependStylesheet($stHost . ('/css/font-awesome.css'))                  
//                ->prependStylesheet($stHost . ('/css/bootstrap.css'))               
//                ->prependStylesheet('//fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic')
//                ->prependStylesheet('//fonts.googleapis.com/css?family=Raleway:700,400,300')
//                ->prependStylesheet('//fonts.googleapis.com/css?family=Pacifico')
//                ->prependStylesheet('//fonts.googleapis.com/css?family=PT+Serif')
        ;?>
        <meta name="google-site-verification" content="V49mj8WBanjG1gsoEpA7m3WfQ0t1QO9yRBFd53QpxVs" />
        <?php echo Web\Module::getConfig('ga') ?> 
        <script>        
            var isMobile = <?php echo Application\Lib\Util::isMobile()?>;        
            var facebook_app_id = '<?php echo \Web\Module::getConfig('facebook_app_id')?>';        
        </script>
    </head>   
    
    <body class="wide <?php echo Application\Lib\Util::isMobile() ? 'body-mobile' : 'body-pc'?>" id="<?php echo "{$controller}_{$action}"?>">
	
		<!-- scrollToTop -->
		<!-- ================ -->		
		<div class="scrollToTop circle"><i class="icon-up-open-big"></i></div>
		
		<!-- page wrapper start -->
		<!-- ================ -->
		<div class="page-wrapper">
			<?php      
                echo $this->partial('web/header');
            ?>
			<?php 
                if (!in_array($controller, array('index', 'page'))) {
                    echo $this->navigation('web_navigation')                            
                                ->breadcrumbs()      
                                ->setLinkLast(true)  
                                ->setMinDepth(0)
                                ->setMaxDepth(10) 
                                ->setPartial('web/breadcrumb');   
                } 
            ?>
            <div class="container">
            <?php
				echo $this->flashMessenger()->renderCurrent('error', array('alert', 'alert-dismissible', 'alert-danger'));
				echo $this->flashMessenger()->renderCurrent('success', array('alert', 'alert-dismissible', 'alert-success'));
				$this->flashMessenger()->getPluginFlashMessenger()->clearCurrentMessagesFromNamespace('success');
				$this->flashMessenger()->getPluginFlashMessenger()->clearCurrentMessagesFromNamespace('error');
            ?>
            </div> 
            <?php
                echo $this->content; 
			?> 	
			<?php echo $this->partial('web/footer'); ?>  
		</div>
        
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($stHost . ('/js/main.js'))             
            ->prependFile($stHost . ('/plugins/notification/js/jquery_notification_v.1.js'))
            ->prependFile($stHost . ('/plugins/lazyload/jquery.lazyload.min.js'))  
            ->prependFile($stHost . ('/js/web.js'))
//                
//            ->prependFile($stHost . ('/plugins/lightbox/jquery.lightbox-0.5.js'))           
//            ->prependFile($stHost . ('/plugins/notification/js/jquery_notification_v.1.js'))
//            ->prependFile($stHost . ('/plugins/select2/select2.js'))
//            ->prependFile($stHost . ('/plugins/datepicker/bootstrap-datepicker.js'))    
//            ->prependFile($stHost . ('/plugins/timepicker/bootstrap-timepicker.js'))            
//            ->prependFile($stHost . ('/plugins/nivo-slider/jquery.nivo.slider.js'))
//            ->prependFile($stHost . ('/plugins/autoNumeric/autoNumeric.js'))
//            ->prependFile($stHost . ('/plugins/jquery-number/jquery.number.min.js'))
//            ->prependFile($stHost . ('/js/style-switcher.js')) 
//            ->prependFile($stHost . ('/js/template.js'))		
//            ->prependFile($stHost . ('/js/SmoothScroll.js')) 
//            ->prependFile($stHost . ('/js/jquery.browser.js')) 
//            ->prependFile($stHost . ('/js/owl.carousel.js')) 
//            ->prependFile($stHost . ('/js/jquery.vide.js'))
//            ->prependFile($stHost . ('/js/jquery.validate.js')) 
//            ->prependFile($stHost . ('/js/jquery.parallax-1.1.3.js')) 
//            ->prependFile($stHost . ('/js/jquery.countTo.js')) 
//            ->prependFile($stHost . ('/js/jquery.waypoints.min.js')) 
//            ->prependFile($stHost . ('/js/jquery.magnific-popup.min.js')) 
//            ->prependFile($stHost . ('/js/isotope.pkgd.min.js')) 
//            ->prependFile($stHost . ('/js/jquery.themepunch.revolution.min.js')) 
//            ->prependFile($stHost . ('/js/jquery.themepunch.tools.min.js')) 
//            ->prependFile($stHost . ('/js/modernizr.js')) 
//            ->prependFile($stHost . ('/js/bootstrap.min.js'))            
//            ->prependFile($stHost . ('/plugins/jquery-ui/jquery-ui.js'))  
//            ->prependFile($stHost . ('/js/jquery.min.js'))    
             
             
        ; ?>
        <?php echo $this->inlineScript() ?>         
        <?php echo Web\Module::getConfig('chat') ?>         
    </body>
</html>