<?php
    $website = $this->viewModel()->getRoot()->getVariable('website');
    $banners = $website['banners'];
    $categories = Web\Model\ProductCategories::getSubCategories($website['product_categories'], $lastLevel, 0, false);
    $featuredBrands = $website['brand_featureds'];
    $groupCategories = [
        'Thời Trang Nam' => [],
        'Thời Trang Nữ' => [],       
    ];
    foreach ($categories as $category) {
        if (in_array($category['category_id'], [50, 55, 59, 63, 64, 68, 71])) {
            $groupCategories['Thời Trang Nữ'][] = $category;
        } elseif (in_array($category['category_id'], [75, 79, 83, 87, 88])) {
            $groupCategories['Thời Trang Nam'][] = $category;
        } 
    }
?>
<div id="page-start"></div>
<!-- section start -->
<!-- ================ -->
<section class="light-gray-bg clearfix">
	<div class="container">        
        
        <div class="row">            
            <?php foreach ($blocks as $block) : ?> 
			<div class="col-md-12 mb-10">
                <?php if (!empty($block['products'])): ?> 
                <div class="nav nav-tabs style-1" role="tablist">
                    <div class="tab-title">
                        <?php echo $block['name'] ?>
                    </div>
                    <?php if (!empty($block['url'])): ?>
                    <div class="tab-more">
                        <a itemprop="url" href="<?php echo $block['url']?>" class="pull-right margin-clear btn btn-sm btn-default-transparent btn-animated">
                            <?php echo !empty($block['name_url']) ? $block['name_url'] : $this->translate('View more')?><i class="fa fa-chevron-circle-right"></i>
                        </a>
                    </div>
                    <?php endif ?>                   
                </div>
                
                <!-- Tab panes -->
				<div class="tab-content clear-style">
					<div class="tab-pane active">
						<div id="grid-4" class="row masonry-grid-fitrows grid-space-10" style="position: relative;">
                        <?php       
                            $products = $block['products'];
                            $locales = \Application\Module::getConfig('general.locales');
                            $request = $this->requestHelper(); 
                            if (!empty($products)) {
                                foreach ($products as $product) {
                                    $product['block_id'] = $block['block_id'];
                                    echo $this->productItemHelper($product, 4);                                                                                                                    
                                }
                            }
                        ?>  
						</div>
					</div>
                </div>
                <?php endif ?>                              
			</div>
            <?php endforeach ?>  
		</div>
	</div>
</section>
<!-- section end -->
<div id="dialog-modal" class="modal fade" role="dialog" aria-labelledby="largeModal" aria-hidden="true">
    <div class="modal-dialog modal-lg"><div class="modal-content"></div></div>
</div>