<table style='width: 100%'>
    <tbody>        
        <tr>
            <td>               
				Kính chào Quý khách <?php echo $data['name']?><br/><br/>
				Chân thành cảm ơn Quý khách đã trải nghiệm mua sắm tại <?php echo $website['url']?>.<br/>
				Chúng tôi hy vọng Quý khách hài lòng với trải nghiệm mua sắm tại <?php echo $website['url']?>.<br/>
				Vui lòng bấm vào liên kết <a href="<?php echo $new_password_url;?>"><?php echo $new_password_url;?></a> để thay đổi mật khẩu của bạn <br/>
            </td>           
        </tr>
		<tr>
            <td>            
				<br/>
				Đơn vị chủ quản: <?php echo !empty($website['company_name']) ? $website['company_name'] : $website['name']?><br/>
				<?php echo $website['address']?><br/>
				<?php echo $this->translate('Hotline')?>: <?php echo $website['phone']?><br/>
				Email: <?php echo $website['email']?><br/> 
				Website: <?php echo $website['url']?>	
            </td>           
        </tr>
    </tbody>
</table>