<?php
    $website = $this->viewModel()->getRoot()->getVariable('website');
    $hasColorAndSize = ((!empty($data['sizes']) && !empty($data['colors'])) ? 1 : 0);
?>
<section class="main-container">

    <div class="container">
        <div class="row">

            <!-- main start -->
            <!-- ================ -->
            <div class="main col-md-12">

                <div class="row detail-images">
                    <div class="col-md-4">                        
                        <div class="tab-content clear-style">
                            <div class="tab-pane active" id="pill-1">
								<?php if (!empty($data['images'])): ?>
                                <div class="owl-carousel content-slider-with-large-controls">
									<?php foreach ($data['images'] as $image): ?>
                                    <div data-image="<?php echo $image['url_image']; ?>" class="overlay-container overlay-visible">
                                        <img src="<?php echo $image['url_image']; ?>" alt="<?php echo $data['name'] ?>">
                                        <a href="<?php echo $image['url_image']; ?>" class="popup-img overlay-link" title="<?php echo $data['name'] ?>"><i class="icon-plus-1"></i></a>
                                    </div>
									<?php endforeach ?>                                
                                </div>
								<?php endif ?>   
                                <?php
                                    $discount = '';
                                    if (!empty($data['discount_percent'])) {
                                        $discount = "<div class=\"discount-text\">-{$data['discount_percent']}%</div>";                        
                                    } elseif (!empty($data['discount_amount'])) {            
                                        $amount = app_money_format($data['discount_amount']);
                                        $discount = "<div class=\"discount-text\">-{$amount}%</div>";            
                                    }
                                    echo $discount;
                                ?>
                            </div>
                        </div>                      
                    </div>
                    <div itemscope itemtype="http://schema.org/Product" class="col-md-5">
                        <h2 itemprop="name"><?php echo $data['name'] ?></h2>                        
                        <?php if (!empty($data['code'])): ?>
                        <p class="code">
                            <span class="attribute-name"><?php echo $this->translate('SKU') ?>:</span>
                            <span itemprop="name" class="attribute-value"><?php echo $data['code']; ?></span>
                        </p>
                        <?php endif ?>
                        <?php
                            if (!empty($data['brand_id'])) {
                                $data['brand_url'] = $this->url(
                                    'web/products', 
                                    array(
                                        'name' => name_2_url($data['brand']['name'])
                                    )
                                );
                                echo "<p class=\"attribute brand\">";
                                echo "<span class=\"attribute-name\">" . $this->translate('Brand') . ":</span>";                                            
                                echo "<span itemprop=\"name\" class=\"attribute-value\"><a itemprop=\"url\" href=\"{$data['brand_url']}\">{$data['brand']['name']}</a></span>";                                            
                                echo "</p>";                                
                            }
                        ?>                                              
                        
                        <p itemprop="description"><?php echo nl2br($data['short']) ?></p>
                        
                        <form method="post" id="detailForm" novalidate="novalidate" role="form" class="clearfix">                           
                            <?php if (!empty($data['sizes']) || !empty($data['colors'])): ?>                                                        
                            <div class="row grid-space-10">
                                <?php if (!empty($data['colors'])): ?>
                                <div class="<?php echo $hasColorAndSize ? 'col-md-6' : 'col-md-12'?>">
                                    <div class="form-group">
                                        <label><?php echo $this->translate('Color') ?></label>
                                        <select name="color_id" id="productColor" class="form-control">
                                        <?php foreach ($data['colors'] as $color): ?>
                                            <option data-product_id="<?php echo $data['product_id'] ?>" data-image="<?php echo $color['url_image'] ?>" <?php if (!empty($color['is_main'])) echo "selected" ?> value="<?php echo $color['color_id'] ?>"><?php echo $color['name'] ?></option>
                                        <?php endforeach ?>
                                        </select>                                       
                                    </div>
                                </div>
                                <?php endif ?>
                                <?php if (!empty($data['sizes'])): ?>
                                <div class="<?php echo $hasColorAndSize ? 'col-md-6' : 'col-md-12'?>">
                                    <div class="form-group">
                                        <label><?php echo $this->translate('Size') ?></label>
                                        <select name="size_id" id="productSize" class="form-control">
                                        <?php foreach ($data['sizes'] as $size): ?>
                                            <option data-product_id="<?php echo $data['product_id'] ?>" data-price="<?php echo $size['price'] ?>" <?php if ($size['size_id'] == $data['default_size_id']) echo "selected" ?> value="<?php echo $size['size_id'] ?>"><?php echo $size['name'] ?></option>
                                        <?php endforeach ?>  
                                        </select>
                                    </div>
                                </div>
                                <?php endif ?>
                            </div>
                            <?php endif ?>
							<div class="detail-price light-gray-bg p-20 bordered clearfix">
                                <div itemprop="offers" itemscope itemtype="http://schema.org/Offer" class="product">                                
                                    <meta itemprop="priceCurrency" content="VND" />
									<i class="icon-tag pr-10"></i>
                                    <span id="productPrice" itemprop="price" class="price">
                                    <?php 
                                        if (!empty($data['price'])) {
                                            echo app_money_format($data['price'], false); 
                                        } else {
                                            echo $this->translate('Price contact');
                                        }                                    
                                    ?>
                                    </span>
									<span class="price">VND</span>
                                    <?php if ($data['price'] < $data['original_price']):?>
                                    <span id="originalPrice" class="original-price">
                                        <?php echo app_money_format($data['original_price'])?>
                                    </span>
                                    <?php endif?>
                                </div>
                                <div class="product elements-list pull-right clearfix">
                                    <?php if (!empty($data['available'])):?>
                                    <input 
                                        type="button" 
                                        value="<?php echo $this->translate('Add to cart') ?>" 
                                        data-url="<?php echo $this->url(
                                                'web/carts', 
                                                array(
                                                    'action' => 'additem',
                                                    'id' => $data['product_id']
                                                ))
                                        ?>"
                                        data-callback="	
                                            if (isMobile == 0) {
                                                loadCart(1);        
                                            } else {     
                                                alert('<?php echo $this->translate('Added to cart') ?>');
                                                $('#mCart .cart-count').html(parseInt($('#mCart .cart-count').html())+1);
                                                $('html, body').animate({scrollTop: 0}, 'slow');
                                            }
                                        "
                                        class="margin-clear btn btn-default ajax-submit">
                                    <?php else:?>
                                    <input type="button" class="margin-clear btn" value="Hết hàng" >
                                    <?php endif?>
                                </div>
                            </div>
						</form>
					</div>
                    <div class="col-md-3">
                        <div id="commitment_and_guide">    
                            <div class="commitment">   
                                <div class="title">Chính sách bán hàng</div>
                                <p>✓ Giao hàng TOÀN QUỐC <a target="_blank" href="http://thoitrang1.net/chinh-sach-ban-hang.html">Chính sách bán hàng</a></p>
                                <p>✓ Thanh toán khi nhận hàng</p>                                                            
                                <p>✓ Giao hàng từ <strong>2 - 3</strong> ngày</p>                               
                                <p>✓ Cam kết hàng giống hình</p>                                               
                                <p>✓ Hàng chính hãng, giá luôn thấp hơn thị trường</p>                                   
                            </div>
                            <div class="guide">  
                                <div class="title">Hướng Dẫn Mua Hàng</div>
                                <p>✓ Xem <a target="_blank" href="http://thoitrang1.net/huong-dan-mua-hang.html">Hướng dẫn mua hàng</a></p>                                             
                            </div>
                        </div>                         
                    </div>
                </div>
            </div>
            <!-- main end -->

        </div>
    </div>
</section>
<!-- main-container end -->

<!-- section start -->
<!-- ================ -->
<section class="">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs style-4" role="tablist">
                    <li class="active"><a href="#h2tab1" role="tab" data-toggle="tab"><i class="fa fa-files-o pr-5"></i>Mô tả <span itemprop="name"><?php echo $data['code']?></span></a></li>
                    <?php if (!empty($data['attributes'])):?>
                    <li><a href="#h2tab2" role="tab" data-toggle="tab"><i class="fa fa-info pr-5"></i>Thông tin <span itemprop="name"><?php echo $data['code']?></span></a></li>
                    <?php endif ?>
                    <?php if (!empty($data['more'])):?>
                    <li><a href="#h2tab4" role="tab" data-toggle="tab"><i class="fa fa-asterisk pr-5"></i>Về <span itemprop="name"><?php echo $data['code']?></span></a></li>
                    <?php endif ?>                   
                    <li><a href="#h2tab3" role="tab" data-toggle="tab"><i class="fa fa-star pr-5"></i><?php echo $this->translate('Reviews') ?> <span itemprop="name"><?php echo $data['code']?></span></a></li>                    
                </ul>
                <!-- Tab panes -->
                <div class="tab-content padding-top-clear padding-bottom-clear">
                    <div class="tab-pane fade in active" id="h2tab1">                                              
                        <div itemprop="description">
                            <?php echo $data['content']; ?>                            
                        </div>
                        
                        <?php if (!empty($data['brand']) && 1==0): ?> 
                        <div itemscope itemtype=\"http://schema.org/Brand\">
                            <h4 class="space-top"><?php echo $this->translate('Brand information') ?></h4><hr>
                            <div itemprop="description"><?php echo nl2br($data['brand']['short']) ?></div>                        
                        </div>
                        <?php endif ?>
                    </div>
                    <?php if (!empty($data['attributes'])): ?>
                    <div class="tab-pane fade in" id="h2tab2">                                              
                        <div itemprop="description">
                            <table class="table table-hover">								
								<tbody>
                                    <?php if (!empty($data['code'])): ?>
                                    <tr class="code">
                                        <td class="attribute-name"><?php echo $this->translate('SKU') ?></td>
                                        <td itemprop="name" class="attribute-value"><?php echo $data['code']; ?></td>
                                    </tr>
                                    <?php endif ?>  
                                    <?php                                        
                                        foreach ($data['attributes'] as $attribute) {
                                            if (!empty($attribute['value'])) {
                                                echo "<tr class=\"attribute\">";
                                                echo "<td class=\"attribute-name\">{$attribute['name']}</td>";                                            
                                                echo "<td itemprop=\"name\" class=\"attribute-value\">{$attribute['value']}</td>";                                            
                                                echo "</tr>";
                                            }
                                        }
                                    ?>									
								</tbody>
							</table>                            
                        </div>                       
                    </div>
                    <?php endif ?>
                    
                    <?php if (!empty($data['more'])): ?>
                    <div class="tab-pane fade in" id="h2tab4">                                              
                        <div itemprop="description">
                            <?php echo $data['more']?>
                        </div>
                    </div>
                    <?php endif ?>
                    
                    <div class="tab-pane fade" id="h2tab3">
                        <!-- comments start -->
						<?php if (!empty($data['product_reviews'])): ?>
                        <div itemscope itemtype="http://schema.org/Review" class="comments margin-clear space-top" id="review-list">
                            <!-- comment start -->
                            <?php                            
                                foreach ($data['product_reviews'] as $review) {
                                    $review['content'] = nl2br($review['content']);
                                    $time = app_datetime_format($review['created']);
                                    $rating = '';
                                    for ($star = 1; $star <= 5; $star++) {
                                        if ($review['rating'] >= $star) {
                                            $rating .= "<i class=\"fa fa-star text-default\"></i>"; 
                                        } else {
                                            $rating .= "<i class=\"fa fa-star\"></i>";
                                        }
                                    }
                                    echo "<div class=\"comment clearfix\">
                                        <!--
                                        <div class=\"comment-avatar\">
                                            <img class=\"img-circle\" src=\"/web/images/avatar.jpg\" alt=\"avatar\">
                                        </div>
                                        -->
                                        <header>
											<span itemprop=\"author\" itemscope itemtype=\"http://schema.org/Person\">
												<h3 itemprop=\"name\">{$review['name']}</h3>
                                            </span>
											<div itemprop=\"reviewRating\" itemscope itemtype=\"http://schema.org/Rating\" class=\"comment-meta\"> 
                                                <span itemprop=\"ratingValue\">{$rating}</span> | <span itemprop=\"datePublished\">{$time}</span>
                                            </div>
                                        </header>
                                        <div class=\"comment-content\">
                                            <div class=\"comment-body clearfix\">
                                                <p itemprop=\"reviewBody\">{$review['content']}</p>                                                
                                            </div>
                                        </div>
                                    </div>";
                                }                            
                            ?>                            
                            <!-- comment end -->
                        </div>
						<?php else: ?>
						<div class="comments margin-clear space-top" id="review-list"></div>
						<?php endif ?>
                        <!-- comments end -->

                        <!-- comments form start -->
                        <div class="comments-form">
                            <h2 class="title"><?php echo $this->translate('Add your Review') ?></h2>
                            <?php                
                                echo $this->htmlForm($reviewForm);                   
                            ?>                            
                        </div>
                        <!-- comments form end -->
                    </div>
                </div>
            </div>
             
            <!-- sidebar start -->
            <!-- ================ -->
            <aside class="col-md-4 col-lg-3 col-lg-offset-1">
                <div class="sidebar">
                    <div class="block clearfix">
                        <?php if (!empty($data['product_related'])) : ?>
                        <h3 class="title"><?php echo $this->translate('Related Products') ?></h3>
                        <div class="separator-2"></div>
                        <?php                         
                            $locales = \Application\Module::getConfig('general.locales');
                            $request = $this->requestHelper(); 
                            if (!empty($data['product_related'])) {
                                foreach ($data['product_related'] as $product) {
                                    $product['url'] = $this->url(
                                        'web/products', 
                                        array(
                                            'name' => name_2_url($product['name'])
                                        )
                                    );
                                    $product['original_price'] = !empty($product['original_price']) ? app_money_format($product['original_price']) : '';
                                    $product['price'] = app_money_format($product['price'], false);									
                                    $product['name'] = truncate($product['name'], 60);
                                    echo "
                                    <div itemscope itemtype=\"http://schema.org/Product\" class=\"media margin-clear\">
                                        <div class=\"media-left\">
                                            <div class=\"overlay-container\">
                                                <a itemprop=\"url\" href=\"{$product['url']}\" class=\"\">
                                                    <img itemprop=\"image\" 
                                                        alt=\"{$product['name']}\" 
                                                        class=\"media-object\" 
                                                        onerror=\"this.src='" . \Web\Module::getConfig('image_unavalable_url') . "'\"
                                                        src=\"{$product['url_image']}\">
                                                </a>
                                            </div>
                                        </div>
                                        <div class=\"media-body\">
                                            <h6 class=\"media-heading\"><a itemprop=\"url\" href=\"{$product['url']}\"><span itemprop=\"name\">{$product['name']}</span></a></a></h6>
                                            <p itemprop=\"offers\" itemscope itemtype=\"http://schema.org/Offer\">
												<meta itemprop=\"priceCurrency\" content=\"VND\" />
                                                <span itemprop=\"price\" class=\"price\">{$product['price']}</span><span class=\"price\">VND</span>
                                                <span class=\"original-price\">{$product['original_price']}</span>
                                            </p>
                                        </div>
                                        <hr>
                                    </div>";                                    
                                }
                                unset($product);
                            }
                        ?>                        
                        <?php endif ?>                       
                        
                    </div>
                </div>
            </aside>
            <!-- sidebar end -->

        </div>
    </div>
</section>
<!-- section end -->

