<div class="row">
    <div class="col-md-10">
        <div class="box box-solid">
            <div class="box-header">
                <h3 class="box-title product-name"><?php echo $data['name'] ?></h3>  
                <div class="box-tools pull-right">
                    <a href="/products/update/<?php echo $data['_id'] ?>"><i class="fa fa-fw fa-edit"></i></a>
                </div>
            </div>
            <div id="myBody" class="box-body">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="image-thumb">
                            <div class="image-thumb-inner">
                                <ul>
                                    <?php if (!empty($data['url_image'])) : ?>
                                    <li>
                                        <a href="<?php echo $data['url_image']; ?>"><img src="<?php echo $data['url_image']; ?>" /></a>
                                    </li>  
                                    <?php endif ?>
                                    <?php foreach ($data['images'] as $image): ?>
                                    <li>
                                        <a href="<?php echo $image['url_image']; ?>"><img src="<?php echo $image['url_image']; ?>" /></a>
                                    </li>
                                    <?php endforeach ?>
                                </ul>
                            </div>
                        </div>
                        <div class="image-view">
                            <div class="image-view-inner">
                                <?php if (!empty($data['url_image'])) : ?>
                                    <img src="<?php echo $data['url_image']; ?>" />
                                <?php endif ?>
                            </div>    
                        </div>    
                    </div>
                    <!-- /.col -->
                    <div class="col-sm-6">                       
                        <?php
                            if (!empty($data['categories'])) {
                                echo "<p class=\"attribute categories\">";
                                echo "<span class=\"attribute-name\">" . $this->translate('Product Category List') . ":</span>";                                            
                                echo "<span class=\"attribute-value\">";
                                foreach ($data['categories'] as $i => $category) {
                                    if ($i > 0) {
                                        echo ', ';
                                    }
                                    echo "<a href=\"/products?category_id={$category['category_id']}\">{$category['name']}</a>";                                                                                
                                }
                                echo "</span>";
                                echo "</p>";
                            }
                        ?>  
                        <?php
                            if (!empty($data['brand_id'])) {                                
                                echo "<p class=\"attribute brand\">";
                                echo "<span class=\"attribute-name\">" . $this->translate('Brand') . ":</span>";                                            
                                echo "<span class=\"attribute-value\"><a href=\"/products?brand_id={$data['brand_id']}\">{$data['brand']['name']}</a></span>";                                            
                                echo "</p>";                                
                            }
                        ?> 
                        <?php if (!empty($data['code'])): ?>
                        <p class="code">
                            <span class="attribute-name"><?php echo $this->translate('SKU') ?>:</span>
                            <span class="attribute-value"><?php echo $data['code']; ?></span>
                        </p>
                        <?php endif ?>
                        <?php if (!empty($data['model'])): ?>
                        <p class="code">
                            <span class="attribute-name"><?php echo $this->translate('Model') ?>:</span>
                            <span class="attribute-value"><?php echo $data['model']; ?></span>
                        </p>
                        <?php endif ?>                        
                        <?php if (!empty($data['warranty'])): ?>
                        <p class="warranty">
                            <span class="attribute-name"><?php echo $this->translate('Warranty') ?>:</span>
                            <span class="attribute-value"><?php echo $data['warranty']; ?></span>
                        </p>
                        <?php endif ?>
                        <?php if (!empty($data['weight'])): ?>
                        <p class="warranty">
                            <span class="attribute-name"><?php echo $this->translate('Weight (kg)') ?>:</span>
                            <span class="attribute-value"><?php echo $data['weight']; ?></span>
                        </p>
                        <?php endif ?>
                        <?php if (!empty($data['size'])): ?>
                        <p class="warranty">
                            <span class="attribute-name"><?php echo $this->translate('Size (depth x width x height cm)') ?>:</span>
                            <span class="attribute-value"><?php echo $data['size']; ?></span>
                        </p>
                        <?php endif ?>
                        <?php if (!empty($data['made_in'])): ?>
                        <p class="made-in">
                            <span class="attribute-name"><?php echo $this->translate('Made in') ?>:</span>
                            <span class="attribute-value"><?php echo $data['made_in']; ?></span>
                        </p>
                        <?php endif ?>
                        <?php
                            if (!empty($data['attributes'])) {
                                foreach ($data['attributes'] as $attribute) {
                                    if (!empty($attribute['options']['value_options']) 
                                        && !empty($attribute['value'])) {
                                        if (!is_array($attribute['value'])) {
                                            $attribute['value'] = array($attribute['value']);
                                        }
                                        $selectedValue = array();
                                        foreach ($attribute['options']['value_options'] as $valueId => $value) {
                                            if (in_array($valueId, $attribute['value'])) {
                                                $selectedValue[] = $value;
                                            }
                                        }
                                        echo "<p class=\"attribute\">";
                                        echo "<span class=\"attribute-name\">{$attribute['name']}:</span>";                                            
                                        echo "<span class=\"attribute-value\">" . implode(', ', $selectedValue) . "</span>";                                            
                                        echo "</p>";
                                    }
                                }
                            }
                        ?>   
                        <p class="text-price">
                            <span class="attribute-name"><?php echo $this->translate('Price') ?>:</span>
                            <span class="attribute-value">                                
                                <?php 
                                    if (!empty($data['price'])) {
                                        echo money_format($data['price']); 
                                    } else {
                                        echo $this->translate('Price contact');
                                    }                                    
                                ?>
                            </span>
                        </p>
                        <?php if (!empty($data['original_price'])): ?>
                        <p class="original-price">
                            <span class="attribute-name"><?php echo $this->translate('Original price') ?>:</span>
                            <span class="attribute-value"><?php echo money_format($data['original_price']); ?></span>
                        </p>
                        <?php endif ?>
                        <p class="p-buy-now">
                            <a class="btn btn-social btn-instagram ajax-submit"
                                href='#'                             
                                data-url="<?php echo $this->url(
                                        'admin/carts', 
                                        array(
                                            'action' => 'additem',
                                            'id' => $data['_id']
                                        ))
                                ?>"
                                data-callback="
                                    loadCart(1);                                    
                                    showMessage('<?php echo $this->translate('Added to cart') ?>')
                                "
                            >
                                <i class="fa fa-fw fa-cart-arrow-down"></i> <?php echo $this->translate('Add to cart') ?>
                            </a>                   
                        </p>
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>
<div class="row">
    <div class="col-md-10">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title"><?php echo $this->translate('Product description') ?></h3>           
            </div>
            <div class="box-body">
                <?php
                    echo $data['content'];
                ?>
            </div>
        </div>
    </div>
</div>
<?php if (!empty($data['brand'])): ?>
<div class="row">
    <div class="col-md-10">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title"><?php echo $this->translate('Brand') ?></h3>           
            </div>
            <div class="box-body">
                <div class="attachment-block clearfix">
                    <?php if (!empty($data['brand']['url_image'])): ?>
                    <a href="#" class="show-model" data-modelid="#brand-modal">
                        <img class="attachment-img" src="<?php echo $data['brand']['url_image'] ?>" alt="Attachment Image">
                    </a>
                    <?php endif ?>
                    <div class="attachment-pushed">
                        <h4 class="attachment-heading">
                            <a href="#" class="show-model" data-modelid="#brand-modal">
                                <?php echo $data['brand']['name'] ?>
                            </a>
                        </h4>
                        <div class="attachment-text">
                            <?php echo nl2br($data['brand']['short']) ?>
                        </div>                 
                    </div>               
                </div>
            </div>
        </div>
    </div>
</div>
<div id="brand-modal" class="modal fade" role="dialog" aria-labelledby="largeModal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">            
            <div class="modal-header">               
                <h4 class="modal-title" id="myModalLabel"><?php echo $data['brand']['name'] ?></h4>
            </div>          
            <div class="modal-body">
                <?php echo $data['brand']['about'] ?>
            </div>   
            <div class="modal-footer">
                <button type="button" class="btn pull-left" data-dismiss="modal"><?php echo $this->translate('Close') ?></button>
            </div>
        </div>
    </div>
</div>
<?php endif ?>