<div class="row">
    <div class="col-md-10">       
        <div class="box box-primary">
            <div class="box-body">
                <?php                
                    echo $this->htmlForm($form);                   
                ?>           
            </div>
        </div>
    </div>
</div>

<?php if (!empty($detailForm)) : ?>
<div class="row">
    <div class="col-md-10">
        <div class="box">            
            <div class="box-header" data-toggle="" title="" data-original-title="Header tooltip">
                <h3 class="box-title"><i class="fa fa-fw fa-cart-plus"></i>&nbsp;<?php echo $this->translate('Cart') ?></h3>
            </div>
            <div class="box-body" id="order-detail">
                <?php
                    echo $this->htmlListForm($detailForm);
                ?>                
            </div>
        </div>
    </div>
</div>
<?php endif ?>

