<?php
$request = $this->requestHelper();
if (empty($data['tax'])) {
    $data['tax'] = 0;
}
if (empty($data['shipping'])) {
    $data['shipping'] = 0;
}
?>
<div class="modal-header">               
    <h4 class="modal-title">
        <?php echo $this->translate('Order detail') ?>
        <a  href='#'
            style="margin-right: 5px;"
            data-dismiss='modal'
            class="pull-right">
            <i class="fa fa-close"></i>
        </a>  
    </h4>
</div>
<div class="modal-body">
    <section class="invoice">    

        <!-- info row -->
        <div class="row invoice-info">
            <div class="col-sm-6 invoice-col">
                <address>
                    <strong><?php echo !empty($data['user_name']) ? $data['user_name'] : '-'; ?></strong><br>
                    <?php echo !empty($data['address']) ? $data['address'] : '-'; ?><br>
                    <?php echo $this->translate('Mobile') ?>: <?php echo !empty($data['user_mobile']) ? $data['user_mobile'] : '-'; ?><br>
                    <?php echo $this->translate('Home phone') ?>: <?php echo !empty($data['user_phone']) ? $data['user_phone'] : '-'; ?><br>
                    <?php echo $this->translate('Email') ?>: <?php echo !empty($data['user_email']) ? $data['user_email'] : '-'; ?><br>
                </address>
            </div>
            <div class="col-sm-6 invoice-col">
                <b><?php echo $this->translate('Code') ?>:</b> <?php echo $data['code']; ?><br>

                <div class="status-date" <?php if ($data['status'] == 'cancel') echo 'style="display:none"' ?>>            

                    <b><?php echo $this->translate('Order date') ?>:</b> 
                    <span class="invoice-date order-date"><?php echo !empty($data['created']) ? datetime_format($data['created']) : '-'; ?></span><br>

                    <b><?php echo $this->translate('Shipping date') ?>:</b> 
                    <span class="invoice-date shipping-date"><?php echo !empty($data['shipping_date']) ? datetime_format($data['shipping_date']) : '-'; ?></span><br>
                                        
                    <b><?php echo $this->translate('Payment date') ?>:</b> 
                    <span class="invoice-date payment-date"><?php echo !empty($data['payment_date']) ? datetime_format($data['payment_date']) : '-'; ?></span><br>
                    
                    <b><?php echo $this->translate('Done date') ?>:</b> 
                    <span class="invoice-date done-date"><?php echo !empty($data['done_date']) ? datetime_format($data['done_date']) : '-'; ?></span><br>                    
                </div>

                <div class="status-cancel-date" <?php if ($data['status'] != 'cancel') echo 'style="display:none"' ?>>            
                    <b><?php echo $this->translate('Cancel date') ?>:</b> 
                    <span class="cancel-date"><?php echo !empty($data['cancel_date']) ? datetime_format($data['cancel_date']) : '-'; ?></span><br>
                </div>

                <b><?php echo $this->translate('Status') ?>:</b>             
                <span <?php if ($data['status'] == 'new') echo 'style="display:inline"' ?> class="btn btn-flat order-status new"><?php echo $this->translate('Processing'); ?></span>
                <span <?php if ($data['status'] == 'shipping') echo 'style="display:inline"' ?>class="btn btn-flat order-status shipping"><?php echo $this->translate('Shipping'); ?></span>               
                <span <?php if ($data['status'] == 'cancel') echo 'style="display:inline"' ?>class="btn btn-flat order-status cancel"><?php echo $this->translate('Cancel'); ?></span>
                <span <?php if ($data['status'] == 'done') echo 'style="display:inline"' ?>class="btn btn-flat order-status done"><?php echo $this->translate('Done'); ?></span>
                <br>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->

        <!-- Table row -->
        <?php if (!empty($data['products'])): ?>
        <div class="row">
            <div class="col-xs-12 table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th><?php echo $this->translate('Product name') ?></th>
                            <th><?php echo $this->translate('Quantity') ?></th>
                            <th><?php echo $this->translate('Price') ?></th>
                            <th><?php echo $this->translate('Subtotal') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($data['products'] as $product): ?>
                        <tr>
                            <td><?php echo $product['product_name']; ?></td>
                            <td><?php echo $product['quantity']; ?></td>                        
                            <td><?php echo money_format($product['price']); ?></td>                        
                            <td><?php echo money_format($product['total_money']); ?></td>
                        </tr>
                        <?php endforeach ?>                    
                    </tbody>
                </table>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
        <?php endif ?>

        <div class="row" style="margin-top: 5px;">
            <!-- accepted payments column -->
            <div class="col-xs-6">
                <?php if (!empty($data['note'])): ?>
                <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
                    <?php echo nl2br($data['note']); ?>
                </p>
                <?php endif ?>
            </div>
            <!-- /.col -->
            <div class="col-xs-6">
                <!--
                <p class="lead">Amount Due 2/22/2014</p>
                -->
                <div class="table-responsive">
                    <table class="table">
                        <tbody><tr>
                                <th style="width:50%"><?php echo $this->translate('Subtotal') ?>:</th>
                                <td><?php echo money_format($data['total_money']); ?></td>
                            </tr>
                            <tr>
                                <th><?php echo $this->translate('Tax') ?></th>
                                <td><?php echo money_format($data['tax']); ?></td>
                            </tr>
                            <tr>
                                <th><?php echo $this->translate('Shipping') ?></th>
                                <td><?php echo money_format($data['shipping']); ?></td>
                            </tr>
                            <tr>
                                <th><?php echo $this->translate('Total') ?></th>
                                <td><?php echo money_format($data['total_money'] + $data['tax'] + $data['shipping']); ?></td>
                            </tr>
                        </tbody></table>
                </div>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->

        <!-- this row will not appear when printing -->
        <div class="row no-print">
            <div class="col-xs-12">
                <a href="invoice-print.html" target="_blank" class="btn btn-default" style="margin-right: 3px;">
                    <i class="fa fa-print"></i> <?php echo $this->translate('Print') ?>
                </a>
                <a href="#" target="_blank" class="btn btn-default">
                    <i class="fa fa-download"></i> <?php echo $this->translate('Generate PDF') ?>
                </a>
                <a  href='#'
                    style="margin-left: 5px;"
                    data-dismiss='modal'
                    class="btn btn-default pull-right">
                    <i class="fa fa-close"></i> <?php echo $this->translate('Close') ?>
                </a> 
                <a                              
                   href="<?php echo $this->url(
                            'admin/productorders', 
                            array(
                                'action' => 'update',
                                'id' => $data['_id']
                            ))
                    ?>"                    
                    style="margin-left: 5px;"
                    class="btn btn-default pull-right">
                    <i class="fa fa-edit"></i> <?php echo $this->translate('Edit') ?>
                </a> 
                <?php if ($data['status'] != 'done' && $data['status'] != 'cancel'): ?>
                <a href='#'                             
                   data-url="<?php echo $this->url(
                             'admin/productorders', 
                             array(
                                 'action' => 'submitcancel',
                                 'id' => $data['_id']
                             ))
                   ?>"
                   data-confirmmessage='<?php echo $this->translate('Are you sure?') ?>'
                   data-callback="
                        if ($('#btn-submit-shipping').length > 0) {
                            $('#btn-submit-shipping').remove();
                        }
                        if ($('#btn-submit-payment').length > 0) {
                            $('#btn-submit-payment').remove();
                        }
                        if ($('#btn-submit-cancel').length > 0) {
                            $('#btn-submit-cancel').remove();
                        }
                        $('.invoice-col .order-status').hide();
                        $('.invoice-col .cancel').show();
                        $('.invoice-col .status-date').hide();
                        $('.invoice-col .status-cancel-date').show();
                        $('.invoice-col .cancel-date').html(result.date);                    
                        showMessage('<?php echo $this->translate('Status updated successfully') ?>')
                    "
                    style="margin-left: 5px;"
                    id="btn-submit-cancel"
                    class="btn btn-danger ajax-submit pull-right">
                    <i class="fa fa-remove"></i> <?php echo $this->translate('Submit Cancel') ?>
                </a>  
                <?php endif ?>  

                <?php if (empty($data['is_paid'])): ?>
                <a href='#'                             
                   data-url="<?php echo $this->url(
                            'admin/productorders', 
                            array(
                                'action' => 'submitpayment',
                                'id' => $data['_id']
                            ))
                    ?>"
                    data-confirmmessage='<?php echo $this->translate('Are you sure?') ?>'
                    data-callback="                        
                        if ($('#btn-submit-payment').length > 0) {
                            $('#btn-submit-payment').remove();
                        } 
                        $('.invoice-col .payment-date').html(result.date);
                        showMessage('<?php echo $this->translate('Status updated successfully') ?>')
                    "
                    style="margin-left: 5px;"
                    id="btn-submit-payment"
                    class="btn btn-success ajax-submit pull-right">
                   <i class="fa fa-credit-card"></i> <?php echo $this->translate('Submit Payment') ?>
                </a> 
                <?php endif ?>  

                <?php if ($data['status'] == 'shipping'): ?>
                <a href='#'                             
                   data-url="<?php echo $this->url(
                            'admin/productorders', 
                            array(
                                'action' => 'submitdone',
                                'id' => $data['_id']
                            ))
                    ?>"
                    data-confirmmessage='<?php echo $this->translate('Are you sure?') ?>'
                    data-callback="
                        if ($('#btn-submit-shipping').length > 0) {
                            $('#btn-submit-shipping').remove();
                        }                        
                        if ($('#btn-submit-cancel').length > 0) {
                            $('#btn-submit-cancel').remove();
                        }
                        if ($('#btn-submit-done').length > 0) {
                            $('#btn-submit-done').remove();
                        }
                        $('.invoice-col .order-status').hide();
                        $('.invoice-col .done').show();
                        if ($('.invoice-col .done-date').html() == '-') {
                            $('.invoice-col .done-date').html(result.date);
                        }
                        $('.invoice-col .done-date').html(result.date);
                        showMessage('<?php echo $this->translate('Status updated successfully') ?>')
                    "
                    style="margin-left: 5px;"
                    id="btn-submit-payment"
                    class="btn btn-success ajax-submit pull-right">
                   <i class="fa fa-credit-card"></i> <?php echo $this->translate('Submit Done') ?>
                </a> 
                <?php endif ?>  
                
                <?php if ($data['status'] == 'new'): ?>
                <a href='#'                             
                   data-url="<?php echo $this->url(
                            'admin/productorders', 
                            array(
                                'action' => 'submitshipping',
                                'id' => $data['_id']
                            ))
                    ?>"
                    data-confirmmessage='<?php echo $this->translate('Are you sure?') ?>'
                    data-callback="
                        if ($('#btn-submit-shipping').length > 0) {
                            $('#btn-submit-shipping').remove();
                        }                   
                        $('.invoice-col .order-status').hide();
                        $('.invoice-col .shipping').show();
                        $('.invoice-col .shipping-date').html(result.date);
                        showMessage('<?php echo $this->translate('Status updated successfully') ?>')
                    "
                    style="margin-left: 5px;"
                    id="btn-submit-shipping"
                    class="btn btn-warning ajax-submit pull-right">
                    <i class="fa fa-ship"></i> <?php echo $this->translate('Submit Shipping') ?>
                </a> 
                <?php endif ?>  

                
            </div>
        </div>
    </section>
</div>
<?php exit; ?>