<?php  
    $request = $this->requestHelper();   
    $post = (array) $request->getPost();  
    $tab = $request->getQuery('tab'); 
    $backUrl = $request->getQuery('backurl'); 
    $url = parse_url($request->getRequestUri())['path']; 
    if (!empty($post['loaddetail'])) {      
        echo $this->htmlListForm($detailForm);
        exit;
    }
?>
<div class="row">
    <div class="col-md-10">    
        <div class="box">    
            <div class="box-header" data-toggle="" title="" data-original-title="Header tooltip">
                <h3 class="box-title"><?php echo $this->translate('Order information') ?></h3>
            </div>
            <div class="box-body">
            <?php  
                echo $this->htmlForm($form); 
            ?>         
            </div>
        </div>
    </div>
</div>

<div class="row" id="row-order-detail">
    <div class="col-md-10">
        <div class="box">            
            <div class="box-header" data-toggle="" title="" data-original-title="Header tooltip">
                <h3 class="box-title"><?php echo $this->translate('Order Detail') ?></h3>                
            </div>
            <div class="box-body" id="order-detail">
            <?php
                echo $this->htmlListForm($detailForm);
            ?>            
            </div>
        </div>
    </div>
</div>

<div id="add-product-modal" class="modal fade" role="dialog" aria-labelledby="largeModal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">            
            <div class="modal-header">               
                <h4 class="modal-title" id="myModalLabel"><?php echo $this->translate('Add Product') ?></h4>
            </div>          
            <div class="modal-body">
                <div id="modal-message" class="modal-message callout callout-success"></div>
                <?php echo $this->htmlForm($addProductForm); ?> 
            </div>   
        </div>
    </div>
</div>