<div id="page-start"></div>
<!-- section start -->
<!-- ================ -->
<section class="section light-gray-bg clearfix">
	<div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="sidebar">
                    <?php if (!empty($categories)): ?>
                    <div class="block clearfix">
                        <h3 class="title"><?php echo $this->translate('Products')?></h3>
                        <div class="separator-2"></div>
                        <nav class="app-category">
                            <ul class="nav nav-pills nav-stacked">
                                <?php foreach ($categories as $category) : ?>  
                                <?php if (!empty($category['sub'])) : ?>                                  
                                    <li class="dropdown">
                                        <a  class="dropdown-toggle" 
                                            data-toggle="dropdown" 
                                            href="<?php echo $this->url('web/products', array('name' => name_2_url($category['name'])))?>">
                                            <?php echo $category['name'] ?>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <?php foreach ($category['sub'] as $subCategory) : ?> 
                                            <?php if (!empty($subCategory['sub'])) : ?>  
                                            <li class="divider"></li>
                                            <li class="dropdown-header"><?php echo $subCategory['name'] ?></li>
                                            <?php foreach ($subCategory['sub'] as $subCategory2) : ?>
                                            <li class="sub-category2">
                                                <a href="<?php echo $this->url('web/products', array('name' => name_2_url($subCategory2['name'])))?>">
                                                    <?php echo $subCategory2['name'] ?>
                                                </a>                                        
                                            </li>    
                                            <?php endforeach ?>  
                                            <?php else: ?>     
                                            <li>
                                                <a href="<?php echo $this->url('web/products', array('name' => name_2_url($subCategory['name'])))?>">
                                                    <?php echo $subCategory['name'] ?>
                                                </a>                                        
                                            </li>
                                            <?php endif ?>
                                            <?php endforeach ?>                                            
                                            <!--<li class="divider"></li>-->
                                            <!--<li class="dropdown-header">Nav header</li>-->                                            
                                        </ul>
                                    </li>                                
                                <?php else: ?>     
                                     <li>
                                        <a  href="<?php echo $this->url('web/products', array('name' => name_2_url($category['name'])))?>">
                                            <?php echo $category['name'] ?>
                                        </a>                                        
                                    </li>  
                                <?php endif ?>                                
                                <?php endforeach ?>                                
                            </ul>
                        </nav>
                    </div>
                    <?php endif ?>
                </div>
            </div>  
            <?php if (!empty($banners)): ?>
            <div class="col-md-9 hidden-xs">
                <div class="slider-wrapper theme-default app-banner">
                    <div id="slider" class="nivoSlider"> 
                        <?php foreach ($banners as $i => $banner) : ?>
                            <a href="<?php echo $banner['url']?>">
                                <img src="<?php echo $banner['url_image']?>" data-thumb="<?php echo $banner['url_image']?>" alt="" /> 
                            </a> 
                        <?php endforeach; ?>	                        
                    </div>                    
                </div>
            </div>
            <?php endif ?>
        </div>
        
        <?php if (!empty($featuredBrands)) : ?> 
		<div class="row">            
            <div class="col-md-12"> 
                <!-- section start -->
                <!-- ================ -->
                <section class="section clearfix">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <!--
                                <h3 class="logo-font"><?php echo $this->translate('Brands')?></h3>
                                <div class="separator-2"></div>          
                                -->
                                <div class="clients-container">
                                    <div itemscope itemtype="http://schema.org/Brand" class="clients">
                                        <?php 
                                        foreach ($featuredBrands as $brand) {                                             
                                            $brand['url'] = $this->url(
                                                'web/products', 
                                                array(                                                  
                                                    'name' => name_2_url($brand['name'])
                                                )
                                            );                                         
                                            echo "
                                            <div class=\"client-image object-non-visible animated object-visible fadeIn\" data-animation-effect=\"fadeIn\" data-effect-delay=\"100\">
                                                <a itemprop=\"url\" href=\"{$brand['url']}\"><img itemprop=\"image\" src=\"{$brand['url_image']}\" alt=\"\"></a>
                                            </div>
                                            ";
                                        }
                                        ?>                                                                                
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- section end -->
            </div>
            <?php endif ?>
            
			<div class="col-md-12">          
                
                <?php foreach ($blocks as $block) : ?> 
                <?php if (!empty($block['products'])) : ?> 
                <ul class="nav nav-pills" role="tablist">
                    <li class="active">
                        <a href="#" onclick="return false;"><strong><?php echo $block['name'] ?></strong></a>
                    </li>                 
                </ul>
                <!-- Tab panes -->
				<div class="tab-content clear-style">
					<div class="tab-pane active">
						<div class="row masonry-grid-fitrows grid-space-10" style="position: relative;">
                        <?php       
                            $products = $block['products'];
                            $locales = \Application\Module::getConfig('general.locales');
                            $request = $this->requestHelper(); 
                            if (!empty($products)) {
                                foreach ($products as $product) {
                                    echo $this->productItemHelper($product, 4);                                                                                                                    
                                }
                            }
                        ?>  
						</div>
					</div>
                </div>
                <?php endif ?>
                <?php endforeach ?>                
			</div>
		</div>
	</div>
</section>
<!-- section end -->