<!-- main-container start -->
<!-- ================ -->
<section class="main-container">

    <div class="container">
        <div class="row">

            <!-- main start -->
            <!-- ================ -->
            <div class="main col-md-12">

                <div class="row">
                    <div class="col-md-4">                        
                        <div class="tab-content clear-style">
                            <div class="tab-pane active" id="pill-1">
								<?php if (!empty($data['url_image'])) : ?>
                                <div class="owl-carousel content-slider-with-large-controls">
                                    <div class="overlay-container overlay-visible">
                                        <img src="<?php echo $data['url_image']; ?>" alt="<?php echo $data['name'] ?>">
                                        <a href="<?php echo $data['url_image']; ?>" class="popup-img overlay-link" title="<?php echo $data['name'] ?>"><i class="icon-plus-1"></i></a>
                                    </div>                                    
                                    <?php if (!empty($data['images'])) : ?>
									<?php foreach ($data['images'] as $image): ?>
                                    <div class="overlay-container overlay-visible">
                                        <img src="<?php echo $image['url_image']; ?>" alt="<?php echo $data['name'] ?>">
                                        <a href="<?php echo $image['url_image']; ?>" class="popup-img overlay-link" title="<?php echo $data['name'] ?>"><i class="icon-plus-1"></i></a>
                                    </div>
									<?php endforeach ?>  
                                    <?php endif ?>
                                </div>
								<?php endif ?>
                            </div>                            
                        </div>                      
                    </div>
                    <div itemscope itemtype="http://schema.org/Product" class="col-md-8 pv-30">
                        <h2 itemprop="name"><?php echo $data['name'] ?></h2>                        
                        <?php
                            if (!empty($data['brand_id'])) {
                                $data['brand_url'] = $this->url(
                                    'web/products', 
                                    array(
                                        'name' => name_2_url($data['brand']['name'])
                                    )
                                );
                                echo "<p class=\"attribute brand\">";
                                echo "<span class=\"attribute-name\">" . $this->translate('Brand') . ":</span>";                                            
                                echo "<span itemprop=\"name\" class=\"attribute-value\"><a itemprop=\"url\" href=\"{$data['brand_url']}\">{$data['brand']['name']}</a></span>";                                            
                                echo "</p>";                                
                            }
                        ?> 
                        <?php if (!empty($data['code'])): ?>
                        <p class="code">
                            <span class="attribute-name"><?php echo $this->translate('SKU') ?>:</span>
                            <span itemprop="name" class="attribute-value"><?php echo $data['code']; ?></span>
                        </p>
                        <?php endif ?>
                        <?php if (!empty($data['model'])): ?>
                        <p class="code">
                            <span class="attribute-name"><?php echo $this->translate('Model') ?>:</span>
                            <span itemprop="name" class="attribute-value"><?php echo $data['model']; ?></span>
                        </p>
                        <?php endif ?>                        
                        <?php if (!empty($data['warranty'])): ?>
                        <p class="warranty">
                            <span class="attribute-name"><?php echo $this->translate('Warranty') ?>:</span>
                            <span itemprop="name" class="attribute-value"><?php echo $data['warranty']; ?></span>
                        </p>
                        <?php endif ?>
                        <?php if (!empty($data['weight'])): ?>
                        <p class="warranty">
                            <span class="attribute-name"><?php echo $this->translate('Weight (kg)') ?>:</span>
                            <span itemprop="name" class="attribute-value"><?php echo $data['weight']; ?></span>
                        </p>
                        <?php endif ?>
                        <?php if (!empty($data['size'])): ?>
                        <p class="warranty">
                            <span class="attribute-name"><?php echo $this->translate('Size (depth x width x height cm)') ?>:</span>
                            <span itemprop="name" class="attribute-value"><?php echo $data['size']; ?></span>
                        </p>
                        <?php endif ?>
                        <?php if (!empty($data['made_in'])): ?>
                        <p class="made-in">
                            <span class="attribute-name"><?php echo $this->translate('Made in') ?>:</span>
                            <span itemprop="name" class="attribute-value"><?php echo $data['made_in']; ?></span>
                        </p>
                        <?php endif ?>
                        <?php
                            if (!empty($data['attributes'])) {
                                foreach ($data['attributes'] as $attribute) {
                                    if (!empty($attribute['options']['value_options']) 
                                        && !empty($attribute['value'])) {
                                        if (!is_array($attribute['value'])) {
                                            $attribute['value'] = array($attribute['value']);
                                        }
                                        $selectedValue = array();
                                        foreach ($attribute['options']['value_options'] as $valueId => $value) {
                                            if (in_array($valueId, $attribute['value'])) {
                                                $selectedValue[] = $value;
                                            }
                                        }
                                        echo "<p class=\"attribute\">";
                                        echo "<span class=\"attribute-name\">{$attribute['name']}:</span>";                                            
                                        echo "<span itemprop=\"name\" class=\"attribute-value\">" . implode(', ', $selectedValue) . "</span>";                                            
                                        echo "</p>";
                                    }
                                }
                            }
                        ?>   
                        
                        <p itemprop="description"><?php echo nl2br($data['short']) ?></p>
                        <hr class="mb-10">
                        
						<form method="post" id="detailForm" novalidate="novalidate" class="clearfix">
							
							<div class="light-gray-bg p-20 bordered clearfix">
                            <span class="product">
								<i class="icon-tag pr-10"></i>
                                <span itemprop="price" class="price">
								<?php 								
                                    if (!empty($data['price'])) {
                                        echo money_format($data['price']); 
                                    } else {
                                        echo $this->translate('Price contact');
                                    }                                    
                                ?>
                                </span>
                                <?php if (!empty($data['original_price'])):?>
                                <span itemprop="price" class="original-price">
                                    <?php echo money_format($data['original_price'])?>
                                </span>
                                <?php endif?>
							</span>
                            <div class="product elements-list pull-right clearfix">
                                <input 
									type="button" 
									value="<?php echo $this->translate('Add to cart') ?>" 
									data-url="<?php echo $this->url(
											'web/carts', 
											array(
												'action' => 'additem',
												'id' => $data['_id']
											))
									?>"
									data-callback="										
										loadCart(1);                                    
										showMessage('<?php echo $this->translate('Added to cart') ?>')
									"
									class="margin-clear btn btn-default ajax-submit">
                            </div>
                        </div>
						</form>
					</div>
                </div>
            </div>
            <!-- main end -->

        </div>
    </div>
</section>
<!-- main-container end -->

<!-- section start -->
<!-- ================ -->
<section class="pv-30 ">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs style-4" role="tablist">
                    <li class="active"><a href="#h2tab2" role="tab" data-toggle="tab"><i class="fa fa-files-o pr-5"></i><?php echo $this->translate('Detail Description') ?></a></li>
                    <li><a href="#h2tab3" role="tab" data-toggle="tab"><i class="fa fa-star pr-5"></i><?php echo $this->translate('Reviews') ?></a></li>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content padding-top-clear padding-bottom-clear">
                    <div class="tab-pane fade in active" id="h2tab2">                                              
                        <div itemprop="description">
                            <?php echo $data['content']; ?>
                        </div>
                        <?php if (!empty($data['brand'])): ?> 
                        <div itemscope itemtype=\"http://schema.org/Brand\">
                            <h4 class="space-top"><?php echo $this->translate('Brand information') ?></h4><hr>
                            <div itemprop="description"><?php echo nl2br($data['brand']['short']) ?></div>                        
                        </div>
                        <?php endif ?>
                    </div>
                    <div class="tab-pane fade" id="h2tab3">
                        <!-- comments start -->
                        <div itemprop="review" itemscope itemtype="http://schema.org/Review" class="comments margin-clear space-top" id="review-list">
                            <!-- comment start -->
                            <?php
                            if (!empty($reviewList)) {
                                foreach ($reviewList as $review) {
                                    $review['content'] = nl2br($review['content']);
                                    $time = app_datetime_format($review['created']);
                                    $rating = '';
                                    for ($star = 1; $star <= 5; $star++) {
                                        if ($review['rating'] >= $star) {
                                            $rating .= "<i class=\"fa fa-star text-default\"></i>"; 
                                        } else {
                                            $rating .= "<i class=\"fa fa-star\"></i>";
                                        }
                                    }
                                    echo "<div class=\"comment clearfix\">
                                        <!--
                                        <div class=\"comment-avatar\">
                                            <img class=\"img-circle\" src=\"/web/images/avatar.jpg\" alt=\"avatar\">
                                        </div>
                                        -->
                                        <header>
                                            <h3 itemprop=\"name\">{$review['name']}</h3>
                                            <div class=\"comment-meta\"> 
                                                <span itemprop=\"ratingValue\">{$rating}</span> | <span itemprop=\"datePublished\">{$time}</span>
                                            </div>
                                        </header>
                                        <div class=\"comment-content\">
                                            <div class=\"comment-body clearfix\">
                                                <p itemprop=\"description\">{$review['content']}</p>                                                
                                            </div>
                                        </div>
                                    </div>";
                                }
                            }
                            ?>                            
                            <!-- comment end -->
                        </div>
                        <!-- comments end -->

                        <!-- comments form start -->
                        <div class="comments-form">
                            <h2 class="title"><?php echo $this->translate('Add your Review') ?></h2>
                            <?php                
                                echo $this->htmlForm($reviewForm);                   
                            ?>                            
                        </div>
                        <!-- comments form end -->
                    </div>
                </div>
            </div>

            <!-- sidebar start -->
            <!-- ================ -->
            <aside class="col-md-4 col-lg-3 col-lg-offset-1">
                <div class="sidebar">
                    <div class="block clearfix">
                        <?php if (!empty($relatedProducts)) : ?>
                        <h3 class="title"><?php echo $this->translate('Related Products') ?></h3>
                        <div class="separator-2"></div>
                        <?php                         
                            $locales = \Application\Module::getConfig('general.locales');
                            $request = $this->requestHelper(); 
                            if (!empty($relatedProducts)) {
                                foreach ($relatedProducts as $product) {
                                    $product['url'] = $this->url(
                                        'web/products', 
                                        array(
                                            'name' => name_2_url($product['name'])
                                        )
                                    );
                                    $product['original_price'] = !empty($product['original_price']) ? money_format($product['original_price']) : '';
                                    $product['price'] = money_format($product['price']);
                                    $product['name'] = truncate($product['name'], 60);
                                    echo "
                                    <div itemscope itemtype=\"http://schema.org/Product\" class=\"media margin-clear\">
                                        <div class=\"media-left\">
                                            <div class=\"overlay-container\">
                                                <img itemprop=\"image\" alt=\"{$product['name']}\" class=\"media-object\" src=\"{$product['url_image']}\">
                                                <a itemprop=\"url\" href=\"{$product['url']}\" class=\"overlay-link small\"><i class=\"fa fa-link\"></i></a>
                                            </div>
                                        </div>
                                        <div class=\"media-body\">
                                            <h6 class=\"media-heading\"><a itemprop=\"url\" href=\"{$product['url']}\"><span itemprop=\"name\">{$product['name']}</span></a></a></h6>
                                            <p>
                                                <span itemprop=\"price\" class=\"price\">{$product['price']}</span>
                                                <span itemprop=\"price\" class=\"original-price\">{$product['original_price']}</span>
                                            </p>
                                        </div>
                                        <hr>
                                    </div>";                                    
                                }
                            }
                        ?>
                        
                        <?php endif ?>                       
                        
                    </div>
                </div>
            </aside>
            <!-- sidebar end -->

        </div>
    </div>
</section>
<!-- section end -->

