<?php 
    $request = $this->requestHelper();
    $priceFrom = $request->getQuery('price_from', '');
    $priceTo = $request->getQuery('price_to', '');    
    $categoryId = !empty($detailCategory['category_id']) ? $detailCategory['category_id'] : 0;
    $brandId = !empty($detailBrand['brand_id']) ? $detailBrand['brand_id'] : 0;
?>		
<div id="page-start"></div>
<!-- section start -->
<!-- ================ -->
<section class="section light-gray-bg clearfix">
	<div class="container">
        <!--
        <div class="row">
            <div class="col-md-9">
                <div class="slider-wrapper theme-default">
                    <div id="slider" class="nivoSlider"> 
                        <?php  foreach ($banners as $i => $banner) : ?>
                            <a href="<?php echo $banner['url']?>">
                                <img src="<?php echo $banner['url_image']?>" data-thumb="<?php echo $banner['url_image']?>" alt="" /> 
                            </a> 
                        <?php endforeach; ?>	                        
                    </div>
                    <div id="htmlcaption" class="nivo-html-caption"> <strong>This</strong> is an example of a <em>HTML</em> caption with <a href="#">a link</a>. </div>
                </div>
            </div>    
            <div class="col-md-3">
                <img src="/web/images/category-6.jpg" style="height:300px;" />
            </div>  
        </div>
        -->
		<div class="row">
            <div class="col-md-3">
                <form>                
                    <div class="sidebar">
                        <?php if (!empty($subCategories)): ?>
                        <div class="block clearfix">
                            <h3 class="title"><?php echo $this->translate('Products') ?></h3>
                            <div class="separator-2"></div>
                            <nav class="app-category">
                                <ul itemscope itemtype="http://schema.org/Product" class="nav nav-pills nav-stacked nav-show">
                                    <?php foreach ($subCategories as $category) : ?>  
                                    <?php if (!empty($category['sub'])) : ?>  
                                        <li class="dropdown<?php if ($openCategoryId==$category['category_id']) echo ' open'?><?php if ($categoryId==$category['category_id']) echo ' active'?>">
                                            <a itemprop="name" class="dropdown-toggle" href="<?php echo $this->url('web/products', array('name' => name_2_url($category['name'])))?>">
                                                <?php echo $category['name'] ?>
                                            </a>
                                            <ul class="dropdown-menu">
                                                <?php foreach ($category['sub'] as $subCategory1) : ?> 
                                                <?php if (!empty($subCategory1['sub'])) : ?>  
                                                <li class="divider"></li>
                                                <li class="dropdown-header"><?php echo $subCategory1['name'] ?></li>
                                                <?php foreach ($subCategory1['sub'] as $subCategory2) : ?>
                                                <li class="sub-category2">
                                                    <a itemprop="name" href="<?php echo $this->url('web/products', array('name' => name_2_url($subCategory2['name'])))?>">
                                                        <?php echo $subCategory2['name'] ?>
                                                    </a>                                        
                                                </li>    
                                                <?php endforeach ?>  
                                                <?php else: ?>     
                                                <li<?php if ($categoryId==$subCategory1['category_id']) echo ' class="active"'?>>
                                                    <a itemprop="name" href="<?php echo $this->url('web/products', array('name' => name_2_url($subCategory1['name'])))?>">
                                                        <?php echo $subCategory1['name'] ?>
                                                    </a>                                        
                                                </li>
                                                <?php endif ?>
                                                <?php endforeach ?>                       
                                            </ul>
                                        </li>   
                                    <?php else: ?>     
                                         <li<?php if ($categoryId==$category['category_id']) echo ' class="active"'?>>
                                            <a itemprop="name" href="<?php echo $this->url('web/products', array('name' => name_2_url($category['name'])))?>">
                                                <?php echo $category['name'] ?>
                                            </a>                                        
                                        </li>  
                                    <?php endif ?>                                
                                    <?php endforeach ?>                                
                                </ul>
                            </nav>
                        </div>
                        <?php endif ?>

                        <?php if (empty($subCategories) && !empty($filter['category'])): ?>
                        <div class="block clearfix">
                            <h3 class="title"><?php echo $this->translate('Products') ?></h3>
                            <div class="separator-2"></div>
                            <nav>
                                <ul itemscope itemtype="http://schema.org/Product" class="nav nav-pills nav-stacked">
                                    <?php foreach ($filter['category'] as $category) : ?>  
                                    <li <?php if ($categoryId==$category['category_id']) echo ' class="active"'?>>
                                        <a itemprop="name" href="
                                            <?php
                                                $routeUrl = array(
                                                    'name' => name_2_url($category['category_name'])                                                   
                                                ); 
                                                if (!empty($detailBrand['name'])) {
                                                    $routeUrl['brand_name'] = name_2_url($detailBrand['name']);
                                                }
                                                echo $this->url(
                                                    'web/products', 
                                                    $routeUrl
                                                )
                                            ?>">
                                            <?php echo $category['category_name'] ?>
                                        </a>
                                    </li>
                                    <?php endforeach ?>                                
                                </ul>
                            </nav>
                        </div>
                        <?php endif ?>                  

                        <?php if (!empty($filter['brand'])): ?>
                        <div class="block clearfix">
                            <h3 class="title"><?php echo $this->translate('Brand') ?></h3>
                            <div class="separator-2"></div>
                            <nav>
                                <ul itemscope itemtype="http://schema.org/Brand" class="nav nav-pills nav-stacked">
                                    <?php foreach ($filter['brand'] as $brand) : ?>  
                                    <li<?php if ($brandId==$brand['brand_id']) echo ' class="active"'?>>
                                        <a href="<?php 
                                            $routerParam = array(
                                                'brand_name' => name_2_url($brand['brand_name'])
                                            );
                                            if (!empty($detailCategory['name'])) {
                                                $routerParam['name'] = name_2_url($detailCategory['name']);
                                            }
                                            echo $this->url(
                                                'web/products', 
                                                $routerParam
                                            )?>">
                                            <span itemprop="name"><?php echo $brand['brand_name'] ?></span>
                                            (<?php echo $brand['count_product'] ?>)
                                        </a>
                                    </li>
                                    <?php endforeach ?>                                
                                </ul>
                            </nav>
                        </div>
                        <?php endif ?>

                        <div class="block clearfix">
                            <h3 class="title"><?php echo $this->translate('Price') ?></h3>
                            <div class="separator-2"></div>
                            <?php
                                $slideValue = $filter['price']['min'] . ',' . $filter['price']['max'];
                                if ($priceFrom !== '' && $priceTo !== '') {
                                    $slideValue = db_float($priceFrom) . ',' . db_float($priceTo);
                                }
                                echo $this->sliderHelper(
                                    'price-range', 
                                    'price_from', 
                                    'price_to',
                                    $filter['price']['min'],
                                    $filter['price']['max'],
                                    '50000',
                                    $slideValue
                                );
                            ?>                                                   
                        </div>
                    </div>
                </form>
            </div>
			<div class="col-md-9">                
				
				<div class="tab-content clear-style">
					<div class="tab-pane active" id="pill-1">
						<div class="row masonry-grid-fitrows grid-space-10" style="position: relative; height: 1082.02px;">
                        <?php                         
                            $locales = \Application\Module::getConfig('general.locales');
                            $request = $this->requestHelper();    
                            $products = !empty($result['data']) ? $result['data'] : array();
                            $limit = !empty($result['limit']) ? $result['limit'] : 10;
                            $count = !empty($result['count']) ? $result['count'] : 0; 
                            if (!empty($products)) {
                                foreach ($products as $product) {
                                    $product['url'] = $this->url(
                                        'web/products', 
                                        array(
                                            'name' => name_2_url($product['name'])
                                        )
                                    );
                                    $product['url_add_to_cart'] = $this->url(
                                        'web/carts', 
                                        array(
                                            'action' => 'additem',
                                            'id' => $product['_id']
                                        )
                                    );     
                                    $product['url_add_to_wishlist'] = '#';
                                    $product['original_price'] = !empty($product['original_price']) ? money_format($product['original_price']) : '';
                                    $product['price'] = money_format($product['price']);
                                    $product['name'] = truncate($product['name'], 60);
                                    $product['short'] = nl2br(truncate($product['short'], 80)); 
                                    echo "
                                        <div class=\"col-sm-6 col-lg-4 masonry-grid-item\">
                                            <div itemscope itemtype=\"http://schema.org/Product\" class=\"listing-item white-bg bordered mb-20\">
                                                <div class=\"overlay-container\">
                                                    <div class=\"image\">
                                                        <img itemprop=\"image\" alt=\"{$product['name']}\" src=\"{$product['url_image']}\" alt=\"\">
                                                    </div>
                                                    <a class=\"overlay-link popup-img-single\" href=\"{$product['url_image']}\"><i class=\"fa fa-search-plus\"></i></a>
                                                    <div class=\"overlay-to-top links\">
                                                        <span class=\"small\">
                                                            <!--<a href=\"{$product['url_add_to_wishlist']}#\" class=\"btn-sm-link\"><i class=\"fa fa-heart-o pr-10\"></i>{$this->translate('Add to Wishlist')}</a>-->
                                                            <a itemprop=\"url\" href=\"{$product['url']}\" class=\"btn-sm-link\"><i class=\"icon-link pr-5\"></i>{$this->translate('View Details')}</a>
                                                        </span>
                                                    </div>
                                                </div>
                                                <div class=\"body\">
                                                    <h3><a itemprop=\"url\" href=\"{$product['url']}\"><span itemprop=\"name\">{$product['name']}</span></a></h3>
                                                    <div class=\"elements-list clearfix\">
                                                        <span itemprop=\"price\" class=\"price\">{$product['price']}</span>
                                                        <a  itemprop=\"url\" href=\"#\" 
                                                            class=\"pull-right margin-clear btn btn-sm btn-default-transparent btn-animated ajax-submit\"                                                           
                                                            data-url=\"{$product['url_add_to_cart']}\"
                                                            data-callback=\"
                                                                loadCart(1);                                    
                                                                showMessage('{$this->translate('Added to cart')}')
                                                            \">{$this->translate('Add to cart')} <i class=\"fa fa-shopping-cart\"></i>
                                                        </a>                                                                
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    ";                                                                                                                     
                                }
                            }
                        ?>   
						</div>
					</div>
                    <!-- pills end -->
                    <!-- pagination start -->
                    <nav class="text-center">
                        <?php   
                            if ($count > $limit) {
                                echo $this->paginatorHelper(
                                    $params, 
                                    $count, 
                                    $limit
                                );
                            }
                        ?>
                    </nav>                    
				</div>
				<!-- pills end -->
			</div>
		</div>
	</div>
</section>
<!-- section end -->