<!-- footer top start -->
<!-- ================ -->
<!--
<div class="dark-bg  default-hovered footer-top animated-text">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="call-to-action text-center">
					<div class="row">
						<div class="col-sm-8">
							<h2>Powerful Bootstrap Template</h2>
							<h2>Waste no more time</h2>
						</div>
						<div class="col-sm-4">
							<p class="mt-10"><a href="http://htmlcoder.me/preview/the_project/v.1.1/template/index-shop.html#" class="btn btn-animated btn-lg btn-gray-transparent ">Purchase<i class="fa fa-cart-arrow-down pl-20"></i></a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
-->
<!-- footer top end -->

<!-- footer start (Add "dark" class to #footer in order to enable dark footer) -->
<!-- ================ -->
<footer id="footer" class="clearfix">

	<!-- .footer start -->
	<!-- ================ -->
	<div class="footer">
		<!-- .footer start -->
        <!-- ================ -->
        <div class="footer">
            <div class="container">
                <div class="footer-inner">
                    <div itemscope itemtype="http://schema.org/ItemList" class="row">
                        <?php foreach ($footerMenus as $menu) : ?>                        
                        <div class="col-md-4">
                            <div class="footer-content">
                                <h4 itemprop="name" class="title text-default"><?php echo $menu['name']?></h4>
                                <nav class="mb-20">
                                    <?php if (!empty($menu['sub'])) : ?> 
                                    <ul itemprop="itemListElement" class="nav nav-pills nav-stacked list-style-icons">
                                    <?php foreach ($menu['sub'] as $subMenu) : ?>  
                                        <li>
                                            <?php if (!empty($subMenu['url'])): ?>
                                            <a itemprop="url" href="<?php echo !empty($subMenu['url']) ? $subMenu['url'] : '#'?>">
                                                <i class="fa fa-chevron-circle-right"></i> 
                                                <span itemprop="name"><?php echo $subMenu['name']?></span>
                                            </a>                                                
                                            <?php else: ?>
                                            <div>
                                                <i class="fa fa-chevron-circle-right"></i> 
                                                <span itemprop="name"><?php echo $subMenu['name']?></span>
                                            </div>
                                            <?php endif ?>
                                        </li>
                                    <?php endforeach ?>                                         
                                    </ul>
                                    <?php endif; ?>
                                </nav>                                
                            </div>
                        </div>
                        <?php endforeach ?> 
                    </div>
                </div>
            </div>
        </div>
        <!-- .footer end -->
	</div>
	<!-- .footer end -->

	<!-- .subfooter start -->
	<!-- ================ -->
	<div class="subfooter">
		<div class="container">
			<div class="subfooter-inner">
				<div class="row">
					<div class="col-md-12">
						<p class="text-center">
                            <?php echo $this->translate(Web\Module::getConfig('head_meta.copyright')) ?>
                        </p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- .subfooter end -->