<?php  
    $request = $this->requestHelper();    
    $tab = $request->getQuery('tab'); 
    $backUrl = $request->getQuery('backurl'); 
    $url = parse_url($request->getRequestUri())['path'];
?>
<div class="row">
    <div class="col-xs-12">    
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs pull-left">
                <li class="<?php if ($tab == '') echo "active" ?>"><a href="<?php echo $url . '?backurl=' . $backUrl;?>" aria-expanded="false"><?php echo $this->translate('General') ?></a></li>
                <li class="<?php if ($tab=='password') echo "active" ?>"><a href="<?php echo $url . '?tab=password&backurl=' . $backUrl;?>" aria-expanded="false"><?php echo $this->translate('Change password') ?></a></li>
            </ul>
            <div class="tab-content no-padding">
                <div class="box-body">
                <?php  
                    echo $this->htmlForm($form);    
                ?>           
                </div>
            </div>
        </div>
    </div>
</div>