<!-- main-container start -->
<!-- ================ -->
<section class="main-container">

    <div class="container">
        <div class="row">

            <!-- main start -->
            <!-- ================ -->
            <div class="main col-md-8 col-md-offset-2">

                <!-- page-title start -->
                <!-- ================ -->
                <h1 class="page-title text-center"><?php echo $this->translate('Thank you')?> <i class="fa fa-smile-o pl-10"></i></h1>
                <div class="separator"></div>
                <!-- page-title end -->
                <p class="lead text-center red">
                    <?php echo $this->translate('Your order has been received and is being processed')?>                    
                </p>
                <p class="lead text-center">
                    Chúng tôi sẽ cập nhật trạng thái đơn hàng qua hộp thư <strong class="red"><?php echo $data['user_email']?></strong>.<br/> Hãy kiểm tra thư trong Inbox (Hộp thư đến) hoặc Spam (Thư nháp) bạn nhé
                </p>
                
                <div class="row">
                    <?php if (!empty($data['payment']) && $data['payment'] == 'ATM'): ?>
                    <div class="bank-account" style="padding-left: 0px; margin-bottom: 15px;">
                        <?php echo \Web\Module::getConfig('bank_account')?>
                    </div>
                    <?php endif ?>
                    
                    <table class='table cart table-bordered'>
                        <thead>
                            <tr>
                                <th colspan="2"><?php echo $this->translate('Invoice')?></th>
                            </tr>
                        </thead>
                        <tbody>                        
                            <tr>
                                <td><?php echo $this->translate('Code')?></td>
                                <td class="information"><?php echo $data['code']?></td>
                            </tr>
                            <tr>
                                <td><?php echo $this->translate('Order date')?></td>
                                <td class="information"><?php echo date('Y-m-d H:i:s', $data['created'])?></td>
                            </tr>
                            <tr>
                                <td><?php echo $this->translate('Order status')?></td>
                                <td class="information invoice-col">
                                    <span <?php if ($data['status'] == 'new') echo 'style="display:inline"' ?> class="btn btn-flat order-status new"><?php echo $this->translate('Processing'); ?></span>
                                    <span <?php if ($data['status'] == 'shipping') echo 'style="display:inline"' ?>class="btn btn-flat order-status shipping"><?php echo $this->translate('Shipping'); ?></span>
                                    <span <?php if ($data['status'] == 'paid') echo 'style="display:inline"' ?>class="btn btn-flat order-status paid"><?php echo $this->translate('Paid'); ?></span>
                                    <span <?php if ($data['status'] == 'cancel') echo 'style="display:inline"' ?>class="btn btn-flat order-status cancel"><?php echo $this->translate('Canceled'); ?></span>
                                </td>
                            </tr>
                            <tr>
                                <td><?php echo $this->translate('Memo')?></td>
                                <td class="information"><?php echo $data['note']?></td>
                            </tr>
                        </tbody>
                    </table>
                        
                    <table class='table cart table-bordered'>
                        <thead>
                            <tr>
                                <th colspan="2"><?php echo $this->translate('Customer information')?></th>
                            </tr>
                        </thead>
                        <tbody>      
                            <tr>
                                <td><?php echo $this->translate('Full name')?></td>
                                <td class="information"><?php echo $data['user_name']?></td>
                            </tr>
                            <tr>
                                <td><?php echo $this->translate('Address')?></td>
                                <td class="information"><?php echo $data['address']?></td>
                            </tr>      
                            <?php if (!empty($data['user_phone'])): ?>
                            <tr>
                                <td><?php echo $this->translate('Phone')?></td>
                                <td class="information"><?php echo $data['user_phone']?></td>
                            </tr>
                            <?php endif ?>
                            <?php if (!empty($data['user_mobile'])): ?>
                            <tr>
                                <td><?php echo $this->translate('Mobile')?></td>
                                <td class="information"><?php echo $data['user_mobile']?></td>
                            </tr>
                            <?php endif ?>
                            <?php if (!empty($data['user_email'])): ?>
                            <tr>
                                <td><?php echo $this->translate('Email')?></td>
                                <td class="information"><?php echo $data['user_email']?></td>
                            </tr>
                            <?php endif ?>
                        </tbody>
                    </table>
                        
                    <?php if (!empty($data['products'])): ?>                        
                    <table class='table cart table-bordered'>
                        <thead>
                            <!--
                            <tr>
                                <th colspan="4"><?php echo $this->translate('Order detail')?></th>
                            </tr>
                            -->
                            <tr>
                                <th><?php echo $this->translate('Product name') ?></th>
                                <th><?php echo $this->translate('Quantity') ?></th>
                                <th><?php echo $this->translate('Price') ?></th>
                                <th class="amount"><?php echo $this->translate('Subtotal') ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($data['products'] as $product): ?>
                            <tr>
                                <td><?php echo $product['product_name']; ?></td>
                                <td align="right"><?php echo $product['quantity']; ?></td>                        
                                <td align="right"><?php echo app_money_format($product['price']); ?></td>                        
                                <td align="right"><?php echo app_money_format($product['total_money']); ?></td>
                            </tr>
                            <?php endforeach ?> 
                            <tr>                              
                                <td colspan="3" align="right"><?php echo $this->translate('Total')?></td>
                                <td align="right"><strong><?php echo app_money_format($data['total_money'])?></strong></td>
                            </tr>
                            <tr>                                
                                <td colspan="3" align="right"><?php echo $this->translate('Discount')?></th>
                                <td align="right"><strong><?php echo app_money_format($data['discount'])?></strong></td>
                            </tr>
                            <tr>                               
                                <td colspan="3" align="right"><?php echo $this->translate('Tax money') ?></td>
                                <td align="right"><strong><?php echo app_money_format($data['tax'])?></strong></td>
                            </tr>
                            <tr>                              
                                <td colspan="3" align="right"><?php echo $this->translate('Shipping money') ?></td>
                                <td align="right"><strong><?php echo app_money_format($data['shipping'])?></strong></td>
                            </tr> 
                            <tr>                              
                                <td colspan="3" align="right"><?php echo $this->translate('Total payment')?></td>
                                <td align="right"><strong><?php echo app_money_format(db_float($data['total_money']) - db_float($data['discount']) + db_float($data['tax']) + db_float($data['shipping']))?></strong></td>
                            </tr>    
                        </tbody>
                    </table>                                        
                    <?php endif ?>                        
                                  
                </div> 
        
                <p class="text-center">
                    <a href="<?php echo $this->url('web/my', array(), array('query' => array('tab' => 'productorder')))?>" class="btn btn-default btn-lg"><?php echo $this->translate('Order list')?></a>	
                    <a style="margin-left:5px;" href="/" class="btn btn-default btn-lg"><?php echo $this->translate('Continue shopping!')?></a>	
                </p>
            </div>
            <!-- main end -->

        </div>
    </div>
</section>
<!-- main-container end -->