<?php  
    $locales = \Application\Module::getConfig('general.locales');
    $request = $this->requestHelper();    
    $tab = $request->getQuery('tab'); 
    $backUrl = $request->getQuery('backurl'); 
    $url = parse_url($request->getRequestUri())['path'];
?>
<div class="row">
    <div class="col-xs-12">    
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs pull-left">
                <li class="<?php if ($tab == '') echo "active" ?>"><a href="<?php echo $url . '?backurl=' . $backUrl;?>" aria-expanded="false"><?php echo $this->translate('General') ?></a></li>
                <?php if (count($locales) > 1) : ?>
                <?php foreach ($locales as $locale => $name) : ?>
                    <li class="<?php if ($tab==$locale) echo "active" ?>"><a href="<?php echo $url . '?tab=' . $locale . '&backurl=' . $backUrl;?>" aria-expanded="false"><?php echo $name ?></a></li>
                <?php endforeach; ?>
                <?php endif ?>
            </ul>
            <div class="tab-content no-padding">
                <div class="box-body">
                <?php if ($form != null) : ?>
                    <?php echo $this->htmlForm($form); ?>           
                <?php endif ?>
                   
                <?php if ($updateOptionForm != null) : ?>    
                    <div class="box box-primary">
                        <div class="box-header" data-toggle="" title="" data-original-title="Header tooltip">
                        <h3 class="box-title"><?php echo $this->translate('Add Option') ?></h3>
                        </div>
                        <div class="box-body">
                            <?php
                                echo $this->htmlForm($updateOptionForm);
                            ?>
                        </div>
                    </div>
                <?php endif ?>
                    
                <?php if ($optionForm != null) : ?>    
                    <div class="box box-primary">
                        <div class="box-header" data-toggle="" title="" data-original-title="Header tooltip">
                        <h3 class="box-title"><?php echo $this->translate('Option List') ?></h3>
                        </div>
                        <div class="box-body">
                            <?php
                                echo $this->htmlListForm($optionForm);
                            ?>
                        </div>
                    </div>
                <?php endif ?>
                </div>
            </div>
        </div>
    </div>
</div>