<div id="page-start"></div>
<!-- section start -->
<!-- ================ -->
<section class="section light-gray-bg clearfix">
	<div class="container">
        <div class="row">     
            <div class="mt-5"></div>
            <?php if (!empty($banners)): ?>
            <div class="col-md-12">
                <div class="slider-wrapper theme-default app-banner">
                    <div id="slider" class="nivoSlider"> 
                        <?php foreach ($banners as $i => $banner) : ?>
                            <a href="<?php echo $banner['url']?>">
                                <img src="<?php echo $banner['url_image']?>" data-thumb="<?php echo $banner['url_image']?>" alt="" /> 
                            </a> 
                        <?php endforeach; ?>	                        
                    </div>                    
                </div>
            </div>
            <?php endif ?>
            <div class="col-md-12">
                <?php echo \Web\Module::getConfig('commitment')?>
            </div>
        </div>
        
        <div class="row"> 
            <?php if (!empty($featuredBrands)) : ?> 		           
            <div class="col-md-12"> 
                <!-- section start -->
                <!-- ================ -->
                <section class="section clearfix">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <!--
                                <h3 class="logo-font"><?php echo $this->translate('Brands')?></h3>
                                <div class="separator-2"></div>          
                                -->
                                <div class="clients-container">
                                    <div itemscope itemtype="http://schema.org/Brand" class="clients">
                                        <?php 
                                        foreach ($featuredBrands as $brand) {                                             
                                            $brand['url'] = $this->url(
                                                'web/products', 
                                                array(                                                  
                                                    'name' => name_2_url($brand['name'])
                                                )
                                            );                                         
                                            echo "
                                            <div class=\"client-image object-non-visible animated object-visible fadeIn\" data-animation-effect=\"fadeIn\" data-effect-delay=\"100\">
                                                <a itemprop=\"url\" href=\"{$brand['url']}\"><img itemprop=\"image\" src=\"{$brand['url_image']}\" alt=\"\"></a>
                                            </div>
                                            ";
                                        }
                                        ?>                                                                                
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- section end -->
            </div>
            <?php endif ?>
            
            <?php foreach ($blocks as $block) : ?> 
			<div class="col-md-12 mb-10">
                <?php if (!empty($block['products'])) : ?> 
                <ul class="nav nav-tabs style-1" role="tablist">
                    <li class="active">
                        <a href="#" role="tab" data-toggle="tab" onclick="return false;"><strong><?php echo $block['name'] ?></strong></a>
                    </li>                 
                </ul>
                <!-- Tab panes -->
				<div class="tab-content clear-style">
					<div class="tab-pane active">
						<div id="grid-4" class="row masonry-grid-fitrows grid-space-10" style="position: relative;">
                        <?php       
                            $products = $block['products'];
                            $locales = \Application\Module::getConfig('general.locales');
                            $request = $this->requestHelper(); 
                            if (!empty($products)) {
                                foreach ($products as $product) {
                                    echo $this->productItemHelper($product, 4);                                                                                                                    
                                }
                            }
                        ?>  
						</div>
					</div>
                </div>
                <?php endif ?>                              
			</div>
            <?php endforeach ?>  
		</div>
	</div>
</section>
<!-- section end -->