<?php
$categories = \Web\Model\ProductCategories::getSubCategories($website['product_categories'], $lastLevel, 0, false);
$cartItems = Application\Lib\Cart::get();
$totalQuantity = 0;
$totalMoney = 0;
if (!empty($cartItems)) {    
    foreach ($cartItems as $item) {
        $totalQuantity += $item['quantity'];
        $totalMoney += $item['quantity'] * $item['price'];
    }
}
?>
<!-- header-container start -->
<div class="header-container">
	
	<!-- header-top start -->
	<!-- classes:  -->
	<!-- "dark": dark version of header top e.g. class="header-top dark" -->
	<!-- "colored": colored version of header top e.g. class="header-top colored" -->
	<!-- ================ -->
	<div class="header-top dark ">
		<div class="container">
			<div class="row">
				<div class="col-xs-3 col-sm-6 col-md-9">
					<!-- header-top-first start -->
					<!-- ================ -->
					<div class="header-top-first clearfix">
						<ul class="social-links circle small clearfix hidden-xs">
                            <?php if (!empty($website['facebook'])): ?>
                            <li class="facebook"><a target="_blank" href="<?php echo $website['facebook']; ?>"><i class="fa fa-facebook"></i></a></li>
                            <?php endif ?>

                            <?php if (!empty($website['twitter'])): ?>
                            <li class="twitter"><a target="_blank" href="<?php echo $website['twitter']; ?>"><i class="fa fa-twitter"></i></a></li>
                            <?php endif ?>

                            <?php if (!empty($website['linkedin'])): ?>
                            <li class="linkedin"><a target="_blank" href="<?php echo $website['linkedin']; ?>"><i class="fa fa-linkedin"></i></a></li>
                            <?php endif ?>

                            <?php if (!empty($website['youtube'])): ?>
                            <li class="youtube"><a target="_blank" href="<?php echo $website['youtube']; ?>"><i class="fa fa-youtube"></i></a></li>
                            <?php endif ?>                                    
						</ul>
						
                        <div class="social-links hidden-lg hidden-md hidden-sm circle small">
                            <!--
                            <div class="btn-group dropdown">
                                <button type="button" class="btn dropdown-toggle" data-toggle="dropdown"><i class="fa fa-share-alt"></i></button>
                                <ul class="dropdown-menu dropdown-animation">
                                    <?php if (!empty($website['facebook'])): ?>
                                    <li class="facebook"><a target="_blank" href="<?php echo $website['facebook']; ?>"><i class="fa fa-facebook"></i></a></li>
                                    <?php endif ?>

                                    <?php if (!empty($website['twitter'])): ?>
                                    <li class="twitter"><a target="_blank" href="<?php echo $website['twitter']; ?>"><i class="fa fa-twitter"></i></a></li>
                                    <?php endif ?>

                                    <?php if (!empty($website['linkedin'])): ?>
                                    <li class="linkedin"><a target="_blank" href="<?php echo $website['linkedin']; ?>"><i class="fa fa-linkedin"></i></a></li>
                                    <?php endif ?>

                                    <?php if (!empty($website['youtube'])): ?>
                                    <li class="youtube"><a target="_blank" href="<?php echo $website['youtube']; ?>"><i class="fa fa-youtube"></i></a></li>
                                    <?php endif ?>
                                </ul>
                            </div>
                            -->
                        </div>
                        
						<ul class="list-inline hidden-sm hidden-xs">
                            <?php if (!empty($website['address']) && 1==0): ?>  
							<li>                                
                                <i class="fa fa-map-marker pr-5 pl-10"></i>
                                <a itemprop="address" itemscope itemtype="http://schema.org/PostalAddress" href="<?php echo $this->url('web/contact')?>">
                                    <?php echo $website['address']; ?>
                                </a>
                            </li>
							<?php endif ?>
                            
                            <?php if (!empty($website['phone'])): ?> 
                            <li>
                                <i class="fa fa-phone pr-5 pl-10"></i>
                                <span itemprop="telephone"><?php echo $website['phone']; ?></span>
                            </li>
							<?php endif ?>
                            
                            <?php if (!empty($website['email'])): ?> 
                            <li>                                
                                <i class="fa fa-envelope-o pr-5 pl-10"></i>
                                <a itemprop="email" href="mailto:<?php echo $website['email']?>">
                                    <?php echo $website['email']; ?>
                                </a>
                            </li>
                            <?php endif ?>
						</ul>
					</div>
					<!-- header-top-first end -->
				</div>
				<div class="col-xs-9 col-sm-6 col-md-3">

					<!-- header-top-second start -->
					<!-- ================ -->
					<div id="header-top-second" class="clearfix">

						<!-- header top dropdowns start -->
						<!-- ================ -->
						<div class="header-top-dropdown text-right">
                        <?php if (!empty($AppUI)): ?> 
                            <!-- User Account: style can be found in dropdown.less -->
                            <div class="navbar-custom-menu">
                                <ul class="nav navbar-nav"> 
                                    <li class="dropdown user user-menu">
                                        <a itemscope itemtype="http://schema.org/Person" href="#" class="dropdown-toggle" data-toggle="dropdown">
                                            <?php if (!empty($AppUI->url_image)): ?>
                                            <img itemprop="image" src="<?php echo $AppUI->url_image;?>" class="user-image" alt="<?php echo $AppUI->display_name;?>">
                                            <?php endif ?>
                                            <span itemprop="name" class=""><?php echo $AppUI->display_name;?></span>
                                        </a>
                                        <ul itemscope itemtype="http://schema.org/ItemList" class="dropdown-menu">                                            
                                            <li itemprop="itemListElement" class="user-body">
                                                <?php if (in_array($AppUI->id, \Application\Module::getConfig('admin_user_id'))): ?>
                                                <div class="col-xs-12 text-left">
                                                    <a itemprop="url" href="<?php echo $this->url('web/page', array('action' => 'deletecache'))?>">                                                        
                                                        <span itemprop="name"><?php echo $this->translate('Delete cache')?></span>
                                                    </a>
                                                </div>
                                                <div class="col-xs-12 text-left">
                                                    <a itemprop="url" href="<?php echo parse_url($this->requestHelper()->getRequestUri())['path'] . '?force=1'?>">                                                        
                                                        <span itemprop="name"><?php echo $this->translate('Delete cache this page')?></span>
                                                    </a>
                                                </div>
                                                <?php endif ?>
                                                <div class="col-xs-12 text-left">
                                                    <a itemprop="url" href="<?php echo $this->url('web/my')?>">
                                                        <span itemprop="name"><?php echo $this->translate('Profile')?></span>
                                                    </a>
                                                </div>
                                                <div class="col-xs-12 text-left">
                                                    <a itemprop="url" href="<?php echo $this->url('web/my', array(), array('query' => array('tab' => 'address')))?>">
                                                        <span itemprop="name"><?php echo $this->translate('My address')?></span>
                                                    </a>
                                                </div>
                                                <div class="col-xs-12 text-left">
                                                    <a itemprop="url" href="<?php echo $this->url('web/my', array(), array('query' => array('tab' => 'productorder')))?>">
                                                        <span itemprop="name"><?php echo $this->translate('Order list')?></span>
                                                    </a>
                                                </div>
                                                <div class="col-xs-12 text-left">
                                                    <a itemprop="url" href="<?php echo $this->url('web/my', array(), array('query' => array('tab' => 'password')))?>"><?php echo $this->translate('Change password')?></a>
                                                </div>
                                                <div class="col-xs-12 text-left">
                                                    <a itemprop="url" href="<?php echo $this->url('web/page', array('action' => 'logout'))?>">
                                                        <span itemprop="name"><?php echo $this->translate('Sign out')?></span>
                                                    </a>
                                                </div>
                                            </li>                                            
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        <?php else: ?>                
							<div class="btn-group">
								<a itemprop="url" href="<?php echo $this->url('web/signup')?>" class="btn btn-default btn-sm">
                                    <i class="fa fa-user pr-10"></i> 
                                    <span itemprop="name"><?php echo $this->translate('Sign up')?></span>
                                </a>
							</div>
							<div class="btn-group">
                                <a itemprop="url" href="<?php echo $this->url('web/login')?>" class="btn btn-default btn-sm">
                                    <i class="fa fa-lock pr-10"></i> 
                                    <span itemprop="name"><?php echo $this->translate('Login')?></span>
                                </a>								
                            </div>
						<?php endif; ?>
                        </div>
                        
						<!--  header top dropdowns end -->
					</div>
					<!-- header-top-second end -->
				</div>
			</div>
		</div>
	</div>
	<!-- header-top end -->
	
    <!-- header start -->
	<!-- classes:  -->
	<!-- "fixed": enables fixed navigation mode (sticky menu) e.g. class="header fixed clearfix" -->
	<!-- "dark": dark version of header e.g. class="header dark clearfix" -->
	<!-- "full-width": mandatory class for the full-width menu layout -->
	<!-- "centered": mandatory class for the centered logo layout -->
	<!-- ================ --> 
	<header class="header fixed clearfix">
		
		<div class="container">
			<div class="row">
                <nav class="navbar navbar-default custom_navbar_default custom_navbar_mobile" role="navigation">
                    <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header text-center vertical-image">
                            <table width="100%" cellpadding="0" cellspacing="0">
                                <tr>
                                    <td align="left" valign="middle" width="50">
                                        <button type="button" id="nav_collapse" class="navbar-toggle custom_navbar_toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                            <span class="sr-only">Toggle navigation</span>
                                            <span class="icon-bar custom_icon_bar"></span>
                                            <span class="icon-bar custom_icon_bar"></span>
                                            <span class="icon-bar custom_icon_bar"></span>
                                        </button>
                                    </td><td align="center" valign="middle">
                                        <a itemprop="url" href="/">
                                            <?php if (!empty($website['url_image'])): ?>
                                                <img itemprop="image" id="logo_img" src="<?php echo $website['url_image'] ?>" alt="<?php echo $website['name'] ?>">
                                            <?php else: ?>  
                                                <span class="logo-text"><?php echo $website['logo_text']; ?></span>
                                            <?php endif ?>  
                                        </a>

                                    </td>   
                                    <td align="right" valign="middle" width="50">
                                        <div id="mCart" class="btn-group" onclick="location.href='/carts/view'">
                                            <button type="button" class="btn">
                                                <i class="icon-basket-1"></i><span class="cart-count default-bg"><?php echo $totalQuantity ?></span>
                                            </button>
                                        </div> 
                                    </td> 
                                </tr>
                            </table>
                        </div>
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="navbar-collapse collapse navbar-submenu" id="bs-example-navbar-collapse-1" aria-expanded="false" style="height: 0px;">
                            <div class="panel-group collapse-style-3">
                                <?php foreach ($categories as $index => $category): ?>
                                <div class="panel panel-default" <?php if ($index==0) echo "style='border-top:0px'"?>>
                                    <?php if (!empty($category['sub'])) : ?> 
                                    <div class="panel-heading">
                                        <h4 itemprop="name" class="panel-title">
                                            <a itemprop="url" data-toggle="collapse" href="#collapse_category_<?php echo $index?>" aria-expanded="false" class="collapsed">
                                                <span itemprop="name"><?php echo $category['name']?></span>
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="collapse_category_<?php echo $index?>" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                        <div class="panel-body">
                                            <nav>
                                                <?php if (!empty($category['sub'])) : ?> 
                                                <ul itemprop="itemListElement" class="nav nav-pills nav-stacked list-style-icons">
                                                <?php foreach ($category['sub'] as $subCategory) : ?>  
                                                    <li>                                                        
                                                        <a itemprop="url" href="<?php echo $this->url('web/products', array('name' => name_2_url($subCategory['name'])))?>">
                                                            <i class="fa fa-chevron-circle-right"></i> 
                                                            <span itemprop="name"><?php echo $subCategory['name']?></span>
                                                        </a> 
                                                    </li>
                                                <?php endforeach ?>                                         
                                                </ul>
                                                <?php endif; ?>
                                            </nav>
                                        </div>
                                    </div>
                                    <?php else: ?>
                                    <div class="no-sub panel-heading">
                                        <h4 itemprop="name" class="panel-title">
                                            <a itemprop="url" href="<?php echo $this->url('web/products', array('name' => name_2_url($category['name'])))?>">
                                                <span itemprop="name"><?php echo $category['name']?></span>
                                            </a>
                                        </h4>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                <?php endforeach ?>
                            </div>
                            
                            <!--
                            <ul itemscope itemtype="http://schema.org/ItemList" class="nav navbar-nav">
                                <?php if (!empty($website['header_menus'])): ?>
                                <?php foreach ($website['header_menus'] as $menu) : ?>
                                <li <?php if (!empty($menu['sub'])) : ?>class="dropdown"<?php endif; ?>>                                            
                                    <a itemprop="url" href="<?php echo $menu['url']?>" class="dropdown-toggle" <?php if (!empty($menu['sub'])) : ?> data-toggle="dropdown"<?php endif; ?>>
                                        <span itemprop="name"><?php echo $menu['name']?></span>
                                    </a>
                                    <?php if (!empty($menu['sub'])) : ?> 
                                    <ul itemprop="itemListElement" class="dropdown-menu">
                                        <?php foreach ($menu['sub'] as $subMenu) : ?>                                         
                                        <li <?php if (!empty($subMenu['sub'])) : ?>class="dropdown"<?php endif; ?>>                                            
                                            <a itemprop="url" class="dropdown-toggle" <?php if (!empty($subMenu['sub'])) : ?> data-toggle="dropdown"<?php endif; ?> href="<?php echo $subMenu['url']?>">
                                                <span itemprop="name"><?php echo $subMenu['name']?></span>
                                            </a>
                                            <?php if (!empty($subMenu['sub'])) : ?> 
                                            <ul itemprop="itemListElement" class="dropdown-menu to-left">
                                                <?php foreach ($subMenu['sub'] as $subMenu2) : ?> 
                                                <li><a itemprop="url" href="<?php echo $subMenu2['url']?>"><span itemprop="name"><?php echo $subMenu2['name']?></span></a></li>
                                                <?php endforeach ?>   
                                            </ul>
                                            <?php endif; ?>                                                                                       
                                        </li>  
                                        <?php endforeach ?>                                         
                                    </ul>
                                    <?php endif; ?>	
                                </li>
                                <?php endforeach ?>
                                <li class="divider"></li>                                
                                <?php endif ?>      
                                
                                
                                <?php if (!empty($categories)): ?>                                
                                <?php foreach ($categories as $category): ?>
                                     <li>
                                        <a  href="<?php echo $this->url('web/products', array('name' => name_2_url($category['name'])))?>">
                                            <?php echo $category['name'] ?>
                                        </a>                                        
                                    </li>                                                                       
                                <?php endforeach ?>  
                                <?php endif ?>
                               
                               
                            </ul>    
                            -->
                            
                        </div><!-- /.navbar-collapse -->
                    </div><!-- /.container-fluid -->
                </nav>
				
                <div id="searchArea" class="hidden-lg hidden-md hidden-sm">
                <form id="searchForm" action="/search" role="search" class="m-search-box search-box margin-clear">
                    <div class="form-group has-feedback">
                        <input id="q" name="q" type="text" class="form-control" placeholder="<?php echo $this->translate('Enter product name or brand name')?>">
                        <i class="icon-search form-control-feedback"></i>
                    </div>                                
                </form>                
            </div>
                
			</div>
		</div>
        
            
       	
	</header>
	<!-- header end -->
    
</div>
<!-- header-container end -->